### ISSUE TITLE
ImportError: No module named pkg_resources－Mac OS X 10.10.4

### ISSUE THREAD

**Issue by lojunren** [dbcli/mycli#101]
When I try to run 'mycli' on my mac, it prompted "ImportError: No module named pkg_resources". 
I have installed org.python(2.7.10) and I have google how to solve this problem and it didn't work.

**Comment by amjith** [comment]
Can you tell me how you installed mycli? Did you install it via `brew install mycli` or `pip install mycli`?

**Comment by lojunren** [comment]
I installed mycli via brew install mycli.

**Comment by amjith** [comment]
Hrm. Can you check if you have `pip` available on the system? 

If it does, then try installing it via pip. 

You can try `pip install mycli`. 

You can also try upgrading setuptools. 

```
pip install --upgrade setuptools
pip install --upgrade distribute
```

I hope that helps.

**Comment by lojunren** [comment]
Great! It worked! Thanks very much!

**Comment by amjith** [comment]
Can you tell me which one you tried to make it work? So I can help others in the future if they encounter the same problem.
