### ISSUE TITLE
"use $database" vs "connect $database"

### ISSUE THREAD

**Issue by jots** [dbcli/mycli#103]
Switching databases with "use"  works fine.
switching with "connect"  leaves the tables from the previous database in the drop downs.

**Comment by amjith** [comment]
Confirmed. This is a bug. I'll fix this soon. 

Thank you for reporting.

**Comment by amjith** [comment]
I have fixed this issue in master. Try installing from master directly: 

```
pip install https://github.com/dbcli/mycli/archive/master.zip
```

I'll release the new version soon.

**Comment by amjith** [comment]
New version (1.2.0) is releasee to pypi. 

You can upgrade using `pip install -U mycli`.

**Comment by jots** [comment]
new version works great!  thanks for such fast work!
