### ISSUE TITLE
Change color during create database

### ISSUE THREAD

**Issue by rajeshisnepali** [dbcli/mycli#1031]
without the use of backtick **`**
![image](https://user-images.githubusercontent.com/23610013/153136123-503c3f89-eeb4-4f2e-b33e-5cfdbc6ce875.png)

use of backtick
![image](https://user-images.githubusercontent.com/23610013/153136181-dce86067-f5df-4e1d-a570-0d4cea532266.png)

The color of database is so hard to see.

**Comment by sgorange** [comment]
Just change your syntax_style in ~/.myclirc
```
# Syntax coloring style. Possible values (many support the "-dark" suffix):
# manni, igor, xcode, vim, autumn, vs, rrt, native, perldoc, borland, tango, emacs,
# friendly, monokai, paraiso, colorful, murphy, bw, pastie, paraiso, trac, default,
# fruity.
# Screenshots at http://mycli.net/syntax
syntax_style = native
```
