### ISSUE TITLE
Mysql Result:  Column is too long to show completely

### ISSUE THREAD

**Issue by Lilihx** [dbcli/mycli#1032]
I save a long json string (very long)  in Mysql.
When i select the row, the command line cannot show complete data.
Instead, it shows "{long json} ... "

When I want to copy the data to covert it to json, I have to save that to a file.

Is there any settings ?
How can i slove the problem ?

**Comment by j-bennet** [comment]
We experienced performance problems outputting huge blobs of text to the terminal before, so by default truncation is on. But you can still view full results by turning on vertical output for the current query with `\G`

```
select col1 from my_table where col2 = 1 \G
```

**Comment by Lilihx** [comment]
Thanks !!!
