### ISSUE TITLE
Pasting long queries can drop characters

### ISSUE THREAD

**Issue by amjith** [dbcli/mycli#104]
From Twitter: https://twitter.com/gbhorwood/status/627909096922951680

> it drops chars occasionally. really only an issue on 50 or more lines. 

I'm unable to reproduce it so far. I wonder if this is localized to a specific OS. I've only tried it on OS X.

**Comment by brewneaux** [comment]
I'm getting it dropping spaces at line breaks.  

Original query:
```SQL
CREATE TABLE temp_table
SELECT
    id,
    val,
    'broken' AS status
FROM 
    testt AS t
    JOIN testt AS t2
        ON t.id = t2.val
;

```
 CREATE TABLE temp_tableSELECT    id,    val,    'broken' AS statusFROM     testt AS t    JOIN testt AS t2        ON t.id = t2.val;
(1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id,    val,    'broken' AS statusFROM     testt AS t    JOIN testt AS t2        ' at line 1")
```

As you can see, on paste, I'm seeing it drop spaces before line breaks.  Really screws up anyone using Sublime Text's SendText plugin.

**Comment by amjith** [comment]
This happens because I have multi-line mode off. Multi-line mode is the one that enables queries to span across multiple lines. 

You can either enable it temporarily for a session by pressing F3 or enable it permanently via the config file (~/.myclirc).

**Comment by brewneaux** [comment]
With Multi-Line turned on, it does work, but does increasing indents...

```
mysql jbruno@localhost:jbruno>
 CREATE TABLE temp_table

SELECT
    id,
        val,
            'broken' AS status

            FROM
                testt AS t
                    JOIN testt AS t2
                            ON t.id = t2.val
                            ;
(1052, u"Column 'id' in field list is ambiguous")
```

**Comment by amjith** [comment]
I might need a paste mode. Not sure about this one. I'll try it out.

**Comment by michaelstack** [comment]
+1 for paste mode

**Comment by amjith** [comment]
Released as part of 1.6.0. Please upgrade: 

```
pip install -U mycli 
```

**Comment by petobens** [comment]
Hi @amjith. Consider the following query:
```sql
SELECT advertiser_id,
       applications.application_id,
       application_name,
       target_event,
       target_event_name,
       if(platform = 'android', 'google_advertising_id', 'apple_ifa') AS ref_type
FROM
  (SELECT id AS application_id,
          advertiser_id,
          name AS application_name,
          lcase(platform) AS platform
   FROM applications
   WHERE id = 433
  ) applications
INNER JOIN
  (SELECT event_id AS target_event,
          description AS target_event_name,
          application_id
   FROM applications_events
   WHERE event_id = 2093
    AND application_id = 433
  ) application_events
  ON application_events.application_id = applications.application_id
```
When I paste into mycli (using tmux on iterm) with the following tmux mapping:
```
bind p run-shell "tmux set-buffer \"$(pbpaste)\"; tmux paste-buffer"
```

it gets pasted like this:
<img width="2880" alt="screen shot 2017-12-08 at 14 50 33" src="https://user-images.githubusercontent.com/2583971/33778407-389cebe8-dc27-11e7-9711-7f859ca03b3c.png">

I can reproduce the same behaviour if I try to paste that query into vim using the tmux paste mapping. However if in  vim I enable paste mode then the query is correctly pasted. So my question is: you spoke about paste-mode in mycli... how do I enable it? (Note that I use vi-mode inside mycli). 
Thanks in advance!

BTW: I can paste normally with `Cmd + v` (i'm on mac) but I want to achieve the same behaviour within tmux (and using tmux paste-buffer)

**Comment by amjith** [comment]
I have verified this behavior on Linux. It works fine if I paste using Ctrl+V, but it gets weird when I paste using tmux paste-buffer. 

We never implemented the paste mode. 

To be honest this behavior is out of our control and it is a bug worth filing with prompt-toolkit the library we use to handle all of this for us. @jonathanslenders What are you thoughts?

**Comment by jonathanslenders** [comment]
The only effect of the prompt_toolkit paste_mode option is that it should not accept the input when "enter" has been pressed. Actually, I even consider removing this in 2.0, because everything can be implemented using normal key bindings.

What is see in @petobens screenshot, looks like a paste which is done without using bracketed paste.
Which tmux version are you using?

**Comment by petobens** [comment]
@jonathanslenders thanks for the quick reply. I'm using tmux latest version from master. 

I tried reproducing the behaviour with ptpython. The following gif shows what happens when pasting with and without paste mode (and always using the tmux paste mapping):

![dec-10-2017 12-33-50](https://user-images.githubusercontent.com/2583971/33806418-ab98e004-dda6-11e7-829d-f458199f2d95.gif)

Is this a tmux issue? i.e the `paste-buffer` should work as the standard `Cmd/Ctrl + v`? Thanks once again for looking into this.

**Comment by jonathanslenders** [comment]
Hi @petobens,
I can't reproduce this in ptpython. When I have paste mode disabled, it inserts additional indentation, but it doesn't drop characters. I think that the output of ``pbpaste`` could contain certain control sequences. Could you check the output of ``pbpaste|less``?

Secondly, can you try the following key binding for tmux?
This will paste use bracketed paste.

```sh
bind p run-shell "tmux set-buffer \"$(pbpaste)\"; tmux send-keys escape \"[200~\"; tmux paste-buffer; tmux send-keys escape \"[201~\" "
```

**Comment by petobens** [comment]
Hi @jonathanslenders , 
I checked the output of `pbpaste | less` but didn't find anything strange.

Your second solution worked marvelously!! Thank you so much. Mmm is this a bug in tmux?
