### ISSUE TITLE
Can we support clear command in mycli

### ISSUE THREAD

**Issue by ruanwenjun** [dbcli/mycli#1057]
Just like clear in linux.

**Comment by ruanwenjun** [comment]
> Hi I think there is no `clear` command in MySQL so it would be wired if there is one in mycli.
> 
> FWIW, you can use `Ctrl` + `L` to clear the screen (in any cli, pgcli, mysql, mycli, etc...)

Thanks, use `Ctrl` + 'L' is good enough.

**Comment by FluffyRudy** [comment]
what about "\! clear" which actually execute the command?
