### ISSUE TITLE
Non-readable suggestion popup

### ISSUE THREAD

**Issue by blackakula** [dbcli/mycli#107]
![86f48-clip-21kb](https://cloud.githubusercontent.com/assets/156983/9033742/5f1a89c6-39ca-11e5-88ff-5d9066dbc03f.jpg)
Great tool. It's totally working, but the suggestions popup is not readable in my CLI.
- VirtualBox: Ubuntu-server 1.14
- Putty

Is it possible to configure tool colors?

**Comment by amjith** [comment]
Hi @blackakula, it is possible to tweak the colors. You can set the color scheme in your config file which is located in the home folder (~/.myclirc). 

You can see a preview of all the color schemes here: http://mycli.net/syntax

**Comment by blackakula** [comment]
I see only predefined list of themes - they all have the same colors for popup. Is it possible to set specific color for popup text/background?

**Comment by amjith** [comment]
Sorry, not right now. Someone else requested this same feature for pgcli (https://github.com/dbcli/pgcli/issues/310). I had said no to them because I thought the colors I had chosen was legible. But now I realize that's not the case. I'll keep this ticket open and work on adding customizations to the colors.

**Comment by amjith** [comment]
@blackakula I've added a way customize the menu colors via the config file. You can install the new version from the git repo directly as follows: 

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

Open your config file (~/.myclirc) and add these following lines: 

```
[colors]
# Completion menus.
Token.Menu.Completions.Completion.Current = 'bg:#ffffff #000000'
Token.Menu.Completions.Completion = 'bg:#000000 #ffffff'
Token.Menu.Completions.MultiColumnMeta = 'bg:#aaffff #000000'
Token.Menu.Completions.ProgressButton = 'bg:#003333'
Token.Menu.Completions.ProgressBar = 'bg:#00aaaa'

# Selected text.
Token.SelectedText = '#ffffff bg:#6666aa'

# Search matches. (reverse-i-search)
Token.SearchMatch = '#ffffff bg:#4444aa'
Token.SearchMatch.Current = '#ffffff bg:#44aa44'

# The bottom toolbar.
Token.Toolbar.Off = 'bg:#222222 #888888'
Token.Toolbar.On = 'bg:#222222 #ffffff'

# Search/arg/system toolbars.
Token.Toolbar.Search = 'noinherit bold'
Token.Toolbar.Search.Text = 'nobold'
Token.Toolbar.System = 'noinherit bold'
Token.Toolbar.Arg = 'noinherit bold'
Token.Toolbar.Arg.Text = 'nobold'
```

I've se the menu colors to black and white which should give you plenty of contrast. But you're welcome to customize this to your needs.

**Comment by blackakula** [comment]
@amjith thanks! It works!
