### ISSUE TITLE
[question] is there a way to execute a .sql file?

### ISSUE THREAD

**Issue by adrianmeca** [dbcli/mycli#108]
Is there a way to use execute the content of a sql script using mycli?

for instance when you restore a mysqldump into another server you can do it in three ways
mysql [options] < dumpfile.sql
cat dumpfile.sql | mysql [options]
mysql [options] -e"source dumpfile"

Or using the interactive mode with the source statement. Is there any way with mycli?

**Comment by amjith** [comment]
Not yet. But that is one of the planned features. 

Thank you for requesting it. I'll keep this issue open to track the development.

**Comment by adrianmeca** [comment]
Thanks!

**Comment by amjith** [comment]
I've added `source` command to master. This allows you to execute an SQL file from the mycli prompt. 

Usage:

```
mycli> source filename.sql
```

You can install directly from master as follows: 

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

I'll release the new version to PyPI sometime this week.

**Comment by amjith** [comment]
The latest version of mycli (1.4.0) has this feature. Please upgrade. 

```
pip install -U mycli
```

**Comment by robsonpeixoto** [comment]
@amjith it will read all file before execute or will read and execute on demand?

**Comment by amjith** [comment]
@robsonpeixoto It will read all of the file and execute it. 

When you say "execute on demand" what do you mean by that?

**Comment by robsonpeixoto** [comment]
Read chunks of the file and execute the SQL comments that was read.
For example, I have an file with 20Gb of data. It'll consume a lot of memory to run.

**Comment by amjith** [comment]
Unfortunately we don't do partial read and execute for a couple of reasons. Right now the implementation will read the file and pass the contents directly to the database and we're done. If we were to do partial reading, we'd have to parse the contents to determine the end of a query and batch it to the database instance.

I'd prefer not to do that, since that is a source of many bugs, such as parsing the queries have to take into account quoted strings and other corner cases.

**Comment by robsonpeixoto** [comment]
Make sense. Thanks a lot and you are making a great job!

**Comment by Ostralyan** [comment]
Is there a way to pass an argument into this script? For example I'd like something like

source filename.sql 5

where in my script it'll be like id={arg1}

**Comment by chrisamow** [comment]
Is there filename completion on the source command?  (I did try it, but wondered if there is some way to config or if there are future plans)  Thanks for the great work!

**Comment by j-bennet** [comment]
@chrisamow We don't currently have file name completion. It's not impossible - feel free to file an issue for it, and we'll do our best.

**Comment by valerii15298** [comment]
Are there any updates on this? @amjith @j-bennet 
For me even `source filename.sql` does not work... basically hangs indefinetely
