### ISSUE TITLE
'less' 不是内部或外部命令，也不是可运行的程序或批处理文件。

### ISSUE THREAD

**Issue by zem558** [dbcli/mycli#1082]
![image](https://user-images.githubusercontent.com/45349060/188428169-fecd4961-902a-4064-b0a7-b05a447a2651.png)
windows11系统成功安装mycli，但是启动mycli然后执行mysql命令时无法正确显示对应结果，报异常：'less' 不是内部或外部命令，也不是可运行的程序或批处理文件。show tables命令能够识别到我的zhuenin数据库下有7张表，但是查询结果页面却没有显示。请问如何解决。

**Comment by amjith** [comment]
@zem558 Looks like `less` is not installed on the system. Can you try installing less.exe? http://gnuwin32.sourceforge.net/packages/less.htm

Or you can open up myclirc file located under `C:\Users\<username>\.myclirc` and set `enable_pager = False`. This will turn off using less for output.

**Comment by amjith** [comment]
Thank you for reporting back. I'm glad you were able to make it work. I'm going to close this issue now.
