### ISSUE TITLE
Some Words are Ineligible in Dark Mode

### ISSUE THREAD

**Issue by kolinkorr839** [dbcli/mycli#1115]
I am on mac and I use dark mode all the time. Is there a way for mycli to change the colors so that it can be visible? For example, below is a screenshot when I do a command. 

![Screen Shot 2023-05-06 at 3 54 18 PM](https://user-images.githubusercontent.com/22241742/236649493-763b6d74-08a5-4bd5-9a64-92164dabb3bc.png)

The command looks like this:
```
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY
```
As you can see the `@'%'` cannot be seen. Is there a way to fix this?

**Comment by amjith** [comment]
There are a lot of different themes that are dark which might be suitable for you. You can check your myclirc file located in ~/.myclirc. 

You can also look at all the themes on this page and pick. https://www.mycli.net/syntax

**Comment by kolinkorr839** [comment]
Thanks!
