### ISSUE TITLE
Code Snippets 

### ISSUE THREAD

**Issue by brewneaux** [dbcli/mycli#112]
Would be really neat, in the same way that we have favorited queries, to have code snippets of a sort.  Say you have a table whose name is "this_is_a_really_longandhardto_remember_tablename" - instead of typing it everything, you could just do something like thatlongtable, hit tab, and have it autofill.

**Comment by amjith** [comment]
That's where the fuzzy matching comes in handy. You can start typing parts of a long table name and it'll narrow them down for you. 

For eg: 

"this_is_a_really_longandhardto_remember_tablename"

Can be narrowed down by typing: 

"trelorta" 

Which are all characters in that table name in the right order.

**Comment by brewneaux** [comment]
Oh wow. I didn't realize it was THAT fuzzy.  Closing.

**Comment by amjith** [comment]
When someone first requested it #46, I thought it would be mountains of coding. But it was 10 lines of code.

Here's a description of the algorithm that was used. http://blog.amjith.com/fuzzyfinder-in-10-lines-of-python

**Comment by Herz3h** [comment]
This would be neat for other cases like the following:

type `select` press `tab` then it expands into:

`SELECT _ FROM _ `

And then you would be able to write columns and table name. I used mycli a lot and it gets very repetitive to type some common queries. > I know about fav queries though
