### ISSUE TITLE
Is there any documentation on creating a customer color scheme?

### ISSUE THREAD

**Issue by scottchiefbaker** [dbcli/mycli#113]
I'm not a big fan of the included color schemes. I'd like to create my own color scheme but I'm not seeing any documentation about how to go about this.

**Comment by amjith** [comment]
The color schemes are from a python library called Pygments. There is documentation on how to create custom color schemes on Pygments website. http://pygments.org/docs/styles/

Did you already check the gallery of themes: http://mycli.net/syntax . You can click on an image to switch between light and dark background.
