### ISSUE TITLE
How do I force a horizontal query result display? (Opposite of \G)

### ISSUE THREAD

**Issue by martin-greentrax** [dbcli/mycli#1135]
_First of all I love mycli, thank you for your work!_

mycli automatically switches to the vertical display of results when result columns are too long to fit the page (I guess).
I would still usually prefer a horizontal list even if it means I need to scroll left/right.

Is that possible with mycli currently? It has \G but I cannot find an option doing the opposite.

**Comment by rolandwalker** [comment]
Hi!

Do you have
```
auto_vertical_output = False
```
set in `~/.myclirc` ?

**Comment by martin-greentrax** [comment]
aah, yes!
Thank you, I did not realize I had the default values there
