### ISSUE TITLE
mycli on CentOS 6.6 - DistributionNotFound

### ISSUE THREAD

**Issue by dschuett** [dbcli/mycli#114]
I just installed mycli on my CentOS 6.6 machine using `yum install python-pip`, and then `pip install mycli`. Everything seemed to install successfully, but now I am unable to use mycli at all without getting the following:

`[root@smtp1 ~]# mycli --help
Traceback (most recent call last):
  File "/usr/bin/mycli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PyMySQL>=0.6.6`

OR

 `mycli -h localhost -u root mailscanner
Traceback (most recent call last):
  File "/usr/bin/mycli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PyMySQL>=0.6.6`

**Comment by dschuett** [comment]
Update: I just uninstalled mycli using `pip uninstall mycli` and tried to reinstall. Here is the output of my install:

`[root@smtp1 tmp]# pip install mycli
Collecting mycli
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached mycli-1.2.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): click>=4.1 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): prompt-toolkit==0.45 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): PyMySQL>=0.6.6 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): sqlparse==0.1.14 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): configobj>=5.0.6 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/lib/python2.6/site-packages (from prompt-toolkit==0.45->mycli)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /usr/lib/python2.6/site-packages (from prompt-toolkit==0.45->mycli)
Installing collected packages: mycli
  Running setup.py install for mycli
Successfully installed mycli-1.2.0`

**Comment by amjith** [comment]
@dschuett There is something wrong with pip in Centos. 

Can you try upgrading setuptools and pip? 

You can do that using:

```
pip install -U setuptools
pip install -U distribute
pip install -U pip
```

After that try installing mycli again. 

```
pip uninstall mycli && pip install mycli
```

That should hopefully fix all the issues.

**Comment by dschuett** [comment]
This didn't seem to solve the issue. Now I can't even install mycli. See below:

** Note I had Already uninstalled mycli

```
[root@mtp1 tmp]# pip install -U setuptools
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting setuptools
  Downloading setuptools-18.1-py2.py3-none-any.whl (461kB)
    100% |████████████████████████████████| 462kB 790kB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 0.6rc11
    DEPRECATION: Uninstalling a distutils installed project (setuptools) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling setuptools-0.6rc11:
      Successfully uninstalled setuptools-0.6rc11
Successfully installed setuptools-18.1
```

```
[root@smtp1 tmp]# pip install -U distribute
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting distribute
  Downloading distribute-0.7.3.zip (145kB)
    100% |████████████████████████████████| 147kB 1.1MB/s
Requirement already up-to-date: setuptools>=0.7 in /usr/lib/python2.6/site-packages (from distribute)
Installing collected packages: distribute
  Found existing installation: distribute 0.6.10
    Uninstalling distribute-0.6.10:
      Successfully uninstalled distribute-0.6.10
  Running setup.py install for distribute
Successfully installed distribute-0.7.3
```

```
[root@smtp1 tmp]# pip install -U pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

```
[root@smtp1 tmp]# pip install mycli
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by dschuett** [comment]
UPDATE:

I had to run the setuptools py script found on the selected answer on this page:

[Link Here](http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources)

**Comment by amjith** [comment]
This is the worst. I'm sorry about all of this. 

I'm not really sure why this is happening. I'm unable to reproduce it on my Centos VM. I'm glad you resolved it. 

Sorry about all the hassle.

**Comment by dschuett** [comment]
No problem at all. Do you think you will eventually make an rpm?

**Comment by amjith** [comment]
Yes. I just have to learn how to do it. 

It took me a full week to actually understand how to create debian packages. So it's a matter of finding the time to to do it. :(
