### ISSUE TITLE
Feature request: ability to search existing log files, similar to mysqlbinlog

### ISSUE THREAD

**Issue by ramiabraham** [dbcli/mycli#115]
Is there presently a manner by which you can search an existing bin log, eg a binary dump like mysql-bin.000120, using mycli?

I would adore such a feature.

**Comment by amjith** [comment]
I have not used mysqlbinlog. This is new to me. But at a first glance it seems like it's a separate utility and not part of the mysql repl. 

I don't think it is in the scope of mycli. Sorry.
