### ISSUE TITLE
Make autocomplete more context-aware

### ISSUE THREAD

**Issue by vtdmhd** [dbcli/mycli#120]
For example, immediately after "SELECT " the autocomplete proposes "Alter table".

**Comment by amjith** [comment]
Right now the context aware completion can suggest either tables or columns or keywords. But the completion engine is not smart enough to order the keywords in a relevant order. 

That will require a more complicated completion engine. One which I'm not sure I can write. 

A possible solution optimization is to rank the keywords based on frequency.

**Comment by danieljwest** [comment]
Not so familiar with this, but I've been tinkering a little. 
I'm not seeing the above result at all. 
With Smart Complete on and supplying "SELECT " the autocomplete proposes field level functions such as AVG, COUNT, DISTINCT, etc. If I supply a table the autocomplete is smart enough to list the fields in the table as well. It's only if I turn smart complete off that I receive "Alter table" as an option.

Is there something I'm missing?

**Comment by amjith** [comment]
@danieljwest You're right, I didn't check to confirm the report. 

@vtdmhd Do you have the smart-completion off? That's the only way you could see the behavior you're seeing.

**Comment by amjith** [comment]
Please reopen if you have other questions.
