### ISSUE TITLE
Can't connect - connection refused

### ISSUE THREAD

**Issue by Flynsarmy** [dbcli/mycli#126]
On OSX 10.10.4 a newly installed copy of mycli can't connect to mysql no matter what I do. Mysql is running on the standard port and I confirmed my credentials are correct. Example:

```
➜  mysql -umylogin
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 20463
Server version: 5.5.42 Source distribution

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
➜  mycli -umylogin
(2003, "Can't connect to MySQL server on u'localhost' ([Errno 61] Connection refused)")
```

I also tried an account with a password and same issue. Connection refused. I added -hlocalhost to both commands - mysql worked, mycli didn't.

**Comment by amjith** [comment]
I suspect that there is an issue with connecting via socket. Can you try the -S option?

mycli -S /tmp/mysql.sock

or path to your socket file?

**Comment by Flynsarmy** [comment]
Got it. `mycli -umylogin -S /Applications/MAMP/tmp/mysql/mysql.sock`. Sorry about that.
