### ISSUE TITLE
cannot show the '*' charactor using mycli in tmux.

### ISSUE THREAD

**Issue by jinleileiking** [dbcli/mycli#127]

**Comment by amjith** [comment]
Can you elaborate, what you mean? 

I don't understand your request. Are you reporting that '*' character is invisible when you type in a query or is it throwing an error if it is present in the results?

**Comment by danieljwest** [comment]
Attempted to reproduce it in tmux, but I was able to see everything fine. I assume it's a theming issue?

**Comment by jinleileiking** [comment]
When I type "select count(*) from ..." it will show " select count( ) from ..."

```
mysql jinleileiking@localhost:(none)> select COUNT(*) 
+------------+
|   COUNT(*) |
|------------|
|          1 |
+------------+
1 row in set
```

**Comment by jinleileiking** [comment]
Oh it seem that it is the theme problem . mycli not use default terminal theme ?

My env is : terminator + solarized color theme

**Comment by amjith** [comment]
The colorschemes can be changed via the config file. Please check ~/.myclirc. 

The gallery of themes can be found here: http://mycli.net/syntax
