### ISSUE TITLE
Add option for lowercase keyword completion

### ISSUE THREAD

**Issue by dgoosens** [dbcli/mycli#128]
Hi,

Thanks for this great tool...

I personally like my SQL statements to be in lowercase...
Would it be possible to add this feature ?
I guess a boolean in the config file could enable/disable it...

**Comment by amjith** [comment]
It's doable but adds more complexity that makes it hard to maintain. For example, I have to be careful not to change the case for table/column names, but only change the case for keywords, functions etc. 

Again it's doable but it'll get a bit cumbersome to maintain. I'd prefer to keep the code base small, if I can help it.

**Comment by darikg** [comment]
I wonder if this could be addressed simultaneously with dbcli/pgcli#287 by moving all the hard-coded completions to external config files, which could then be re-ordered or re-capitalized at will. That's another step down the road to config hell though.

**Comment by amjith** [comment]
That's an interesting idea. I'm still hesitant about adding more config options. If there are more requests for this feature, I'll definitely consider implementing it.

**Comment by tsroten** [comment]
This was requested via https://github.com/dbcli/mycli/issues/473.

**Comment by tsroten** [comment]
This is now addressed by https://github.com/dbcli/mycli/pull/476. It will be in the next release of mycli.

**Comment by tsroten** [comment]
@dgoosens This is included as of version 1.11.0. If you installed via `pip`, you can upgrade by running `pip install --upgrade mycli`.

To use this, just add this to your `~/.myclirc`:
```conf
keyword_casing = lower
```

We also support `auto` which will suggest upper or lower case based on how you type.

Thanks for the idea!

**Comment by dgoosens** [comment]
Brilliant !  
Thanks
