### ISSUE TITLE
Keyword 'LIKE' is not working well

### ISSUE THREAD

**Issue by cxbig** [dbcli/mycli#135]
The completion of keyword LIKE is not working well.
I have to type the full word to get this completion.
![like-issue](https://cloud.githubusercontent.com/assets/1363706/9411135/993fdcec-4824-11e5-9fa6-da371026c12b.gif)

**Comment by amjith** [comment]
You're right. I'll investigate why this is the case. 

Thank you for reporting.

**Comment by amjith** [comment]
@darikg I'm noticing this in pgcli as well, which is expected since they use the same completion engine. I think this started after we added the extra detection into the WHERE clause. Do you have time to take a look at this?

**Comment by darikg** [comment]
Sure I'm on it

**Comment by amjith** [comment]
The latest version of mycli (1.4.0) has a fix for this. Please upgrade. 

```
pip install -U mycli
```
