### ISSUE TITLE
Support \R or prompt command.

### ISSUE THREAD

**Issue by yuntas** [dbcli/mycli#136]
# I would like you to add [mysql command](https://dev.mysql.com/doc/refman/5.6/en/mysql-commands.html "mysql command")

**Comment by amjith** [comment]
I don't understand your request. 

Can you explain what exactly you'd like me to add?

**Comment by yuntas** [comment]
I'm studying MySQL.

So, I'm suggesting because I had to type [\R] command in order to change prompt.

p.s. Do you plan on expanding completion about DCL(Data Control Language, e.g. ROLLBACK, TRANSACTION)

**Comment by amjith** [comment]
I see. You're interested in getting \R working. You can change the prompt via the config file ~/.myclirc. I'll consider adding support for \R command. 

Adding support for ROLLBACK and TRANSACTION should be easy. I'll try and handle that soon.

**Comment by yuntas** [comment]
Thank you very much, Mr.amjith.

I understood !!

I try to do it.

Is it right that  I change the _.myclirc_ (line 47 ~ 53), 

```ruby:.myclirc
47 # MySQL prompt
48 # \t - Product type (Percona, MySQL, Mariadb)
49 # \u - Username
50 # \h - Hostname of the server
51 # \d - Database name
52 # \n - Newline
53 prompt = '\t \u@\h:\d> '
```

line 53 [prompt = '\R \t \u@\h:\d>']

??

sorry, I'm fool...

Thank you for your help with this suggestion.

**Comment by amjith** [comment]
Yes you can change line 53 to set your prompt. Mycli doesn't have all of the supported prompt variables from mysql. You can only use the ones listed in the comments in line 47 - 52.

**Comment by yuntas** [comment]
I got it.

Thank you very much, Mr.amjith.

**Comment by mdsrosa** [comment]
I'm not sure here. Are we going to support the `\R` command?

**Comment by amjith** [comment]
Yes. The plan is to add a special command called \R to change the prompt during runtime.

**Comment by mdsrosa** [comment]
Nice! I'll look into this `\R` command to know more about it and maybe add it to mycli. I'll let you know when and if I start implementing it. :)

**Comment by mdsrosa** [comment]
@amjith I'm working on this. :smile:
