### ISSUE TITLE
Can not run 'mycli -u root' and got ImportError: cannot import name inherit

### ISSUE THREAD

**Issue by smcdl** [dbcli/mycli#137]
When I run the command 'mycli -u root' then I got below:
Traceback (most recent call last):
  File "/usr/bin/mycli", line 7, in <module>
    from mycli.main import cli
  File "/usr/lib/python2.7/site-packages/mycli/main.py", line 39, in <module>
    from .lexer import MyCliLexer
  File "/usr/lib/python2.7/site-packages/mycli/lexer.py", line 1, in <module>
    from pygments.lexer import inherit
ImportError: cannot import name inherit

Please help me, thanks.

**Comment by amjith** [comment]
Sorry about the trouble. 

Can you tell me what is the version of mycli you're using? 

Also did you install it using pip or did you install it using brew or deb packages?

My guess is that there is already a version of pygments in your path which is an older version. 

Here are a few things to try:

* Try upgrading Pygments. `pip install -U pygments`
* Try installing mycli using easy_install instead of pip. `easy_install mycli`. 

Let me know how that goes.

**Comment by smcdl** [comment]
2015-08-26 23:05 GMT+08:00 Amjith Ramanujam <notifications@github.com>:

**Comment by smcdl** [comment]
Sorry, I reply you a empty email before. The version of mycli is 1.4.0 .
I install it by pip in the first. I also use the easy_install as you
mentioned, but it doesn't work.
BTW, the pygments was already up-to-date.

2015-08-26 23:05 GMT+08:00 Amjith Ramanujam <notifications@github.com>:

**Comment by amjith** [comment]
Try uninstalling completely and then reinstalling. 

```
pip uninstall mycli 
pip uninstall pygments
```

```
easy_install mycli 
```

I have a suspicion that pygments is corrupted. So uninstalling it first and then reinstalling mycli (which will install pygments as a dependency) might be able to fix it.

**Comment by smcdl** [comment]
Hi Amjith Ramanujam

Great, you fix my problem perfectly. Thank you very much.
There was another question when I run mycli, the program show me a warning
message like this:

/usr/lib/python2.7/site-packages/mycli-1.4.0-py2.7.egg/mycli/main.py:565:
Warning: Click detected the use of the unicode_literals __future__ import.
This is heavily discouraged because it can introduce subtle bugs in your
code.  You should instead use explicit u"" literals for your unicode
strings.  For more information see http://click.pocoo.org/python3/
  @click.argument('database', default='', nargs=1)

BTW, my system is CentOS7.


2015-09-01 22:56 GMT+08:00 Amjith Ramanujam <notifications@github.com>:

**Comment by amjith** [comment]
Yes that warning will be fixed in the next release.
