### ISSUE TITLE
ImportError: cannot import name zip_longest

### ISSUE THREAD

**Issue by Tahvok** [dbcli/mycli#138]
Just tried this on clean centos 7.
Used `pip install mycli` to install it.

```
# mycli -uroot -p
Traceback (most recent call last):
  File "/usr/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.4.0', 'console_scripts', 'mycli')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/mycli/main.py", line 18, in <module>
    from prompt_toolkit.shortcuts import create_default_layout, create_eventloop
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 35, in <module>
    from .layout.menus import CompletionsMenu, MultiColumnCompletionsMenu
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/layout/menus.py", line 3, in <module>
    from six.moves import zip_longest
ImportError: cannot import name zip_longest
```

**Comment by amjith** [comment]
Sorry about that. 

Looks like Centos is not playing well with pip for some reason. Can you try easy_install? 

`easy_install mycli`

Let me know if easy_install works for you.

**Comment by Tahvok** [comment]
You don't need to apologize, bugs always happen, and we should only be thanking you for this awesome tool :)

Same problem after easy_install:

```
# easy_install mycli
Searching for mycli
Best match: mycli 1.4.0
Adding mycli 1.4.0 to easy-install.pth file
Installing mycli script to /usr/bin

Using /usr/lib/python2.7/site-packages
Processing dependencies for mycli
Finished processing dependencies for mycli

# mycli -u root -p
Traceback (most recent call last):
  File "/usr/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.4.0', 'console_scripts', 'mycli')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/mycli/main.py", line 18, in <module>
    from prompt_toolkit.shortcuts import create_default_layout, create_eventloop
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 35, in <module>
    from .layout.menus import CompletionsMenu, MultiColumnCompletionsMenu
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/layout/menus.py", line 3, in <module>
    from six.moves import zip_longest
ImportError: cannot import name zip_longest
```

**Comment by Tahvok** [comment]
I need to add that this worked fine on a clean install of centos 7 about a month ago. Not sure what's the difference now.

**Comment by amjith** [comment]
There are a couple of things you can try. 

1. Try installing an older version of mycli. 

```
pip install mycli==1.3.0
```

2. Try upgrading six, since that seems to be issue. 

```
pip install -U six
```

You might need sudo for these commands. I'll try to get a Centos 7 VM running to try it locally.

**Comment by Tahvok** [comment]
Got it working now. I just played around with different versions of mycli and six.
The same problem came up on older versions of mycli. What fixed it was downgrading six to an older version, and upgrading it after to latest version again. It seems that the first time installing mycli got a corrupted six package somehow.
Just run this commands:
pip install six==1.3.0
pip install -U six

I will create a new clean centos 7 machine, and test if the same problem appears there after installing mycli. I'll report back here.

Full log of what I did:
https://gist.github.com/Tahvok/2aef0991d4cd2cd0a248

**Comment by Tahvok** [comment]
Confirmed, no problem on a newly installed server. I probably had some corruption during installation of six.
Thanks!

**Comment by amjith** [comment]
Thank you for digging into this and providing me with the full log, that was very helpful in seeing the complete picture. 

Looks like `pip uninstall six && pip install six ` is the key. It's really weird because you're not the first person who ran into issues with six and Centos. But every problem reported about this issue has a different error signature.

I'm glad you got it working. Thanks again for posting back your solution. :)
