### ISSUE TITLE
how to show the complete line result

### ISSUE THREAD

**Issue by kakiezhang** [dbcli/mycli#140]
i have a novice, look the picture i just took like below : 
![image](https://cloud.githubusercontent.com/assets/2803225/9511319/026bd716-4ca8-11e5-8908-167157e9f1b4.png)

That query didn't show the entire result in one line, even i know can use the "\G" to replace ";" to show it, but i just wonder how can i watch the whole result in that situation;

**Comment by amjith** [comment]
@kakiezhang You can use the left/right arrow to horizontal scroll the results. 

Right now the options passed into the pager makes it so the output doesn't wrap around. But you can change that by pressing `Shift-S` when the pager is active or you can permanently change the behavior by setting the pager value in `~/.my.cnf` under the `[client]` section as follows: 

```
pager = 'less -RXF'
```

That will make sure the output is always wrapped but for tables with lots of columns the wrapped output will look unreadable.

**Comment by kakiezhang** [comment]
@amjith oh, yes, it works, pretty thanks!
