### ISSUE TITLE
'ascii' codec can't decode byte 0xac in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by biniama** [dbcli/mycli#145]
Hello.

I connected to my database from my terminal (Mac OS) and when I run, 
```
SELECT * FROM job ORDER BY job_id DESC
```
I got the following error:
```
'ascii' codec can't decode byte 0xac in position 0: ordinal not in range(128)
```

mycli works when I run other commands.

**Comment by amjith** [comment]
Sorry about the bug. Can you run the same query in the default mysql client and paste the output here? 

I'm curious to know what is causing this to break. 

Also can you tell me what OS you're using and what version of mycli you're using?

**Comment by biniama** [comment]
When I run it in the default client, I get the list of jobs.
My OS is Mac OSX Yosmite and Terminal Version 2.5.3 (343.7)

This is the tool I have been waiting for to have and I am interested if it works. 
Thanks for developing it and the help.

**Comment by amjith** [comment]
@biniama I wanted to see the output because the error you're getting is due to unicode decoding issues. I'm assuming that the results has non-english characters. But if it is encoded with utf-8 then it should work. 

Can you tell me what is the default encoding for the database? You can find that information using the following query: 

```
SELECT @@character_set_database, @@collation_database;
```

**Comment by biniama** [comment]
You are right and so smart.
It is because the character set is latin.
```
mysql> SELECT @@character_set_database, @@collation_database, job_id FROM job ORDER BY job_id DESC limit 1;
+--------------------------+----------------------+--------+
| @@character_set_database | @@collation_database | job_id |
+--------------------------+----------------------+--------+
| latin1                   | latin1_swedish_ci    |   3351 |
+--------------------------+----------------------+--------+
1 row in set (0.00 sec)
```

Is there a way to pass a parameter to render as unicode? Or what shall I do?
Thanks.

**Comment by amjith** [comment]
@biniama I knew that choosing utf-8 was going to come back and bite me. Here's a work around:

Open your `~/.my.cnf` file (create this file if it doesn't exist already) and set the default encoding in that file as follows:

```
[client]
default-character-set = 'latin1'
```

If you already have that file, then add the `default-character-set = 'latin1'` line under the `[client]` section. 

This will force mycli to use latin1 as the encoding.

**Comment by amjith** [comment]
@biniama Were you able to get it working by setting the character set to 'latin1' in your my.cnf file?

**Comment by biniama** [comment]
I added that to .myclirc and added .my.cnf under /User/username but the same error is happening.

**Comment by amjith** [comment]
Adding it to `~/.myclirc` won't work. But adding it to `~/.my.cnf` should work. Did you add it under the sub-section `[client]` ? It should look like this: 

```
[client]
default-character-set = 'latin1'
```

**Comment by flyingfoxlee** [comment]
+----------------------------+------------------------+
| @@character_set_database   | @@collation_database   |
|----------------------------+------------------------|
| utf8                       | utf8_general_ci        |
+----------------------------+------------------------+
I have the above encoding setting, still I got this error.

**Comment by tsroten** [comment]
@flyingfoxlee Could you please be more specific -- what encoding setting do you have? Post the relevant portion of your `~/.my.cnf`.

**Comment by amjith** [comment]
@flyingfoxlee That's very surprising that it is still broken. Can you tell us if you have a specific charset in your config file? Typically the charset is specified in your `my.cnf` using `default-charcter-set` option. This file can be located in the following locations: 

```
/etc/my.cnf
/etc/mysql/my.cnf
/usr/local/etc/my.cnf
~/.my.cnf
```

If you don't have that line in your config file, try adding it yourself and setting it to `utf8` in your `client` section.

Here's an example:

```
[client]
default-character-set = 'utf8'
```

**Comment by tsroten** [comment]
@biniama Any luck?

**Comment by amjith** [comment]
Please reopen the issue if the problem still persists.

**Comment by sbusch** [comment]
@amjith could you please reopen this issue?

I have the a similiar (the same?) problem, but not for `SHOW DATABASES` but when selecting some (auto-generated) data contained in fields of type "JSON" (`SELECT * FROM MYTABLE`). It definitely depends on the data, because the query does not throw an exception when JSON field is empty (`{}`). 

With `mysql` this query just works fine...

Here`s the traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mycli/sqlexecute.py", line 116, in run
    for result in special.execute(cur, sql):
  File "/usr/local/lib/python3.4/dist-packages/mycli/packages/special/main.py", line 56, in execute
    raise CommandNotFound
mycli.packages.special.main.CommandNotFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.6.0', 'console_scripts', 'mycli')()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mycli/main.py", line 750, in cli
    mycli.run_cli()
  File "/usr/local/lib/python3.4/dist-packages/mycli/main.py", line 546, in run_cli
    raise e
  File "/usr/local/lib/python3.4/dist-packages/mycli/main.py", line 512, in run_cli
    for title, cur, headers, status in res:
  File "/usr/local/lib/python3.4/dist-packages/mycli/sqlexecute.py", line 119, in run
    yield self.execute_normal_sql(sql)
  File "/usr/local/lib/python3.4/dist-packages/mycli/sqlexecute.py", line 124, in execute_normal_sql
    num_rows = cur.execute(split_sql)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1292, in read
    self._read_result_packet(first_packet)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1347, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1385, in _read_rowdata_packet
    rows.append(self._read_row_from_packet(packet))
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1396, in _read_row_from_packet
    data = data.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdc in position 865: ordinal not in range(128)
```

Default encodings:

```
> show VARIABLES like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
|--------------------------+----------------------------|
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```
Setting `default-character-set = 'latin1'` in `~/.my.cnf` doesn't work:

```
> show VARIABLES like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
|--------------------------+----------------------------|
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```
As you can see the setting is used but I get the same error.

**Comment by jyouAc** [comment]
```
whereis python #to find where the Lib location
```

and add this to Lib/python2.7/site-packages/sitecustomize.py
```
# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

and it works!

**Comment by tsroten** [comment]
@sbusch Hello! I'm sorry you're having trouble with this. Can you please show us your locale's encoding by running this in your shell?
```bash
echo ${LANGUAGE:-none} && echo ${LC_ALL:-none} && echo ${LC_CTYPE:-none} && echo ${LANG:-none}
```
