### ISSUE TITLE
why there is a "percona" at the begining of every input line ?

### ISSUE THREAD

**Issue by JayMiao** [dbcli/mycli#156]
Can I hide it ?
It shows like this.
percona vip@192.168.0.1:premium>

**Comment by tsroten** [comment]
@JayMiao `percona` is the product type (other examples include mysql and mariadb). You can hide it by [modifying your `~/.myclirc` per the documentation](http://mycli.net/config). Specifically, you might try changing this line:
```
prompt = '\t \u@\h:\d> '
```

to something like this:
```
prompt = '\u@\h:\d> '
```

**Comment by amjith** [comment]
@JayMiao I hope @tsroten's suggestion solved the issue for you.

If not please feel free to reopen the issue.

**Comment by JayMiao** [comment]
Thanks, it helps.
