### ISSUE TITLE
System wide myclirc

### ISSUE THREAD

**Issue by alasdairdc** [dbcli/mycli#161]
Should create a default myclirc in /etc/defaults (on Debian based distros) when can then be overriden by the users ~/.myclirc if they wish to change the behaviour.

Will make it easier for SysAdmins to control users setup.

Additional option to disable checking/parsing of ~/.myclirc in system wide config would also be great.

**Comment by amjith** [comment]
This is definitely possible but can you tell me why we'd need a system wide config file? All the config options are for personal fine tuning such as what keybindings to use or the syntax color theme etc. It seems too restrictive to disallow honoring the local ~/.myclirc.

**Comment by alasdairdc** [comment]
Technically a system-wide config is not needed but it would make sysadmins job easier if this was the default file created as then if the sysadmin decides to install mycli across all servers they managethis would allow a consistent setup for all users e.g. defaulting multi_line = True for instance for all users across many systems (e.g. if deployed via puppet) .  The system-wide config becomes the file created if it does not exist and can be overridden by a users ~/.myclirc if the user wishes to create one to alter the sysadmin determined behaviour.  Ignore the suggestion of disabling parsing of the users. but I feel it would be better for SAs if the config file created was an overridable system config. otherwise any SA wanting a consistent setup needs to create the 'default' config for every user in every users home dir.  If that makes sense.

**Comment by amjith** [comment]
Yup. That makes sense. I'll add in a check for /etc/myclirc.

**Comment by tsroten** [comment]
@amjith I was thinking over implementing this, but I'm not sure how this will work. Right now, mycli creates a default config file in the user's home directory. This file needs to be able to override system defaults. So, checking for a system file would be pointless unless we stop creating the config file in the user's directory. What do you think?

**Comment by amjith** [comment]
That is a good observation. 

How about we check to see if /etc/myclirc is available if it is, then we'll copy that file into the ~/.myclirc instead of using our default file.

**Comment by alasdairdc** [comment]
Instead of creating ~/.myclirc you create /etc/myclirc and parse that always then check for the presence of ~/.myclirc and update the program settings with anything found inside there.

**Comment by amjith** [comment]
We're not going to have permissions to create /etc/myclirc file, since we don't create that file at install time. 

I'd be wary of writing config files in root privileged locations.

**Comment by alasdairdc** [comment]
you do have permissions to create it install time if installed from the repository https://packagecloud.io/amjith/mycli

**Comment by amjith** [comment]
Yes. But there are different ways in which people install mycli. One of them is debian packages, but there is also via pip or easy_install, maybe via RPM in the future. 

So having it create the files in all of those means is a rather daunting task. We also have to make sure that installing a new version doesn't overwrite the existing file. So I'm going to stick with the simpler approach of creating the file at first launch. 

If there is a file available at /etc/myclirc we'll copy that to the local home folder. Do you anticipate any problems with this approach? If you see any loopholes to this approach please let us know.

**Comment by alasdairdc** [comment]
The problem with copying to every users home would be a pain for SAs to maintain in a multiuser environment.

How about only create ~/.myclirc if /etc/myclirc does not exist (leaving it to the SA to create or move his ~/.myclirc to /etc/myclirc).  If /etc/myclirc does exist do not create ~/.myclirc.  If both exist source /etc/myclirc first then update settings with any entries in ~/.myclirc.  This way the SA can still create + maintain the system-wide default easily and if a particular user wishes to change it for theirs then they can, but every other user is using the system-wide default and if the SA needs to make a change it only needs done to one file and not the one in everyone's home.  If someone has overridden it for themselves then they have their home version and that is fine/their choice.  Also easier to spot someone who has decided to override it instead of having to compare hashes of files to know which to update.

I hope this makes sense to you.

**Comment by amjith** [comment]
I think that's a fair request. 

@tsroten To summarize, we create the ~/.myclirc file in the home folder only if /etc/myclirc file is not present. I'm open to hear your feedback.

**Comment by alasdairdc** [comment]
I think thats a decent compromise.  Just trying to make it easier for SAs to manage in a production environment and make it easier for you to get the package accepted to the official Debian / RHEL / Centos / etc repositories.

**Comment by tsroten** [comment]
That sounds good to me. I'll work on it this weekend.

**Comment by tsroten** [comment]
@alasdairdc This issue has an [open pull request](https://github.com/dbcli/mycli/pull/200) now. Sorry for taking so long!

**Comment by alasdairdc** [comment]
@tsroten No problem I understand the juggling everyone does on Github.  Thanks for the integration.
