### ISSUE TITLE
vi-mode dt and df works incorrectly

### ISSUE THREAD

**Issue by rehno-lindeque** [dbcli/mycli#167]
In vi-mode with the cursor positioned as follows:

```
|abcdef
```

---

The key-combo `dte` results in:

```
|def
```

and the key-combo `dfe` results in:

```
|ef
```

---

The correct result for `dte` should be:

```
|ef
```

and `dfe` should be:

```
|f
```

**Comment by amjith** [comment]
You are correct. I believe this is an oversight in prompt_toolkit's implementation of vi-mode. I'll see what I can do about that.

**Comment by tsroten** [comment]
Closing as the fix for this was merged into Python Prompt Toolkit in February 2016 and has been released since then.
