### ISSUE TITLE
Make pycrypto optional

### ISSUE THREAD

**Issue by amjith** [dbcli/mycli#169]
PR #152 brought in the dependency for pycrypto. This is used to parse the mylogin.cnf file. 

This is a hard package to install on Windows. So I'd like to make pycrypto an optional dependency. When pycrypto is installed we can read mylogin.cnf, when it is not available we will skip reading mylogin.cnf but print a warning message at startup that we found a mylogin.cnf file but did not read in the details due to missing pycrypto package.

**Comment by j-bennet** [comment]
You mind if I take this @amjith?

**Comment by amjith** [comment]
It is now yours @j-bennet.
