### ISSUE TITLE
Command Time 0 on MariaDB 10.0

### ISSUE THREAD

**Issue by jkavalik** [dbcli/mycli#172]
I ran a query which took around 10s (checked with mysql cli) but the Command Time shows 0
```sql
mariadb root@localhost:vic_main> select count(1) from table1 where text like '%test%';
+------------+
|   count(1) |
|------------|
|       9670 |
+------------+
1 row in set
Command Time: 0.000s
Format Time: 0.000s
```
I verified it with some more queries, the Command Time shows 0 all the time.

Server version is 10.0.21-MariaDB on Ubuntu 12.04

**Comment by amjith** [comment]
Sorry about that broken timing. We started using generators in mycli for query results and that meant we weren't consuming the results until we started formatting the table. So this resulted in zero time for command time. 

I've created a new PR #173 to fix this and consolidate both command time and format time into a single value. 

You can try it out yourself by installing it directly from the branch with the fix:

`pip install https://github.com/dbcli/mycli/archive/amjith/consolidate-timing.zip`

**Comment by jkavalik** [comment]
That was fast. And works well. Thank you.
```sql
mariadb root@localhost:vic_main> select sleep(2);
+------------+
|   sleep(2) |
|------------|
|          0 |
+------------+
1 row in set
Time: 2.003s
```
