### ISSUE TITLE
Connection via ssh

### ISSUE THREAD

**Issue by msztolcman** [dbcli/mycli#18]
I don't know this is possible for current mycli architecture and libs, but many GUI tools have an option to connect via ssh to remote host, and then connect to local mysql. This is very useful, because often admins do not allow to connect to mysql from remote hosts, or only from specified address. And often do not want to install additional software (like mycli) on this kind of host :)

**Comment by gled-rs** [comment]
reported as working correctly patching mycli/sqlexecute.py

Thanks @grooverdan

**Comment by gawel** [comment]
I've made a script as a workaround. Open a tunnel, read ~/.my.cnf on the remote host and connect using those infos: https://gist.github.com/gawel/190efd5b2109e4872407

**Comment by gled-rs** [comment]
@gawel You just need to monkey patch mycli/sqlexecute with @grooverdan pseudocode to solve that. The necessary changes in PyMysql and Paramiko are deployed.

No need for a wrapper ;)

**Comment by amjith** [comment]
You guys are welcome to send me a PR instead of monkey patching it. :smile: 

After all this is an open source project.

**Comment by gled-rs** [comment]
Will do once I get it cleaned, so much hardcoded stuff for now that I would be ashamed to produce a PR ;)

**Comment by seschwar** [comment]
@gled-rs: How's progress on the clean up? I'd love to see this feature included.

**Comment by nick-hahner** [comment]
Any progress updates? For now I'm just using an autossh tunnel in a screen session. Not as pretty, but it works.

**Comment by meeuw** [comment]
I don't know if it's useful for you but I've created a wrapper for mycli which support bash completion and ssh tunnels. https://github.com/meeuw/wrapc

**Comment by tsroten** [comment]
This feature is now out in version 1.18.0. You can get the newest version via `pip` or [check out the release](https://pypi.org/project/mycli/#files).
