### ISSUE TITLE
Click detected the use of the unicode_literals future import. This is heavily discouraged because it can introduce subtle bugs in your code.

### ISSUE THREAD

**Issue by Petrox** [dbcli/mycli#189]
Ubuntu 14.04 (latest cloud vagrantbox + distupgrade)

Installed mycli from apt repository (https://packagecloud.io/)

$ mycli
/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/main.py:565: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.argument('database', default='', nargs=1)
(2003, "Can't connect to MySQL server on u'localhost' ([Errno 2] No such file or directory)")
vagrant@vagrant-ubuntu-trusty-64:~$ python --version
Python 2.7.6

$ mycli --version
/usr/share/python/mycli/local/lib/python2.7/site-packages/mycli/main.py:565: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.argument('database', default='', nargs=1)
Version: 1.4.0

vagrant@vagrant-ubuntu-trusty-64:~$ env |grep UTF
LC_PAPER=hu_HU.UTF-8
LC_ADDRESS=hu_HU.UTF-8
LC_MONETARY=hu_HU.UTF-8
LC_NUMERIC=hu_HU.UTF-8
LC_ALL=en_US.UTF-8
LC_TELEPHONE=hu_HU.UTF-8
LC_IDENTIFICATION=hu_HU.UTF-8
LANG=en_US.UTF-8
LC_MEASUREMENT=hu_HU.UTF-8
LC_TIME=hu_HU.UTF-8
LC_NAME=hu_HU.UTF-8

**Comment by amjith** [comment]
@Petrox We've fixed this in the master and we're getting ready to release the new version. It will be fixed soon.

**Comment by Petrox** [comment]
Thank you @amjith. I suspected, that you've seen this already, I just didn't find open issues on the topic. :)
