### ISSUE TITLE
Boring Connection reset.

### ISSUE THREAD

**Issue by JayMiao** [dbcli/mycli#202]
Again, me     :)

vipcenter> select \* from member;
Connection reset. Reconnect (Y/n): Y
Reconnected!
Try the command again.

Why my connection is always be reset, should I change some mysql setting?

**Comment by amjith** [comment]
We currently use a timeout of 1024 seconds. It is the standard timeout used for interactive sessions. 

Can you tell me how long does the REPL sit idle before you reach this timeout?

**Comment by JayMiao** [comment]
It depends, but I'm sure it is less than 1024. 

I was thinking if the mycli get the colum name or table name using background quick searching to the MySQL. Then the connection will be reset ? Just an assumption. 



—

**Comment by amjith** [comment]
I don't fully understand your question but if you're asking whether mycli gets the column name or table names in a background thread, then the answer is it depends on your mycli version. Starting from mycli version 1.5.0 and above they are fetched in a background thread. But before that it was done synchronously in the foreground. 

So if you're using an older version, my recommendation is to upgrade to 1.5.0 or above.

**Comment by JayMiao** [comment]
When I update to 1.5.0. It seems not improve.
Connection reset. Reconnect (Y/n): Y
Reconnected!
Try the command again.

Is there a setting that the mycli can auto-reconnect when connection broken?

**Comment by blackakula** [comment]
+1
I'm ok with reconnect confirmation. But is it possible to make automatic re-query last command? Native mysql cmd client does this way. Maybe it's possible to add one more config setting to re-query last command on reconnect? It's really boring to recall last command once again.
And it would be also helpful to setup confirmations in different cases with the config settings.

**Comment by amjith** [comment]
@blackakula Can you tell me how often this happens? I'm surprised that I haven't run into this myself. 

The reason for asking you to manually rerun the last command is a safety feature. I'm reluctant to override that with a config value. But if it happens often enough I'll definitely consider it. 

What other cases do you want confirmation? Can you please elaborate?

**Comment by blackakula** [comment]
Hi @amjith

> how often this happens?

Usually at the beginning of each day (I left my computer on when leaving office). And sometimes during the day. But I never noticed if it less or not than 1024 seconds. On native mysql cli it was not disturbing me, because mysql native client automatically re-connect and repeat the last query without any confirmation.

> What other cases do you want confirmation? Can you please elaborate?

mycli also require confirmation on drop tables, columns. I appreciate such confirmations, but it would be better to have it configurable (at least to achieve the same behavior as a native mysql cli client).

**Comment by amjith** [comment]
> mycli also require confirmation on drop tables, columns. I appreciate such confirmations, but it would be better to have it configurable (at least to achieve the same behavior as a native mysql cli client).

This is configurable. You can open up the config file located at `~/.myclirc` and set 

```
destructive_warning = False
```

**Comment by amjith** [comment]
I'll consider adding a config value to reconnect automatically.

**Comment by JayMiao** [comment]
Yep, the perfect mycli is just let me run the query I input and put the reconnect things background.
Possible When I turn on the auto-reconnect setting, every time execute SQL check the connection and if it's broken just connect background and run my SQL immediately. 

 "destructive_warning"  is necessary !!!

**Comment by diversario** [comment]
Yep, I'm so tired of the "Connection reset" message. It's happening almost every single time I get back to the CLI. I would really, really love some setting that makes it never show again and just do the reconnect for me and run my query.

**Comment by diversario** [comment]
To illustrate, this is what I see **a lot**:

```
mariadb db> delete from foo;
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
Connection reset. Reconnect (Y/n): y
Reconnected!
Try the command again.
mariadb db> delete from foo;
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
Query OK, 1 row affected
Time: 0.247s
mariadb db>
```

6 keyboard strokes to execute what should've taken 2.

**Comment by amjith** [comment]
That is definitely annoying. I'll see if I can fix that. 

BTW, you can turn off the warning on destructive commands via the config file (~/.myclirc). 

https://github.com/dbcli/mycli/blob/master/mycli/myclirc#L17

**Comment by diversario** [comment]
Yeah, I know. I'm ok with the warning, though, no harm is being extra-cautious with the db.
