### ISSUE TITLE
Favorite Queries do not accept \G statement terminator

### ISSUE THREAD

**Issue by michaelstack** [dbcli/mycli#203]
I have some queries that use the \G terminator for vertical output. When I try to save one to Favorite Queries I get an error:

```sql
mysql root@localhost:mydb> \f acc select created from account where id = 1 \G
(1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\f acc select created from account where id = 1' at line 1")
```

If I replace the \G with a semicolon it saves fine, but the query has output that is more readable in vertical mode.

**Comment by spacewander** [comment]
To save a favorite query, you need to use `\fs`

And a comon is required since mycli don't add it for you currently.

> \\fs simple select * from abc where a is not Null;

**Comment by amjith** [comment]
@michaelstack  You're right there is a bug that doesn't allow you to save favorite queries with `\G` in them. I'll see if I can fix them soon.

**Comment by michaelstack** [comment]
@spacewander It looks like I copied in the wrong command. Thanks for pointing that out. 

I should have used this one:

```sql
mysql root@localhost:mydb> \fs acc select created from account where id = 1 \G
(1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\fs acc select created from account where id = 1' at line 1")
```
