### ISSUE TITLE
prompt_toolkit>=0.46

### ISSUE THREAD

**Issue by jukebox** [dbcli/mycli#204]
possible to change setup.py ?

**Comment by mdsrosa** [comment]
@jukebox Could you please elaborate more your request? Why do we need to accept versions greater than `v0.46`? Is there a feature in the latest version that needs to be taken advantage of on mycli? Because we need to run some tests before doing any change.

**Comment by loonies** [comment]
The latest _prompt_toolkit_ `0.54` breaks _mycli_. It works with `0.46`.

**Comment by amjith** [comment]
That exactly why we didn't specify `prompt_toolkit>=0.46`. Prompt Toolkit is an evolving library and the API changes between releases (for a good reason). So it takes a little bit of work to upgrade to the latest.
