### ISSUE TITLE
Very wide data is out of screen.

### ISSUE THREAD

**Issue by smcdl** [dbcli/mycli#215]
As it said in title, how to fix this problem, THKS!

**Comment by tsroten** [comment]
@smcdl - You might try putting [`\G` at the end of your query](http://dev.mysql.com/doc/refman/5.7/en/mysql-tips.html#vertical-query-results). For example:

```mysql
SELECT id, name from users where date_created > '2015-01-01' \G
```

Soon, mycli will also support automatic vertical output: https://github.com/dbcli/mycli/pull/205.

**Comment by amjith** [comment]
@smcdl You can use the left/right arrow to scroll horizontally.

If you're not a fan of the horizontal scrolling, then there is one other option. Press Shift-S when the output is shown in the pager. This will switch off the horizontal scrolling in the pager.

**Comment by tsroten** [comment]
@smcdl Did that answer your question?

**Comment by tsroten** [comment]
@smcdl I'm going to close this. If you need something else, feel free to post again!

**Comment by iamsebastian** [comment]
Is that *scrolling* with the arrow-keys implemented by yourself or is it implemented by `less`? Never tried this out before, because man-pages and most-output are fits within the screen.

**Comment by tsroten** [comment]
@iamsebastian I believe all the keybindings for the pager are implemented by the pager itself. `less` is the default pager for *nix distributions per the `click` library that mycli uses to print output via a pager. It respects the `PAGER` environment variable as well.

**Comment by iamsebastian** [comment]
Yes, ok. Never knewn before. Just used `less` for years in vertical scrolling only. Thanks, @tsroten
