### ISSUE TITLE
Disable pager

### ISSUE THREAD

**Issue by diversario** [dbcli/mycli#218]
It seems like mycli switches from dumping output on the screen to showing it in a pager depending on how many results are there (?). I almost never want the pager – is there a way to force output to never use it?

**Comment by diversario** [comment]
Oh, and also – when the pager is used it destroys whatever there was on the screen before it.

**Comment by tsroten** [comment]
@diversario You're right, it would be nice to have a way of turning the pager off, similar to the official mysql client. I've implemented this and am testing it now.

Regarding the pager destroying what's on the screen. That's annoying to me as well! I'm not sure what the solution to that is, but we can certainly look at it and see what's possible.

**Comment by tsroten** [comment]
@diversario #237 should address the pager destroying what's on screen.

**Comment by diversario** [comment]
Great! Is the version with this change available in `brew`?

**Comment by tsroten** [comment]
@diversario I don't believe so.

@amjith Any idea when the next release will be published?

**Comment by amjith** [comment]
I'd like to upgrade prompt_toolkit to 0.60 and then do a release. 

Hopefully later today.

**Comment by amjith** [comment]
Released as part of 1.6.0. Please upgrade: 

```
pip install -U mycli 
```

Version is not yet available in brew, but a PR has been made and pending approval from brew maintainers. https://github.com/Homebrew/homebrew/pull/50388
