### ISSUE TITLE
Support for storing multiple database credentials

### ISSUE THREAD

**Issue by shanemhansen** [dbcli/mycli#22]
I've always hated the fact that mysql doesn't support the [.pgpass format](http://www.postgresql.org/docs/9.3/static/libpq-pgpass.html)

It looks like mysql has a kind of similar feature that can be activated using a [command line flag](http://dba.stackexchange.com/questions/3889/is-it-possible-to-have-passwords-configured-per-database-or-per-host-in-my-cnf) but that's kind of lame. Someday (not soon) it would be super awesome to have support for a .myclipass file that looked like .pgpass.

**Comment by amjith** [comment]
This request is address by this issue https://github.com/dbcli/mycli/issues/95

In ~/.my.cnf you can list multiple sections with different databases and credentials. 

eg:
```
[clientServerName]
user=root
password=MySuperSecurePassword
host=remote.server.com
database=example
[clientAnotherServer]
user=amjith
password=MyAwesomePassword
host=remote.server.net
database=example123
```

Then you can launch mycli with the following option: 

```
$ mysql --defaults-group-suffix=AnotherServer
```

This will launch mycli and use the credentials from the section called `clientAnotherServer`. 

This is available in the latest version of mycli (1.3.0 and above).
