### ISSUE TITLE
[question] How do I enable local-infile?

### ISSUE THREAD

**Issue by daj0ker** [dbcli/mycli#221]
As said in the title, I've edited my.cnf to enable local-infile.

After that, <code>$mysql -u username -p --local-infile</code> does the job.

How do I configure mycli to do this?

**Comment by tsroten** [comment]
@daj0ker We don't currently support the `--local-infile` flag.

It shouldn't be too hard to add, though. mycli uses PyMySQL which simply looks for a boolean argument `local_infile`.

**Comment by tsroten** [comment]
@daj0ker Some initial tests look promising for this. I'll go ahead and submit a pull request for this.

**Comment by amjith** [comment]
Released as part of 1.6.0. Please upgrade: 

```
pip install -U mycli 
```
