### ISSUE TITLE
brew install mycli -- error 

### ISSUE THREAD

**Issue by mikeerickson** [dbcli/mycli#222]
I have performed brew update (twice) and brew doctor but this issue continues to appear

Note: I am installing on linux (hosted on Vagrant)

Last 15 lines from /home/vagrant/.cache/Homebrew/Logs/mycli/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/home/vagrant/.linuxbrew/Cellar/mycli/1.5.2/libexec/vendor
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

**Comment by mkody** [comment]
`brew` on linux? Did I miss something?

You simply need to install or update setuptools on python. 
To install setuptools on Debian, Ubuntu, Mint or derivated:
`$ sudo apt-get install python-setuptools`
`$ sudo apt-get install python3-setuptools`
And if for some reason it doesn't work on Red Hat-based distributions:
`$ sudo yum python-setuptools`
If you don't have an apt or yum package manager, you could finally use `pip`:
`$ pip install -U setuptools`

**Comment by amjith** [comment]
@mikeerickson Were you able to get past the issue, using the instructions from @mkody?

**Comment by tsroten** [comment]
@mikeerickson I hope you were able to install mycli. I'm going to close this issue for now. If you have any other questions, feel free to post them.
