### ISSUE TITLE
source functionality doesn't work

### ISSUE THREAD

**Issue by faizalpribadi** [dbcli/mycli#231]
i'm not sure for this, why source command for import sql file not work ?

**Comment by amjith** [comment]
It is not yet implemented in mycli. We'll add it to our list of things to do. Thanks for the report.

**Comment by tsroten** [comment]
@amjith Didn't you implement this [back in August](https://github.com/dbcli/mycli/commit/c4ea29a18bb25705a525607ff221e510ea0fb526)?

**Comment by amjith** [comment]
You're correct. :) 

Time to close this issue.
