### ISSUE TITLE
Syntax highlighting and smart completion support for OFFSET

### ISSUE THREAD

**Issue by Niels-NTG** [dbcli/mycli#234]
A very small issue, but I've noticed that mycli doesn't highlight or auto suggests the keyword `OFFSET`, commonly used to find the "nth" result of a query. For example:
```
SELECT * FROM users ORDER BY id DESC LIMIT 1 OFFSET 10
```
…selects the row 10 rows below the result of the query.

**Comment by amjith** [comment]
This is now fixed in master. It will be released in the next version. 

In the meantime if you'd like to start using it right away, you can install directly from master using the following command: 

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

**Comment by Niels-NTG** [comment]
Great! And just a general thank you; mycli has proven to be a great tool to learn SQL queries for me.
