### ISSUE TITLE
how can i start if i want to contributing

### ISSUE THREAD

**Issue by dhlwing** [dbcli/mycli#240]
I'm already clone the code to my computer, but i got this error when i run this code:

```bash
cd mycli/
python main.py 
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    from .packages.tabulate import tabulate, table_formats
ValueError: Attempted relative import in non-package
```

how can i start if i want to contributing

**Comment by j-bennet** [comment]
Hi @dhlwing, thanks for your interest in being a contributor! We have a step-by-step guide here: https://github.com/dbcli/mycli/blob/master/DEVELOP.rst

In two words, you do not run `python main.py`, you install `mycli` into a virtual environment and run `mycli`.

Good luck!

**Comment by dhlwing** [comment]
understanding
