### ISSUE TITLE
Read Line "Search for command in the history" support

### ISSUE THREAD

**Issue by meeuw** [dbcli/mycli#247]
Would it be possible to implement "Search for command in the history" like read line (and ie. bash):
https://www.gnu.org/software/bash/manual/bashref.html#Searching

The stock mysql command line clients supports this and it's quite handy to repeat and alter commands from your history.

C-R is the default emacs keybinding, bash also has a vi mode which can also search using the / command (set -o vi ; [escape]/test[enter]).

**Comment by mdsrosa** [comment]
@meeuw Hello! and thank you for using mycli. 

The feature that you're requesting I think is already available. You can search for previous queries using `Ctrl+R` and down to the status bar will show up a `I-search/I-search backward: ` input field for you to start typing. If that does not behave like you expected, let us know. :-)

**Comment by meeuw** [comment]
Great! I was using mycli packaged by Fedora but it Ctrl+R didn't work (1.5.2-4.fc23) but mycli installed by using pip works!

Do you know what is missing in the Fedora version so I can file / search for a issue in their bugzilla?

**Comment by mdsrosa** [comment]
@meeuw Oh, that's good to know!

But I'm sorry, unfortunately I don't know what is missing in the Fedora version. But maybe Amjith can help you out. Any thoughts on this, @amjith? :-)

**Comment by amjith** [comment]
I wonder what version of mycli was being packaged by Fedora, but this feature has been available for a very long time. Unfortunately I didn't package it for Fedora and some volunteer packaged it. Sorry I don't have more info to provide.

**Comment by meeuw** [comment]
The spec file for Fedora can be found at:
http://pkgs.fedoraproject.org/cgit/rpms/mycli.git/tree/

I've tested the master branch from this git repository and is has the same error as the Fedora packaged version; When I'm using tag v1.5.2 searching in the history works fine.

I've used git bisect to find the troubling commit and it seems this one:
9c0b65ebb9d8b423c7e7701116dc20bda206296a is the first bad commit
commit 9c0b65ebb9d8b423c7e7701116dc20bda206296a
Author: Lennart Weller <lhw@ring0.de>
Date:   Fri Nov 27 14:19:17 2015 +0100

    Respect the new default actions in prompt_toolkit which were added in 0.51

:040000 040000 596396aa10de3a053944dd82bdd4926641b49de8 e511d69132d96901964cf845c9a69b7da43c71ab M	mycli
:100644 100644 e503e2c4d1b395bfb3629e0a55a4525c5ca7164b ac9717e82dfd02e63ba9ba9fa8c63c573aae4bb7 M	setup.py

Maybe @lhw can have look?

**Comment by amjith** [comment]
@meeuw You're right. I can't believe it's broken in master. Thanks a lot for running through bisect to pin point the issue. I'll dig into it once I get back from work. 

Thank you!

**Comment by tsroten** [comment]
Closing since it looks like Fedora is using version 1.7.0 now, which has the fix for this issue.
