### ISSUE TITLE
edit cmdline in vim mode

### ISSUE THREAD

**Issue by jinleileiking** [dbcli/mycli#252]
Can I edit cmdline in vim mode?

eg dw = delete a word. etc.

**Comment by amjith** [comment]
Yes. You can toggle the vim mode temporarily by pressing F4. It will enable vim mode and then you can type `Esc` to go to the normal mode and use the `dw` etc. 

If you want to enable it permanently you can set it up in the config file. ~/.myclirc

**Comment by jinleileiking** [comment]
@amjith Can I use `/` to search ? It seems can not.

**Comment by amjith** [comment]
@jinleileiking It does work but it only searches for the search term in the current query, not the whole page.

**Comment by ReneFroger** [comment]
I use gnome-terminal. 

Vi mode is enabled. I see it also in the mode line: [F4] Vi-mode.

When I press <kbd>escape</kbd>, I'm still in INSERT mode and can't get into normal mode. Any suggestions? I have also tried other terminals.

I use Xubuntu 16.04 by the way.

**Comment by amjith** [comment]
@ReneFroger Can you see if you can press Ctrl-[ to simulate the Esc key?

**Comment by ReneFroger** [comment]
Yes, <kbd>Ctrl-[</kbd> is working. Strangely this is not the case for the <kbd>Esc</kbd> key.

Any way to remap these keys in `.myclirc`?

**Comment by ReneFroger** [comment]
Any suggestion?

**Comment by amjith** [comment]
I don't have any thoughts off the top of my head. I strongly suspect it has
to do with gnome terminal settings.

I'm unable to dig in at the moment. (Dealing with a newborn).

One alternative is to try this on ptpython and if the problem persists then
it has to do with prompt-toolkit.

**Comment by ReneFroger** [comment]
Congratulations with your newborn!  :smiley: !

Where are the keybindings of mycli REPL located? Then I will trying to figure out how to modify them.

**Comment by amjith** [comment]
https://github.com/dbcli/mycli/blob/master/mycli/key_bindings.py

But some of the basic bindings for the Emacs and Vi mode are coming
directly from prompt-toolkit.

**Comment by tsroten** [comment]
Closing as this seemed more terminal-related than Prompt Toolkit-related. Feel free to open again if this issue presents itself.
