### ISSUE TITLE
error while executing command "sudo pip install mycli"

### ISSUE THREAD

**Issue by binarywang** [dbcli/mycli#254]
......  
  src/hash_template.c:339: error: for each function it appears in.)
    src/hash_template.c:339: error: ‘m’ undeclared (first use in this function)
    src/hash_template.c:351: error: ‘ALGtype’ undeclared (first use in this function)
    src/hash_template.c:351: error: ‘PyType_Type’ undeclared (first use in this function)
    src/hash_template.c:352: warning: implicit declaration of function ‘Py_InitModule’
    src/hash_template.c:356: error: ‘o’ undeclared (first use in this function)
    src/hash_template.c:356: warning: implicit declaration of function ‘PyInt_FromLong’
    src/hash_template.c:356: warning: implicit declaration of function ‘PyDict_SetItemString’
    src/hash_template.c:356: warning: implicit declaration of function ‘PyModule_GetDict’
    src/hash_template.c:356: warning: implicit declaration of function ‘Py_DECREF’
    src/hash_template.c:360: warning: implicit declaration of function ‘PyErr_Occurred’
    src/hash_template.c:361: warning: implicit declaration of function ‘Py_FatalError’
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BOG7nI/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Y5e6K0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-BOG7nI/pycrypto/

I don't understand python, can someone help me to fix it? 
Thanks very much.

**Comment by binarywang** [comment]
And when I use "sudo easy_install mycli", the message seems to be same:

Searching for mycli
Best match: mycli 1.6.0
Processing mycli-1.6.0-py2.6.egg
mycli 1.6.0 is already the active version in easy-install.pth
Installing mycli script to /usr/bin

Using /usr/lib/python2.6/site-packages/mycli-1.6.0-py2.6.egg
Processing dependencies for mycli
Searching for pycrypto>=2.6.1
Reading http://pypi.python.org/simple/pycrypto/
Best match: pycrypto 2.6.1
Downloading https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf5161a0d5d7eda
Processing pycrypto-2.6.1.tar.gz
Running pycrypto-2.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1HWb0m/pycrypto-2.6.1/egg-dist-tmp-L5n60W
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
src/MD2.c:31:20: error: Python.h: No such file or directory
src/MD2.c:131: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
In file included from src/MD2.c:147:
src/hash_template.c:48: error: expected specifier-qualifier-list before ‘PyObject_HEAD’
src/hash_template.c:59: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘PyTypeObject’
src/hash_template.c: In function ‘newALGobject’:
src/hash_template.c:69: warning: implicit declaration of function ‘PyObject_New’
src/hash_template.c:69: error: expected expression before ‘ALGobject’
src/hash_template.c: At top level:
src/hash_template.c:76: error: expected ‘)’ before ‘*’ token
src/hash_template.c:91: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
src/hash_template.c:110: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
src/hash_template.c:122: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
src/hash_template.c:162: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
src/hash_template.c:188: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
src/hash_template.c:190: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘ALG_methods’
src/hash_template.c:199: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
src/hash_template.c:225: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘ALGtype’
src/hash_template.c:271: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
src/hash_template.c:304: error: array type has incomplete element type
src/hash_template.c:305: error: ‘PyCFunction’ undeclared here (not in a function)
src/hash_template.c:305: error: expected ‘}’ before ‘ALG_new’
src/hash_template.c: In function ‘init_MD2’:
src/hash_template.c:339: error: ‘PyObject’ undeclared (first use in this function)
src/hash_template.c:339: error: (Each undeclared identifier is reported only once
src/hash_template.c:339: error: for each function it appears in.)
src/hash_template.c:339: error: ‘m’ undeclared (first use in this function)
src/hash_template.c:351: error: ‘ALGtype’ undeclared (first use in this function)
src/hash_template.c:351: error: ‘PyType_Type’ undeclared (first use in this function)
src/hash_template.c:352: warning: implicit declaration of function ‘Py_InitModule’
src/hash_template.c:356: error: ‘o’ undeclared (first use in this function)
src/hash_template.c:356: warning: implicit declaration of function ‘PyInt_FromLong’
src/hash_template.c:356: warning: implicit declaration of function ‘PyDict_SetItemString’
src/hash_template.c:356: warning: implicit declaration of function ‘PyModule_GetDict’
src/hash_template.c:356: warning: implicit declaration of function ‘Py_DECREF’
src/hash_template.c:360: warning: implicit declaration of function ‘PyErr_Occurred’
src/hash_template.c:361: warning: implicit declaration of function ‘Py_FatalError’
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by amjith** [comment]
Looks like python dev package is not installed on the system. 

You can install the python dev package in Redhat/Centos/Fedora using:

```
sudo yum install python-devel
```

Or if you're using ubuntu you can install it via apt-get as follows:

```
sudo apt-get install python-dev
```

**Comment by binarywang** [comment]
@amjith It works, thanks a lot.

**Comment by pichardoJ** [comment]
I have a similar issue, but I already have `python-devel`

```
Collecting mycli
  Using cached mycli-1.8.1-py2.py3-none-any.whl
Requirement already satisfied: sqlparse<0.2.2,>=0.2.0 in /usr/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: click>=4.1 in /usr/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: prompt-toolkit<1.1.0,>=1.0.0 in /usr/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: PyMySQL>=0.6.2 in /usr/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: Pygments>=2.0 in /usr/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python2.7/site-packages (from mycli)
Collecting pycrypto>=2.6.1 (from mycli)
  Using cached pycrypto-2.6.1.tar.gz
Requirement already satisfied: wcwidth in /usr/lib/python2.7/site-packages (from prompt-toolkit<1.1.0,>=1.0.0->mycli)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python2.7/site-packages (from prompt-toolkit<1.1.0,>=1.0.0->mycli)
Installing collected packages: pycrypto, mycli
  Running setup.py install for pycrypto ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-DjCsyD/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-T5FVVi-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/Crypto
    copying lib/Crypto/pct_warnings.py -> build/lib.linux-x86_64-2.7/Crypto
    copying lib/Crypto/__init__.py -> build/lib.linux-x86_64-2.7/Crypto
    ...
    configure: creating ./config.status
    config.status: creating src/config.h
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
    building 'Crypto.Hash._MD2' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-DjCsyD/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-T5FVVi-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-DjCsyD/pycrypto
```
