### ISSUE TITLE
auto-vertical-output option in config file

### ISSUE THREAD

**Issue by sauloperez** [dbcli/mycli#255]
I just found the `auto_vertical_output` in the readme and it's something that it's going to be very useful for me. What I was wondering is if it's possible to add that option into my `~/.myclirc` or it's only a cli argument. According to my quick search on the codebase, looks like the latter.

**Comment by amjith** [comment]
Right now this option is not available via the config file. But it should be easy to add.

**Comment by sauloperez** [comment]
Cool! I'll try to take a look over the next few days

**Comment by mdsrosa** [comment]
Working on it.

**Comment by johnksterling** [comment]
This works for me.  Can this issue be closed?

**Comment by j-bennet** [comment]
Yes, when mycli is released with the change.

**Comment by tsroten** [comment]
@sauloperez 

mycli version 1.9.0 is now out which has this change in it. You can install/upgrade by running `pip install --upgrade mycli`

Let us know if you run into any other issues, thanks!
