### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by adamchainz** [dbcli/mycli#262]
I can't seem to spot a changelog for mycli on the repo or the docs page. I am upgrading from 1.5.2 to 1.6.0 and can't tell what changed! 🎅

**Comment by mdsrosa** [comment]
You can find what's new in 1.6.0 here: https://github.com/dbcli/mycli/blob/master/changelog.md

I'll try to make this more visible in the repo's main page.

**Comment by adamchainz** [comment]
Ah sorry, I'm too used to looking for CHANGELOG or HISTORY or NEWS or CHANGES, my eyes just skimmed over the lowercase names

Pushing it into your PyPI description is imo ideal since half the people visiting the PyPI change care about it
