### ISSUE TITLE
Please upgrade to prompt_toolkit 1.0.0

### ISSUE THREAD

**Issue by Fale** [dbcli/mycli#263]
As title

**Comment by matheus-iclinic** [comment]
@Fale There is already a pull request (https://github.com/dbcli/mycli/pull/261) that will do exactly that. ;-)

**Comment by mdsrosa** [comment]
@Fale There is already a pull request (#261) that will do exactly that. ;-)

**Comment by Fale** [comment]
Thanks :). Sorry, for some reasons I did not noticed it when I opened this bug
