### ISSUE TITLE
Issues with latest 1.7.0 on PyPI

### ISSUE THREAD

**Issue by aabmass** [dbcli/mycli#266]
Just wanted to point out, It looks there is an issue with how `1.7.0` got uploaded to PyPI.

- `pip search mycli` outputs the wrong latest version as `1.5.2` still:
```
mycli (1.5.2)                - CLI for MySQL Database. With auto-completion and
                               syntax highlighting.
  INSTALLED: 1.7.0
  LATEST:    1.5.2
```
- searching directly on the PyPI website gives a similar [result](https://pypi.python.org/pypi?%3Aaction=search&term=mycli&submit=search), showing only much older versions.
- The tarball can't be downloaded off of PyPI by the usual scheme `https://pypi.python.org/packages/source/m/mycli/mycli-${pkgver}.tar.gz`. Looks like this works up to [`1.6.0`](https://pypi.python.org/packages/source/m/mycli/mycli-1.6.0.tar.gz) but 404's on [`1.7.0`](https://pypi.python.org/packages/source/m/mycli/mycli-1.7.0.tar.gz). I was using this feature for the Arch Linux package of this tool.

**Comment by amjith** [comment]
@aabmass In my investigation of this issue I accidentally deleted the mycli-1.7.0.tar.gz file and now PyPI won't let me upload it again. 😞 

So I've cut a new patch release mycli-1.7.1.tar.gz. It has no additional changes, just the version number has been bumped.

I haven't changed anything with the way I upload files to PyPI. I wonder if the infrastructure for PyPI has changed. 

FYI @dbcli/mycli-core. I had to cut a new patch release (1.7.1) since I managed to screw up 1.7.0 on PyPI. Sorry.

**Comment by aabmass** [comment]
Thanks for getting back to me @amjith! I'm not sure if it solved all of those problems, `pip search mycli` still gives me
```
mycli (1.5.2)                - CLI for MySQL Database. With auto-completion and
                               syntax highlighting.
  INSTALLED: 1.7.0
  LATEST:    1.5.2
```

Also, check out how the url works for `1.5.2`:
- https://pypi.python.org/packages/source/m/mycli/mycli-1.5.2.tar.gz vs.
- https://pypi.python.org/packages/source/m/mycli/mycli-1.7.1.tar.gz

On the up side, it looks like `pip install` does get the right version &mdash; in a clean venv, I got `mycli==1.7.1`

**Comment by amjith** [comment]
I suspect this is a PyPI anomaly. I believe that they changed the way the tarballs are stored in the backend which probably messed up the urls. 

I noticed that `pip install mycli` gets the right version but the url to the mycli tarball has a guid in the path.

**Comment by aabmass** [comment]
Ah, understood. I'll just hard code it for now. Thanks you!
