### ISSUE TITLE
How can i use ssh Tunnel?

### ISSUE THREAD

**Issue by huihuidaxia** [dbcli/mycli#269]
RT?

**Comment by j-bennet** [comment]
Something like to set up the tunnel:

```
ssh -Nf <ssh-user>@<ssh-host> -L 3306:<remote-mysql-host>:3306
```

Then connect to mysql as if it was running on localhost:

```
mycli -h localhost -P 3306
```

It's not specific to `mycli`, you'd use the same with `mysql`.

**Comment by johnksterling** [comment]
I think this issue can be closed.

**Comment by andrewimeson** [comment]
Support was also added in #634
