### ISSUE TITLE
display login-path within prompt

### ISSUE THREAD

**Issue by jmjpro** [dbcli/mycli#271]
I saved a DB connection to mysql config like this:

`mysql_config_editor set --login-path=qa --host=qa.domain.com --user=mysql_user --password`

Now I connect using mycli like this:

`mycli --login-path qa`

Can I configure mycli to use the login-path `qa` in the prompt? The issue is that the hostnames for AWS are really long.

**Comment by amjith** [comment]
Can you elaborate a little bit about the request? When you say "use `qa` in the prompt", do you mean show `user@qa:dbname>` or something else? 

Also the title of the issue said something about using a nickname in the config file. I don't understand that request.

**Comment by jmjpro** [comment]
@amjith, I changed the issue title. You're right, I like to display `user@qa:dbname`

**Comment by amjith** [comment]
This might not happen right away, but I'll keep this in the back log to implement. Thanks!

**Comment by johnksterling** [comment]
Hi - this feature has been merged and works great for me with the PR from j-bennet.  You can probably close this issue.

**Comment by j-bennet** [comment]
Yes, this is available since 1.8.0. Closing.
