### ISSUE TITLE
what is the FREEZE keyword?

### ISSUE THREAD

**Issue by schmeic** [dbcli/mycli#274]
When I type "SELECT * F" the auto complete choices are "FREEZE" and "FROM".

What is FREEZE?  As far as I can tell, it's not a mysql keyword:
https://dev.mysql.com/doc/refman/5.7/en/keywords.html

**Comment by amjith** [comment]
That was a mistake. It was ported from pgcli. You're welcome to submit a PR to remove it from the list. Here's the file that has the list of keywords: https://github.com/dbcli/mycli/blob/master/mycli/sqlcompleter.py#L29

**Comment by amjith** [comment]
This is now fixed in version 1.8.0. Please upgrade mycli: 

```
pip install -U mycli
```
