### ISSUE TITLE
Weird history bug

### ISSUE THREAD

**Issue by grafa** [dbcli/mycli#282]
Hi there,

when I submit an SQL it I get the results but the SQL doesn't dismiss from the "input line". Also, when I do search in history (arrow up), I get random SQL from my history, but def not the last ones.

Whole mycli was working right for like a month but then this starts happening.

```
grafa@tp ~> mysql --version
mysql  Ver 14.14 Distrib 5.6.30, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

**Comment by amjith** [comment]
What version of mycli are you using? 

This is the first time I've heard this complaint. 

The history file is stored in the home folder ~/.mycli-history, you can check the entries in there yourself and check if you're getting the right results when you press up-arrow.

**Comment by grafa** [comment]
```
grafa@tp ~> mycli -v
Version: 1.6.0
```

I guess the thing is when I enter and submit a SQL it just do not clean itself up from the prompt. How I've said, the whole thing was working but then I've upgraded MySQL....

**Comment by amjith** [comment]
I'm having a hard time reproducing the issue. Can you paste a screenshot of what you're seeing? 

Upgrading MySQL won't help `mycli`. They two different softwares. 

You can also try upgrading to the latest version of mycli. `pip install -U mycli`.

**Comment by grafa** [comment]
Hi,

like a week ago version 1.7 has apeared in Debian repository. Since I do use the new version, problem is solved :)

**Comment by tsroten** [comment]
This sounds like it's resolved, so I'm going to close it :)
