### ISSUE TITLE
Ctrl-p / Ctrl-n can not move in history

### ISSUE THREAD

**Issue by georgexsh** [dbcli/mycli#283]
Ctrl-p / Ctrl-n will trigger auto-completion options rather than navigate history, which is different from other REPL with readline lib, ref:
http://tiswww.case.edu/php/chet/readline/rluserman.html#SEC15

Version: 1.7.1

**Comment by amjith** [comment]
Are you using Vi-mode for the keybindings? 

Only in Vi-mode C-P and C-N will trigger completion. In emacs mode C-P and C-N will navigate the history.

**Comment by georgexsh** [comment]
@amjith sorry, I cant reproduce this now, may used Vi-mode accidentally that time.
