### ISSUE TITLE
Auto reconnect when connection is lost

### ISSUE THREAD

**Issue by georgexsh** [dbcli/mycli#284]
Original mysql command line tool will try to reconnect automatically if connection is lost, but mycli will not.
What if offer an option to auto reconnect?

Version: 1.7.1

**Comment by jialongl** [comment]
https://github.com/jialongl/mycli/commit/05a13b7bb327c379d1c43d932ac6ed67426ba255

**Comment by diversario** [comment]
I'm on 1.8.1 and I see no auto reconnect. Is it need to be enabled somehow?

**Comment by amjith** [comment]
This feature is not yet released. If you'd like to use it (and provide some feedback) you can install it directly from master

```pip install -U https://github.com/dbcli/mycli/archive/master.zip```

**Comment by diversario** [comment]
I installed it, so far works well.

**Comment by tsroten** [comment]
@georgexsh @diversario @jialongl

mycli version 1.9.0 is now out which should fix this. You can install/upgrade by running `pip install --upgrade mycli`

Let us know if you run into any other issues, thanks!
