### ISSUE TITLE
prompt setting in .my.cnf ignored

### ISSUE THREAD

**Issue by dbolser-ebi** [dbcli/mycli#300]
I set my prompt like this:
prompt=\n\u@\h:\p (\d)\n>\_

What I really like about that is the final \n that starts my query on a new line. Otherwise a big prompt makes your SQL craped up on the right.

Can you honor the prompt setting in ~/.my.cnf?

Version: 1.5.2

**Comment by amjith** [comment]
mycli will only honor the [client] section in my.cnf. So if you have the prompt listed in the [client] section it will do the right thing.

**Comment by dbolser-ebi** [comment]
Thanks for this tip, I had my prompt settings under the [mysql] section of ~/.my.cnf. It is now being picked up (and I'm now on version 1.8.0 of mycli), however, it isn't being formatted like in the regular client. This is what I have set currently:
```
[client]
prompt=\n\D\n\u@\h:\p (\d)\n>\_
```

and it gets rendered like this in the regular client (mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1):
```
Thu Aug  4 09:01:24 2016
ensro@mysql-eg-prod-1.ebi.ac.uk:4238 (test)
> SELECT ...
```

which is great, but it looks like this in mycli (1.8.0):
```
\D
ensro@mysql-eg-prod-1.ebi.ac.uk:\p (test)
>\_SELECT ...
```
which isn't ideal!

Obviously I don't need such a fancy prompt, but I would have thought mycli just relies on whatever mysql uses, rather than trying to do something else with the prompt?


Many thanks,
Dan.

**Comment by amjith** [comment]
@dbolser-ebi mycli is a completely new client written from ground up. It does not share code with the mysql's default client. So we had to recreate the behavior of mysql wherever it made sense. But you have to remember that mysql is at least 20 years old and we started less than a year ago. So there is a long way to go. 

The difference I see between your mysql prompt and mycli's prompt is that we don't support `\D`, `\p` and `\_`. These are easy things to add support for, in fact you can add them in yourself and send us a pull request. 

Here's the code that deals with prompts: 
https://github.com/dbcli/mycli/blob/master/mycli/main.py#L688-L696

I'll be happy to provide you with any guidance you might need to add support for the missing features. 😄 

Cheers!

**Comment by dbolser-ebi** [comment]
Thanks man!

**Comment by mdsrosa** [comment]
@dbolser-ebi https://github.com/dbcli/mycli/pull/323 😉

**Comment by dbolser-ebi** [comment]
Thanks for the commit. Looking forward to this making it into a release.
