### ISSUE TITLE
Pasting multiline SQL into mycli

### ISSUE THREAD

**Issue by dbolser-ebi** [dbcli/mycli#301]
If I paste (using middle mouse button) SQL like this from emacs:

```
SELECT star
FROM blar;
```

The SQL gets re-formatted as "SELECT starFROM blar;", which fails (Unknown column 'starFROM' in 'field list').

The \n should be converted into a space unless it's within quotes, or you shouldn't try to do re-formatting on paste.

**Comment by amjith** [comment]
Can you tell me what version of mycli you are using?

I believe this is fixed in the newer versions of mycli. You can upgrade using: 

```
pip install -U mycli
```

**Comment by dbolser-ebi** [comment]
I was using 1.5.2, I'm now on 1.8.0 (thanks for fixing https://github.com/dbcli/mycli/issues/299). Now when I try to paste multiple lines, it goes wrong in a different way. After the first line is pasted, the 'chooser' pops up as if it's trying to autocomplete. When I press return to get rid of the chooser, it submits the first line and none of the following lines.

**Comment by amjith** [comment]
@dbolser-ebi I'm unable to reproduce the behavior you're seeing. Here's what I'm able to do:

![paste](https://cloud.githubusercontent.com/assets/49260/17407026/a39f536c-5a1a-11e6-9c8a-4821edd7f1c1.gif)

**Comment by dbolser-ebi** [comment]
How do you record this?​

**Comment by j-bennet** [comment]
http://www.cockos.com/licecap/

**Comment by dbolser-ebi** [comment]
I get the above problem whether or not I have Smart Completion: ON or OFF.

**Comment by dbolser-ebi** [comment]
I've installed the latest version of mycli (co-incidentally on a new OS). I've tried this on Ubuntu and RH7. In both cases the issue seems to have resolved, so you can close this ticket now.
