### ISSUE TITLE
Chinese can't display properly

### ISSUE THREAD

**Issue by lik0914** [dbcli/mycli#303]
example: show create table tableName;
`first_order` int(11) DEFAULT NULL COMMENT '<E9><A6><96><E6><AC><A1><E5><B8><A6><E7><9C><8B><E8><AE><A2><E5><8D><95>|<E6><9E><97><E8><A8><80><E8><B6><85>|2015-03-31',
How do you solve this problem?
Version: 1.7.1

**Comment by tsroten** [comment]
@lik0914 Thanks for using mycli!

In mycli, could you run `status` and tell us the different "charactersets" listed in that command? Here is a sample response:
```
+----------------------+-------------------------------+
| Connection id:       | 1471                          |
| Current database:    | test                          |
| Current user:        | root@localhost                |
| Current pager:       | System default                |
| Server version:      | 5.7.13 Homebrew               |
| Protocol version:    | 10                            |
| Connection:          | localhost via TCP/IP          |
| Server characterset: | utf8                          |
| Db characterset:     | utf8                          |
| Client characterset: | utf8                          |
| Conn. characterset:  | utf8                          |
| TCP port:            | 3306                          |
| Uptime:              | 9 days 21 hours 44 min 10 sec |
+----------------------+-------------------------------+
```

**Comment by lik0914** [comment]
mycli 1.7.1, running on CPython 2.7.5

+----------------------+-----------------------------------------+
| Connection id:       | 621223                                  |
| Current database:    |                                         |
| Current user:        | work@10.51.64.132                       |
| Current pager:       | System default                          |
| Server version:      | 5.6.24-log MySQL Community Server (GPL) |
| Protocol version:    | 10                                      |
| Connection:          | db_work via TCP/IP                      |
| Server characterset: | latin1                                  |
| Db characterset:     | latin1                                  |
| Client characterset: | utf8                                    |
| Conn. characterset:  | utf8                                    |
| TCP port:            | 3306                                    |
| Uptime:              | 15 days 23 hours 19 min 17 sec          |
+----------------------+-----------------------------------------+

**Comment by lik0914** [comment]
mycli 1.7.1, running on CPython 2.7.5

+----------------------+-----------------------------------------+
| Connection id:       | 621223                                  |
| Current database:    |                                         |
| Current user:        | work@xxx                       |
| Current pager:       | System default                          |
| Server version:      | 5.6.24-log MySQL Community Server (GPL) |
| Protocol version:    | 10                                      |
| Connection:          | db_work via TCP/IP                      |
| Server characterset: | latin1                                  |
| Db characterset:     | latin1                                  |
| Client characterset: | utf8                                    |
| Conn. characterset:  | utf8                                    |
| TCP port:            | 3306                                    |
| Uptime:              | 15 days 23 hours 19 min 17 sec          |
+----------------------+-----------------------------------------+

**Comment by tsroten** [comment]
@lik0914 It looks like your server is running in `latin1`, which won't support Chinese characters. Do you also have this problem in the official mysql client (e.g. running `mysql`)?

You might try [restarting your MySQL server](http://dev.mysql.com/doc/refman/5.7/en/charset-server.html) like this: `mysqld --character-set-server=utf8`

**Comment by lik0914** [comment]
mycli 1.7.1, running on CPython 2.7.5

+----------------------+-----------------------------------------+
| Connection id:       | 13501                                   |
| Current database:    | rrc                                     |
| Current user:        | work@xxxxx                       |
| Current pager:       | System default                          |
| Server version:      | 5.6.30-log MySQL Community Server (GPL) |
| Protocol version:    | 10                                      |
| Connection:          | db_work via TCP/IP                      |
| Server characterset: | utf8                                    |
| Db characterset:     | utf8                                    |
| Client characterset: | utf8                                    |
| Conn. characterset:  | utf8                                    |
| TCP port:            | 3306                                    |
| Uptime:              | 25 days 23 hours 47 min 49 sec          |
+----------------------+-----------------------------------------+

But, there are still the same problem

**Comment by c02y** [comment]
It seems this problem is not fixed.

`mycli 1.8.1, running on CPython 3.3.5`

It shows wrong string in the mycli if one field contains Chinese characters, and the Chinese string is totally OK in standard mysql.

**Comment by tsroten** [comment]
@c02y Thanks for pointing this out again. I'm having trouble replicating this. If you can give me some more information, it might help narrow things down.

1. From mycli, with your database that contains Chinese selected, run `status` and post the various character sets here.
2. Run `create table foo;`, where `foo` is the name of your table, and post the response.
3. From the official mysql client, with your database that contains Chinese selected, run `status` and post the various character sets here.

Thanks!

**Comment by c02y** [comment]
1. `status` in mycli:

    mycli 1.8.1, running on CPython 3.3.5
    +----------------------+-------------------------------+
    | Current pager:       | System default                |
    | Server version:      | 5.1.71 Source distribution    |
    | Protocol version:    | 10                            |
    | Connection:          | localhost via TCP/IP          |
    | Server characterset: | latin1                        |
    | Db characterset:     | latin1                        |
    | Client characterset: | utf8                          |
    | Conn. characterset:  | utf8                          |

But  `status` in standard mysql is:

    mysql  Ver 14.14 Distrib 5.1.71, for redhat-linux-gnu (i386) using readline 5.1

    Current pager:          stdout
    Server version:         5.1.71 Source distribution
    Protocol version:       10
    Connection:             Localhost via UNIX socket
    Server characterset:    latin1
    Db     characterset:    latin1
    Client characterset:    latin1
    Conn.  characterset:    latin1

Chinese in mysql is fine, but is a mess in mycli.


2. `create table Cars;` which Cars is my table name:

in mycli:

    (1050, "Table 'Cars' already exists")

in standard mysql:

    ERROR 1050 (42S01): Table 'Cars' already exists

**Comment by tsroten** [comment]
@c02y I'm sorry, I meant to say `show create table Cars;`  -- so that we can see your table's information.

**Comment by c02y** [comment]
`show create table Cars;` in mycli:

    +---------+----------------+
    | Table   | Create Table   |
    |---------+----------------|
    | Cars    | CREATE TABLE `Cars` (
      `ID` int(11) NOT NULL AUTO_INCREMENT,
      `parID` int(11) DEFAULT NULL,
      `Name` text,
      `Price` bigint(20) DEFAULT NULL,
      PRIMARY KEY (`ID`)
    ) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=latin1                |
    +---------+----------------+

`show create table Cars;` in standard mysql:

The same as mycli.

**Comment by tsroten** [comment]
@c02y What if you add this line to your `~/.my.cnf`?

```
[client]
default-character-set=latin1
```

If the `[client]` section already exists, just add the line into that section.

**Comment by c02y** [comment]
Still not working, whether I put that in ~/.my.cnf or /etc/my.cnf

**Comment by yibingyi** [comment]
In mycli, i have same situation of chinese display. 
table encode is utf8

**Comment by yibingyi** [comment]
I have the same problem，if data column has any Chinese character. I am so sad.....
a fancy tool can not run with Chinese.

**Comment by tsroten** [comment]
@yibingyi Can you please show us the output of this command in your terminal: `locale`

**Comment by yibingyi** [comment]
@tsroten thx for your reply
The output in terminal  
``` shell
LANG=en_US
LC_CTYPE=en_US
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL= 
```

**Comment by tsroten** [comment]
@yibingyi I think you're going to want to enable UTF-8 in your terminal locale settings:
```bash
$ export LC_ALL=en_US.UTF-8
$ export LANG=en_US.UTF-8
$ locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
[...]
# Now run mycli again.
$ mycli
```

If that works, you'll want to add those two export commands to your bash or zsh configuration file (e.g. `.bashrc` or `.zshrc`).

**Comment by yibingyi** [comment]
@tsroten 
It works, thank you. 👍 👍 🔢

**Comment by tsroten** [comment]
@yibingyi No problem! I hope you enjoy mycli!
