### ISSUE TITLE
It is impossible to install `mycli` and `pgcli` togther

### ISSUE THREAD

**Issue by LiraNuna** [dbcli/mycli#304]
Because `mycli` has the dependency of `sqlparse==0.1.19` but `pgcli` has the dependency of `sqlparse == 0.2.0`, it is impossible to install both at the same time without a complex venv setup.

**Comment by amjith** [comment]
Sorry about that sqlparse made a breaking change in 0.2.0 so I had to pin the version. We plan to upgrade the sqlparse version for mycli soon.

**Comment by LiraNuna** [comment]
As a (semi-)temporary solution, we built PEX archives of each.

**Comment by meeuw** [comment]
mycli now (only) supports sqlparse 0.2 so you should be able to install both at the same time!

**Comment by amjith** [comment]
@LiraNuna Try installing directly from master. It is fixed, haven't released a new version yet. 

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

**Comment by xeron** [comment]
But now `pgcli` depends on `>=0.2.2` and `mycli` is on `<0.2.2` :(

**Comment by meeuw** [comment]
I think we can change it to <=0.2.2, I'm willing to write patches if it doesn't work :-) have you tried it?

**Comment by xeron** [comment]
I didn't try mycli with sqlparse 0.2.2. My issue is that I'm maintain mycli port in macports and I can't add pgcli port because they require different versions of sqlparse.

Related pgcli PR: https://github.com/dbcli/pgcli/pull/606

**Comment by amjith** [comment]
Sorry about the trouble. 

Fixed in master. I'll let @mdsrosa do a release of a new version when he sees fit.

**Comment by tsroten** [comment]
@xeron @LiraNuna 

mycli version 1.9.0 is now out which should fix this. You can install/upgrade by running `pip install --upgrade mycli`

Let us know if you run into any other issues, thanks!
