### ISSUE TITLE
Use 16-colour terminal palette

### ISSUE THREAD

**Issue by krigstask** [dbcli/mycli#307]
*mycli* seems to use 256 (or 88?) colour palette which could be not configured properly.  For example, this is how ''mycli'' session looks now in my iTerm2 with pretty famous [dark Solarized colour scheme](http://ethanschoonover.com/solarized)
![screen shot 2016-08-10 at 16 44 25](https://cloud.githubusercontent.com/assets/419654/17555967/a969a588-5f22-11e6-8113-ccfd9bc3bb62.png)
Note practically unreadable blue table names :(

And that's how my terminal looks usually:
![screen shot 2016-08-10 at 16 46 55](https://cloud.githubusercontent.com/assets/419654/17555970/abba1f34-5f22-11e6-852d-232838c07658.png)

![screen shot 2016-08-10 at 16 52 42](https://cloud.githubusercontent.com/assets/419654/17556122/511d7dd6-5f23-11e6-9e6e-4673d0278018.png)

It'd be nice to have some option to make *mycli* use only 16 "standard" colours.

**Comment by amjith** [comment]
Sorry about that. You can always change the color scheme in your ~/.myclirc
file.

There are plenty of choices. You can see a gallery of them here:
http://mycli.net/syntax

Amjith

**Comment by krigstask** [comment]
I see, thanks for reply.
Probably I need to talk to *prompt_toolkit* developers about forcing 16 colours on apps using it.

**Comment by krigstask** [comment]
I've opened an issue: https://github.com/jonathanslenders/python-prompt-toolkit/issues/376

**Comment by krigstask** [comment]
With `prompt_toolkit>=1.0.6` it's as simple as...
```
$ PROMPT_TOOLKIT_ANSI_COLORS_ONLY="1" mycli
```
![screen shot 2016-08-16 at 11 08 56](https://cloud.githubusercontent.com/assets/5174481/17692328/46df4e5e-63aa-11e6-8654-6935c465cb44.png)
