### ISSUE TITLE
packagecloud.io apt package out of date

### ISSUE THREAD

**Issue by tommarshall** [dbcli/mycli#308]
The [Debian/Ubuntu install instructions](https://github.com/dbcli/mycli#debianubuntu-package) in the README recommend installing via `apt`, however the packagecloud.io apt package does not appear to have been updated since 1.5.2.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

$ sudo apt-get upgrade mycli
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
mycli is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ mycli --version
Version: 1.5.2
```

**Comment by amjith** [comment]
You're correct. The README is now outdated. There are now officials builds of mycli available via the regular apt repositories (thanks to @lhw) instead of using package cloud. I'll update the docs.

**Comment by tommarshall** [comment]
Thanks for the quick response on this @amjith.

It looks like the package is only available for 16.04 (xenial), not 14.04 (trusty) and 12.04 (precise). 

12.04 reaches end-of-life in the next year, but 14.04 will be supported until 2019.

What's the recommended install path for install MyCLI on 14.04? `pip`? Or is there an `apt` package for 14.04 that I'm missing?

**Comment by amjith** [comment]
@lhw Can I trouble you for making deb packages for trusty and precise?

**Comment by amjith** [comment]
@tommarshall I'd recommend installing mycli via pip until the deb packages are built for older debian versions. 

You can install pip in trusty using 

```
sudo apt-get install python-pip
```

Then it's a matter of doing 

```
sudo pip install mycli
```

I hope that helps you in the mean time.

**Comment by tommarshall** [comment]
Thanks @amjith. Happy to do that.

The reason for asking in the first place is because I maintain an [ansible role for installing mycli](https://galaxy.ansible.com/detail#/role/4640), which was still following the instructions in the README.

I'll keep an eye on this issue and update the role to install from the apt repositories if you do end up with packages for precise and trusty as well 👍

**Comment by lhw** [comment]
It's not that easy sadily. All the dependencies would have to be ported 
as well as we added most of them in the last few months so they are not 
yet ubuntu as of yet.
I could have a look but I'll be on vacation for 2 weeks starting friday 
and I might not have the time to do it until then.

Also getting new packages into ubuntu stable releases is probably a no 
go to begin with. I'd have to look through the policies but I don't 
think it will be easy. Publishing a ppa for older ubuntu versions or 
using your packagecloud.io system is probably a whole lot easier.

**Comment by uuip** [comment]
ubuntu's apt source should be updated alse.

**Comment by pasenor** [comment]
apt packages are not officially supported anymore. Please refer to https://www.mycli.net/install for up-to-date installation instructions.
