### ISSUE TITLE
Double keyword "distinct" 

### ISSUE THREAD

**Issue by uuip** [dbcli/mycli#313]
according to https://github.com/dbcli/mycli/issues/305
I have run the command: pip install -U https://github.com/dbcli/mycli/archive/master.zip
but there is also  "distinct"  after I input "select di".
![2016-09-18_140531](https://cloud.githubusercontent.com/assets/16631174/18613345/1fec8404-7dab-11e6-995f-f656bc3997f1.png)

**Comment by amjith** [comment]
You're right. I have fixed it in a PR. It will be included in the next release.

**Comment by uuip** [comment]
https://github.com/dbcli/mycli/commit/c78396dd09a3c4b759a0e26a3520a0745f3328f3

Verified ,good job.
