### ISSUE TITLE
Keyword REGEXP missed

### ISSUE THREAD

**Issue by cxbig** [dbcli/mycli#326]
When I do search, I'd like to use `REGEXP` keyword.
But we don't have it in auto-completion:
<img width="183" alt="mycli_no_regexp" src="https://cloud.githubusercontent.com/assets/1363706/20177488/62dc70b4-a74d-11e6-9d57-a296637f68e1.png">

**Comment by amjith** [comment]
That's a valid request. We'll be happy to add that to the list. If you're feeling particularly generous you're also welcome to submit a PR to add `REGEXP` to the list of keywords. 

Here's the place to add the keyword: https://github.com/dbcli/mycli/blob/master/mycli/sqlcompleter.py#L21..L38
