### ISSUE TITLE
MySQL alternative data directory conflicts with MyCLI

### ISSUE THREAD

**Issue by ReneFroger** [dbcli/mycli#329]
I wanted to move my MySQL data directory to an alternative source, so I did the following steps [described in this tutorial](https://www.digitalocean.com/community/tutorials/how-to-move-a-mysql-data-directory-to-a-new-location-on-ubuntu-16-04). 

After completing this process, I noticed the `mysql` command line interface works fine, but MyCLI ran into vaguely errors with the Python library client. 

So I'm wondering if there is some configuration where you can 'tell' MyCLI that he needs to look into other data directory?

**Comment by johnksterling** [comment]
Can you provide more information on what errors you ran into?  I'm not clear on why the backend storage would impact mycli, but I must be misreading your question.

**Comment by ReneFroger** [comment]
I cannot reproduce this again, because I installed Mysql again and skipped the tutorial as linked.

Nevertheless, thanks for your offer to help!
