### ISSUE TITLE
Does mycli support Apache Hive?

### ISSUE THREAD

**Issue by csrgxtu** [dbcli/mycli#330]
apache hive have the hive cli and beeline as the client for command line, but it is not convinient as mycli, so i am wondering is there any way that can extend the mycli to compatible with hive.

**Comment by tsroten** [comment]
@csrgxtu Hi! I'm not familiar with Hive -- is it a fork/derivative of MySQL?

How compatible is the syntax between the two?

**Comment by csrgxtu** [comment]
@tsroten hi, hive is a component in Hadoop ecosystem, it is a layer or tool that run above hadoop distributed systerm, implemented by Facebook engineers, it lets you do map reduce work in structure query language ie SQL. for example, if you want to get how many records have 'Linux' in it, you can do it in Hive like this:
```sql
select count(*) from records where content  like '%Linux%';
```
just like SQL, but based on Hadoop Distributed File system, it can process huge amount of data.

and mycli is great for MySQL, so i am wondering if it has support for Hive. or i am wondering how to implement a similar one for Hive. btw, the Hive inner command line really sucks, can't compare it with mysql-client.

**Comment by csrgxtu** [comment]
https://hive.apache.org/
https://en.wikipedia.org/wiki/Apache_Hive

plz refer the upper links for detail

**Comment by tsroten** [comment]
Thanks for the information! Hive seems a bit out of scope for mycli.

mycli focuses on MySQL and MySQL-compatible servers (e.g. MariaDB).

mycli uses [PyMySQL](https://github.com/PyMySQL/PyMySQL) behind the scenes to connect to and query MySQL databases. For Hive, it looks like you would need to use [PyHive](https://github.com/dropbox/PyHive) to do this.

As far as the UI, mycli relies on [Click](http://click.pocoo.org/5/) and [Python Prompt Toolkit](https://github.com/jonathanslenders/python-prompt-toolkit), both of which would be helpful for a Hive client.

**Comment by tsroten** [comment]
@csrgxtu Good luck with Apache Hive! I'm going to close this issue for now since it's not looking like this will be a good fit for mycli.
