### ISSUE TITLE
[bug] tmux + mycli only paste one line

### ISSUE THREAD

**Issue by jinleileiking** [dbcli/mycli#332]
When use tmux with mycli.

I copy some lines to tmux buffer by `ctrl + [`

```
CREATE TABLE `xxxxx` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `xxx` varchar(128) NOT NULL,
  `xxxxx` varchar(32) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `xxxx` (`id`) USING BTREE,
  UNIQUE KEY `xxxxx` (`unique_name`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8

```

I paste the lines use tmux paste buffer. 

mycli only paste one line

```
CREATE TABLE `xxxxx` (
 

```

**Comment by amjith** [comment]
@jinleileiking The reason why this happened is because you need to be in multi-line mode when you paste a query that has multiple lines. 

So enable multi-line mode with F3 key and then try pasting.

**Comment by jinleileiking** [comment]
Thanks 👍

**Comment by jinleileiking** [comment]
@amjith can set it to default?

**Comment by amjith** [comment]
You can set this in your config file located under `~/.myclirc` file. 

Look for a line that says `multi_line` and set that value to `true`.

**Comment by jinleileiking** [comment]
Use multiline cannot work fine in my env. I will show the details later.

**Comment by dbolser-ebi** [comment]
I'm having similar issues under screen. i.e. I can paste multiline queries /without/ Multiline OFF in my regular terminal, but not under a screen session. Also, pasting multiline queries is 'activating' the autocomplete box in both cases, which is distracting. I seem to remember seeing another issue about this, but I can't find it.

**Comment by tsroten** [comment]
@dbolser-ebi What happens when you paste under screen?

**Comment by dbolser-ebi** [comment]
Same issue as described above...
http://asciinema.org/a/2d00z0rytoxxowfsldkigmozv
