### ISSUE TITLE
"smart_completion = False" doesn't work

### ISSUE THREAD

**Issue by jialongl** [dbcli/mycli#334]
Having `smart_completion = False` in `~/.myclirc` and launch `mycli`, the text `[F2] Smart Completion: OFF` in greyed-out style shows at the bottom of the terminal --- normal.

However, at the end of the line it shows `Refreshing Completions ...` and when the message disappears, greyed-out `[F2] Smart Completion: OFF` becomes bright `[F2] Smart Completion: ON`.

Please confirm and advise.

**Comment by amjith** [comment]
You're right the config option in ~/.myclirc seems to be not honored. I'll look into this. Sorry about the bug. 😞

**Comment by tsroten** [comment]
@amjith I know you already assigned this to yourself, but I happened to already be looking at that setting: https://github.com/dbcli/mycli/compare/honor_smart_completion_setting?expand=1

Okay if I submit a PR for this one?

**Comment by tsroten** [comment]
@amjith, Haha totally didn't see your PR until just now. Feel free to ignore that one :)
