### ISSUE TITLE
Auto Capital case for SQL key words.

### ISSUE THREAD

**Issue by mmuruev** [dbcli/mycli#336]
Is it possible make an option for convert
` select id, field from my_table `
in to
` SELECT id, field FROM mytable;` ?

**Comment by tsroten** [comment]
@mmuruev Hello and thanks for using mycli!

Are you referring to the `SELECT` keyword's change from lowercase to uppercase? Or, the change from `my_table` to `mytable`?

In the case of the latter, tab completion will automatically convert your lowercase keyword into uppercase.

In the case of the former, have you tried the smart completions option (you can toggle it on/off with [F2])?

**Comment by tsroten** [comment]
@mmuruev Let us know if you get a chance to try out the tab completion and see if that auto-capitalizes for you. It works like this:

Type `se` and hit `<enter>` -- you should have `SELECT`. You can do the same thing by typing the  whole word: `select`, then hit `<enter>`.

**Comment by mmuruev** [comment]
Yes. Awesome. Looks good! But is possbile make it without 'TAB' or 'ENTER' just writting sum( will auto replace it to SUM( ?

**Comment by amjith** [comment]
@mmuruev A similar feature was (requested)[https://github.com/dbcli/pgcli/issues/615] in pgcli (sibling project of mycli). I gave a detailed answer on why that's not possible. I'm pasting that answer below:

> That is a dangerous precedent that we'd like to avoid. If a user chooses an entry from the menu by using the up/down arrow or tab key then it is a choice made by the user. But if we go in and modify what the user has typed in, it can lead to undesired behavior. For example, I've seen table named session which is a reserved keyword in postgres. If we took this approach of auto-capitalization of keywords then anytime the user types session we'll replace it with SESSION. This is just one example.
> 
> In general we'd like to avoid changing the query typed by the user. So the closest solution to your request is what we have implemented already.

> It does know the context for the most part. It works great for nearly 90% of inputs (probably more). But writing auto-completers is hard since we're working with partial statements. So the syntax is not fully formed which makes it hard to compensate for parser shortcomings. I guess what I'm saying is when the sql statement gets complicated it can cause unexpected behavior.

> So we can't rely on the parser to do a good job in discerning a table name vs a keyword. This becomes especially relevant when you start writing nested SQL such as

```
WITH RECURSIVE search_graph(id, link, data, depth) AS (
        SELECT g.id, g.link, g.data, 1
        FROM graph g
      UNION ALL
        SELECT g.id, g.link, g.data, sg.depth + 1
        FROM graph g, search_graph sg
        WHERE g.id = sg.link
)
SELECT * FROM search_graph;

```
> Obviously I'm giving you a worst case scenario but my attempt is to demonstrate why it is undesirable to rewrite a query that a user has typed in with insufficient context.

**Comment by tsroten** [comment]
@mmuruev I think automatically changing what the user types is something that isn't a great fit for mycli, like @amjith mentioned.

I hope that you continue to get a lot out of mycli. Thanks for using mycli and let us know if you have any other ideas or issues!
