### ISSUE TITLE
autocomplete on other command prompt

### ISSUE THREAD

**Issue by zer09** [dbcli/mycli#343]
If you open mycli on two or more command prompt then you create new table from the other one, then you switch to other command prompt, the new created table cannot be found on the autocomplete.

Thanks.

**Comment by amjith** [comment]
Hi, We try try not to refresh auto-completion until a DDL statement (like DROP, UPDATE, CREATE) have been executed. 

But if you'd like to trigger a refresh you can always do that manually by typing `\#`.

**Comment by zer09** [comment]
ohh thanks a lot. It works.

BTW why some of the mysql keyword is missing on the autocomplete, example the auto_increment, constraint, etc?

Thanks.

**Comment by amjith** [comment]
Sorry the keyword list is not complete, but you can totally add new keywords and send a PR. It's quite trivial. https://github.com/dbcli/mycli/blob/master/mycli/sqlcompleter.py#L21

😄
