### ISSUE TITLE
Emacs mode: Multiple delete words are not pasted correctly

### ISSUE THREAD

**Issue by dbolser-ebi** [dbcli/mycli#355]
In emacs this will eat the next two words and then spit them out. In mycli it eats two words but then only spits out the last one eaten.

**Comment by dbolser-ebi** [comment]
I've logged this with [python-prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) here: https://github.com/jonathanslenders/python-prompt-toolkit/issues/479

**Comment by amjith** [comment]
Thanks for filing the issue with prompt-toolkit. I'll keep an eye on the issue and upgrade as soon as they release.

**Comment by tsroten** [comment]
I renamed the title, so here is the original title:
```
alt-d alt-d then ctrl-y
```

**Comment by schmeic** [comment]
This is somewhat related - is there any way in emacs mode to use underscore as a word boundary? Currently, alt-f will go all the way to the end of 'some_table_name', unlike in the mysql client. Is this also an issue with prompt-toolkit?

**Comment by pasenor** [comment]
@schmeic yes, navigation in emacs mode is handled by the prompt toolkit. 

Closing, as the original issue is fixed.
