### ISSUE TITLE
Smart autocomplete?

### ISSUE THREAD

**Issue by dbolser-ebi** [dbcli/mycli#357]
I use predictive text on my phone, I wonder if mycli could have that mode?

i.e. typing the following "S<tab>* F<tab>blah W<tab>" would give me "SELECT * FROM blah WHERE ".

Just a fun feature request ;-)

**Comment by amjith** [comment]
I realize that you're half-joking with this feature request. But I'm going to entertain this issue and talk through a few of my thoughts. 

1. Writing `S * F blah W` might look like a short version of the full sql, but in reality this requires forethought on the users' part to come up with that string and I'd argue that the auto-completion achieves the same result with the same input using the tab key. You type `S<tab>` you get `SELECT` then you type * and then you type `F<tab>` and you get `SELECT * FROM` and so on. So technically we're not saving any keystrokes except many the `<tab>` presses. 

2. The completion engine is a fairly complex piece of code. Having it expand `S * F blah W` might make it even more complex, thus making it hard to add features in the future. 

So for the reasons mentioned above, I'm going to say this is a highly unlikely feature to support in mycli. What do you think?

**Comment by dbolser-ebi** [comment]
​Yeah, I'd say it should be a separate code / mode. To be clear, I think
tab strokes should be there, just that the order of the selection should be
based on usage rather than alphabetical, so fewer tabs in general.

**Comment by simolev** [comment]
> the order of the selection should be based on usage rather than alphabetical
This is my idea, too. Show the first n most used values before alphabetically listing all the rest.
n should be configurable in ~/.myclirc. Feature request?

**Comment by tsroten** [comment]
@simolev Thanks for the input! That sounds more similar to https://github.com/dbcli/mycli/issues/351.

**Comment by pasenor** [comment]
Let's move the discussion to #351.
