### ISSUE TITLE
apt-get installs old version

### ISSUE THREAD

**Issue by mikeerickson** [dbcli/mycli#370]
I am trying to install the latest version (I have 1.8.1 on my macOS)

Trying to install on Linux, but it always installs 1.5.2-4?

```
$ apt-get update
$ apt-get install mycli
```

This always installs 1.5.2-4, how can I get latest version installed?

**Comment by j-bennet** [comment]
Ah, that must not have been updated for a while. Any reason to not use `pip install mycli`?

**Comment by meeuw** [comment]
There is a development version available on launchpad:
https://launchpad.net/ubuntu/+source/mycli

But I'm not sure how to install this on Ubuntu.

**Comment by mikeerickson** [comment]
@j-Bennet I will give pip a try

**Comment by mikeerickson** [comment]
@j-bennet I am trying to completely remove mycli so that I can install via pip

```
$ apt-get purge mycli <-- appears to remove 
$ mycli --version 
The program 'mycli' is currently not installed. You can install it by typing:
sudo apt install mycli
```

Now trying to install via pip

```
$ pip install mycli

Requirement already satisfied: mycli in ./.local/lib/python2.7/site-packages
Requirement already satisfied: pycrypto>=2.6.1 in ./.local/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: PyMySQL>=0.6.2 in ./.local/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: prompt-toolkit<1.1.0,>=1.0.0 in ./.local/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: Pygments>=2.0 in ./.local/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: configobj>=5.0.6 in ./.local/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: sqlparse<0.2.2,>=0.2.0 in ./.local/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: click>=4.1 in ./.local/lib/python2.7/site-packages (from mycli)
Requirement already satisfied: six>=1.9.0 in ./.local/lib/python2.7/site-packages (from prompt-toolkit<1.1.0,>=1.0.0->mycli)
Requirement already satisfied: wcwidth in ./.local/lib/python2.7/site-packages (from prompt-toolkit<1.1.0,>=1.0.0->mycli)
```

**Comment by mikeerickson** [comment]
@j-bennet Well, I got this working.  However, I had to setup ruby and linuxbrew (which I planned on doing anyway).

```
$ brew install mycli
```

And I now have `v1.8.1` installed

**Comment by amjith** [comment]
Wow, I had no idea there was such a thing as `linuxbrew`. 

I'm sorry you were having difficulty getting the latest version and I'm glad you found a workaround. Thanks for telling us about linux brew. :)

**Comment by mikeerickson** [comment]
@amjith no worries, thx for reply :)
