### ISSUE TITLE
How do I set the options that the LESS pager uses?

### ISSUE THREAD

**Issue by mikeerickson** [dbcli/mycli#376]
Just installed `1.9.0` and there seems to be difference

In 1.8.1, the console would scroll with the various entered commands as usual

![image](https://cloud.githubusercontent.com/assets/183153/24078200/68002ffe-0c24-11e7-83ee-c7f31b649e14.png)

But with 1.9.0, it appears it clears screen rather "aggressively"  After each command, it clears the screen and then output results

![image](https://cloud.githubusercontent.com/assets/183153/24078205/98c922bc-0c24-11e7-8418-203480c42472.png)

Is there a setting for this?
If not, how do I go about reverting 1.8.1

**Comment by meeuw** [comment]
Hmm that's stange, I think it is related to this commit (c3ed9a67aeb1a30ddf0ed67203def3aa4c9753ab) where os.environ['LESS'] only get set when it's empty. Could you please check your LESS environment variable by running `echo $LESS` in your shell?

**Comment by johnksterling** [comment]
Agree - let me know what you see and I can help troubleshoot.  Hopefully you it is working as designed - i.e. passing through your default less settings.

**Comment by golovan** [comment]
Same issue. $LESS gives -R for me. export LESS="-RXF" fixes it. Placed it into my .zshrc file for now. :)

**Comment by meeuw** [comment]
@golovan, thanks for reporting! Do you know why you had LESS="-R" ? What operating system are you using (and optionally which toolchain (cygwin/msys/homebrew etc))?

**Comment by huwenchao** [comment]
@meeuw, I got the same issue with @golovan, my toolchain is OS  X EI Capitan, zsh, python environment is anaconda, installed mycli with pip.

**Comment by tonydeng** [comment]
setting $LESS=-RXF

**Comment by glasala** [comment]
Happened to me, solved setting "-RXF".
I had
```
me:~> echo $LESS
-M -I -R
```

**Comment by amjith** [comment]
Hey Folks. We're considering making some changes to the pager stuff in mycli. Can you answer a few questions to help us decide? 

Can you tell us what version of mycli you're using? You can find out the version by:

```
mycli -v
```

Can you also tell us the output of the following commands in your shell (not inside mycli)

```
echo $PAGER
echo $LESS
```

**Comment by glasala** [comment]
Hello,
mycli Version: 1.10.0
pager: less
-RXFI

**Comment by tsroten** [comment]
There is now a page in the documentation devoted to the pager: http://mycli.net/pager

Let us know if anything appears to be missing :smile:.
