### ISSUE TITLE
Add ability to set statement delimiter

### ISSUE THREAD

**Issue by jpitchardu** [dbcli/mycli#383]
Hi, I've trouble using mycli to create stored procedures but when I try `delimiter //;` I get 

> (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'delimiter //' at line 1")

But, if I run it on mysql default client it executes as supposed.

**Comment by tsroten** [comment]
@pichardoJ Thanks for using mycli! I'm sorry you're having issues defining stored procedures.

mycli does not currently support the `delimiter` command -- this is not a SQL statement, but a MySQL client command.

I think it's a good idea. If you or anyone else wants to try to implement it, feel free to :)

**Comment by tsroten** [comment]
Just a note that the sqlparse library we use internally does not currently support delimiters other than semi-colon. They have an ongoing issue tracking this request: https://github.com/andialbrecht/sqlparse/issues/139

**Comment by tsroten** [comment]
A helpful sqlparse user posted a possible workaround for this that we could experiment with in mycli: https://github.com/andialbrecht/sqlparse/issues/139#issuecomment-518659069

**Comment by pasenor** [comment]
There is a neat workaround since version 1.20.0: you can switch to single-line mode and break lines with `Alt-Enter`. It allows you to create multi-line stored procedures without changing delimiters:

![изображение](https://user-images.githubusercontent.com/11982173/66504585-1b167880-ead2-11e9-9c6b-778052094d53.png)

**Comment by pasenor** [comment]
Released in version 1.21.0
