### ISSUE TITLE
mycli fails to return multiple result sets

### ISSUE THREAD

**Issue by sampablokuper** [dbcli/mycli#387]
MySQL and MariaDB are capable of returning multiple result sets, for example [from a stored procedure](https://forums.mysql.com/read.php?98,365143,365804#msg-365804).

In such cases, the `mysql` client displays all the returned result sets, as expected, but `mycli` only displays the first one.

**Comment by meeuw** [comment]
Thanks for reporting, I can reproduce this by:

Create stored procedure:
```
DELIMITER //
CREATE PROCEDURE dmtest
()
BEGIN
  SELECT 1;
  SELECT 2;
END //
DELIMITER ;
```

Call stored procedure
```
call dmtest;
```

And it returns:
```
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set
Time: 0.002s
```

It should return both 1 and 2

pymysql supports multiple resultsets by calling `Cursor.nextset()`, I'll check if this can easily be done.

**Comment by dbolser-ebi** [comment]
Why aren't you calling this a bug?

**Comment by tsroten** [comment]
@dbolser-ebi Mostly because it appears that this was not an oversight, but intentionally left out to make the initial mycli release simpler.

I could easily be wrong :) @amjith

**Comment by dbolser-ebi** [comment]
Hehe, I guess it's semantics.

**Comment by j-bennet** [comment]
This is now fixed in master. To install from master:

`pip install -U https://github.com/dbcli/mycli/archive/master.zip`
