### ISSUE TITLE
I must press 'q' (quit) after I input any command.

### ISSUE THREAD

**Issue by AurevoirXavier** [dbcli/mycli#389]
When I update mycli to 1.9 from 1.8.

I have to press 'q', after input anything.

Although I just press Enter...

I don't want to enter the view mode.

**Comment by belartodmarinus** [comment]
I think this is related to #376 and your LESS variable is not set correct.

Please try `unset LESS` or `LESS="-RXF"` (which is the default) from your shell before starting mycli.

**Comment by meeuw** [comment]
I think this is related to #376 and your LESS variable is not set correct.

Please try `unset LESS` or `LESS="-RXF"` (which is the default) from your shell before starting mycli.

**Comment by AurevoirXavier** [comment]
It works.

You did me a big favor. @belartodmarinus @meeuw
