### ISSUE TITLE
How do I add colors to the prompt?

### ISSUE THREAD

**Issue by mikeerickson** [dbcli/mycli#394]
I am trying to colorize my prompt (I have to use `mycli` on 3 different sessions and want to colorize matching session prompt)

Do you have an example which shows how to do this with `mycli`

I have tried this but it doesn't work (this is what i use from the session prompt)

```
--prompt "[\033[\033[36m\u@\h \[\033[32m\]:\d > "
```

produces

```
[\033[\033[36msotg_www@127.0.0.1 \[\033[32m\]:sotg_www >
```

**Comment by tsroten** [comment]
@mikeerickson Thanks for using mycli! Colorized prompts sounds like it would be helpful. The library we use for the prompt does not currently support ANSI escape codes. If (or when) they do, mycli should be able to use it :)

Here is the issue if you want to track it: https://github.com/jonathanslenders/python-prompt-toolkit/issues/450

You can colorize your prompt in your `.myclirc` (add the `[colors]` section if it doesn't exist):
```
[colors]
Token.Prompt = '#ffffff bg:#4444aa'
```

If you need different colors for different sessions, you'll have to use different `.myclirc`s for each session (which isn't in the released version of mycli, yet -- it will be in our next release).

**Comment by mikeerickson** [comment]
@tsroten OK, I will go the multiple `.myclirc` files as there is really only one per session.  I have a work `SSH` connection, a `Homestead (Vagrant)` connection and `localhost`.

**Comment by tsroten** [comment]
@mikeerickson mycli 1.10.0 has a new command-line argument `--myclirc`, which allows you to specify an alternative config file.

You could alias this in your shell to make it easy-to-use, e.g.:

```bash
$ alias mycli_work='mycli --myclirc ~/.myclirc_work'
```

Then, every time you run `mycli_work`, it loads the correct config file.

I'm going to close this issue for now. If that python prompt toolkit issue is implemented and there is a problem using in mycli, we can open a new issue for it.

**Comment by eirnym** [comment]
@mikeerickson this is available by using `python-prompt-toolkit` 2.x, but mycli and iPython aren't compatible with it.

**Comment by mikedfunk** [comment]
FYI `Tokens.Prompt` config for colors has stopped working. :(

**Comment by j-bennet** [comment]
In Prompt-Toolkit 2.0, tokens are not used for styling anymore. Instead, style strings are used. See the updated config file:

https://github.com/dbcli/mycli/blob/6cd567c367ab0d01973e4f60a96284944f08313d/mycli/myclirc#L88-L107

Tokens that we used previously should still work - they are mapped by this code to "new style" class names:

https://github.com/dbcli/mycli/blob/6cd567c367ab0d01973e4f60a96284944f08313d/mycli/clistyle.py#L15-L39

**Comment by mikedfunk** [comment]
Cool, is there a style string for the prompt so I can color it? I really like having some contrast in my command prompts so I can easily identify them.

**Comment by meeuw** [comment]
Good suggesion, just posted PR #680 for coloring the prompt.

**Comment by mikeerickson** [comment]
Glad to hear, I have been waiting patiently since I orginally asked about it!

**Comment by cangyin** [comment]
Thank you all !
The current prompt coloring feature is good enough for me,
![image](https://user-images.githubusercontent.com/50256182/95005381-3a36e000-062a-11eb-9cb2-09d4cae67a50.png)

But just for discussion, will MyCli support prompt coloring like this ?

in `my.ini`:
```ini
prompt=[32m\u@\h:[[36;1m\d[0m[32m][[35m\c[32m]\n[0m[1m>[0m\_
```
![image](https://user-images.githubusercontent.com/50256182/95005340-aebd4f00-0629-11eb-9655-bb5e8fe44081.png)
