### ISSUE TITLE
Add completion support for views.

### ISSUE THREAD

**Issue by amjith** [dbcli/mycli#4]
https://dev.mysql.com/doc/refman/5.0/en/views-table.html

**Comment by mdsrosa** [comment]
@amjith I just check that functionality. It is already working.
<img width="803" alt="screen shot 2015-10-12 at 7 27 57 pm" src="https://cloud.githubusercontent.com/assets/1862239/10440637/7a1b7d96-7117-11e5-8e37-92a424d1c1fb.png">

**Comment by amjith** [comment]
Thanks for checking this one. I'll close the issue.
