### ISSUE TITLE
Shorten sections of the prompt when too long

### ISSUE THREAD

**Issue by asfaltboy** [dbcli/mycli#401]
I ❤️ `mycli` and use it (along with `pgcli`) for everything! Occasionally I connect to a database that, due to the particular Prompt Formatting parts, has a very long `prompt>`. This prompt is so long that I find it difficult to write any, but the most simplest commands, without breaking lines.

This is often the case for servers on Amazon RDS, as AWS hostnames tend to be long unique strings:

    mariadb user@mysql-foobar.n23nlmfml83g.eu-central-1.rds.amazonaws.com:some_database

I am aware of the prompt-format config, and while I'm considering removing the host part, it's actually very useful to be aware of which database I'm looking at the moment, etc.

So to fix this case, I suggest shortening each formatted string when it's 20 chars or longer (configurable), by trimming and introducing an ellipsis somewhere in the middle:

    mariadb root@mysql-foo...naws.com:mt4repl_live1

If this sound like a suitable solution, I'll try to cook up a PR

**Comment by tsroten** [comment]
Hi @asfaltboy! I'm glad to hear you're enjoying mycli! I'm not sure if you're aware that we have two options in the `.myclirc` that are designed to help with this exact issue.

**Option 1:** Newline in the prompt. If you put a `\n` in your prompt in `.myclirc`, then you can make your prompt much more readable. Here is an example:
```
mysql user@mysql-foobar.n23nlmfml83g.eu-central-1.rds.amazonaws.com:(none)
> use my_db;
You are now connected to database "my_db" as user "user"
Time: 0.003s
mysql user@mysql-foobar.n23nlmfml83g.eu-central-1.rds.amazonaws.com:my_db
>
```

**Option 2:** Alias your host names for the prompt. mycli supports MySQL's login paths, which are a way to store the host/user (and optionally password) in an encrypted file. First, add `login_path_as_host = True` to your `.myclirc`. Then, if we want to alias your example as foobar, we can do this:
```
$ mysql_config_editor set --login-path=foobar --host=mysql-foobar.n23nlmfml83g.eu-central-1.rds.amazonaws.com --user=user
$ mycli --login-path=foobar
Password: **********
mysql user@foobar:(none)>
```

You can easily alias `mycli --login_path=foobar` to something like `myclifb` using your chosen shell (e.g. bash, zsh, etc.).

**Comment by tsroten** [comment]
Here is the link to the original issue which had a similar problem with long AWS host names: https://github.com/dbcli/mycli/issues/271

**Comment by amjith** [comment]
I think pgcli has a feature to automatically switch to a smaller prompt when the prompt length is above a certain threshold. https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L88

That might not be a bad idea to port over to mycli.

**Comment by tsroten** [comment]
@amjith Good point. The pgcli option will automatically switch to a simple prompt (only displays database name) when the prompt is over 30 characters. It only does this when the prompt is not customized by the user. I think that'd be a good thing to have, although it doesn't quite help with this problem where the user wants to make sure the host part stays there.

**Comment by tsroten** [comment]
Here is an issue to copy that pgcli feature: https://github.com/dbcli/mycli/issues/402

**Comment by asfaltboy** [comment]
Thank you both! Yes the second solution bestt solves the issue to my liking, since I already use emre/storm I'm used to aliasing my server connections strings.
