### ISSUE TITLE
Unable to upload mycli via setuptools or twine

### ISSUE THREAD

**Issue by tsroten** [dbcli/mycli#407]
I was surprised to hit an error in the release of 1.10.0. This is the second surprise of the week from the good folks at PyPI :)

In this case I uploaded the release manually. But, we can fix it for next time.

```
running upload
Submitting dist/mycli-1.10.0.tar.gz to https://upload.pypi.org/legacy/
HTTP Error 400: author_email: Invalid email address.
error: HTTP Error 400: author_email: Invalid email address.
```

@amjith Are you alright with me making your email address valid in `setup.py` (i.e. `[dot]` -> `.` and `[at]` -> `@`)? I assume it was done that way to prevent spam, so I wanted to double-check with you.

**Comment by j-bennet** [comment]
@amjith: Same here. I already had to enter a valid email address for `pgcli` (except I entered it as `amjith.r+pgcli` because gmail ignores part of the username after `+`, and you can block emails with this `To` address if you like).

**Comment by amjith** [comment]
Pull requests submitted to both mycli and pgcli. I didn't realize my name was still listed there.

**Comment by tsroten** [comment]
Closing since this the pull request is merged and this is now considered resolved.
