### ISSUE TITLE
Installing mycli 1.8.1 with Python 2.6

### ISSUE THREAD

**Issue by Travis-z** [dbcli/mycli#414]
```bash
$ pip install mycli
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting mycli
  Using cached mycli-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pycryptodome>=3 in /usr/lib64/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): PyMySQL>=0.6.7 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): sqlparse<0.3.0,>=0.2.2 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.6 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): prompt-toolkit<1.1.0,>=1.0.10 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): configobj>=5.0.5 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): click>=4.1 in /usr/lib/python2.6/site-packages (from mycli)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/lib/python2.6/site-packages (from prompt-toolkit<1.1.0,>=1.0.10->mycli)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /usr/lib/python2.6/site-packages (from prompt-toolkit<1.1.0,>=1.0.10->mycli)
Installing collected packages: mycli
Successfully installed mycli-1.10.0
```

```bash
$ mycli --help
Traceback (most recent call last):
  File "/usr/bin/mycli", line 7, in <module>
    from mycli.main import cli
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 305
    return {x: get(x) for x in keys}
                        ^
SyntaxError: invalid syntax
```

```bash
$ rpm -qa|grep python-devel
python-devel-2.6.6-66.el6_8.x86_64
$ cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m
```

**Comment by amjith** [comment]
mycli dropped support of Python 2.6 since version 1.9 and above. 

You can either upgrade python 2.7 or you can install an older version of mycli and continue to use it. 

You can use the following command to install an older version of mycli: 

```
pip install mycli==1.8.1
```

Sorry about the inconvenience.

**Comment by meeuw** [comment]
Since you're using CentOS I'd advice you to use the EPEL or IUS yum repositories to install a new version of Python.

https://ius.io/
https://fedoraproject.org/wiki/EPEL

**Comment by Travis-z** [comment]
@amjith  @meeuw think you very mach. I follow your answer, first uninstall, and then re-install, but there are other errors.

# pip install mycli==1.8.1
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting mycli==1.8.1
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading mycli-1.8.1-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 337kB/s 
Requirement already satisfied (use --upgrade to upgrade): configobj>=5.0.6 in /usr/lib/python2.6/site-packages (from mycli==1.8.1)
Collecting sqlparse<0.2.2,>=0.2.0 (from mycli==1.8.1)
  Downloading sqlparse-0.2.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): PyMySQL>=0.6.2 in /usr/lib/python2.6/site-packages/PyMySQL-0.7.11-py2.6.egg (from mycli==1.8.1)
Requirement already satisfied (use --upgrade to upgrade): click>=4.1 in /usr/lib/python2.6/site-packages/click-6.7-py2.6.egg (from mycli==1.8.1)
Requirement already satisfied (use --upgrade to upgrade): prompt-toolkit<1.1.0,>=1.0.0 in /usr/lib/python2.6/site-packages/prompt_toolkit-1.0.14-py2.6.egg (from mycli==1.8.1)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in /usr/lib/python2.6/site-packages/Pygments-2.2.0-py2.6.egg (from mycli==1.8.1)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6.1 in /usr/lib64/python2.6/site-packages (from mycli==1.8.1)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.6/site-packages/six-1.10.0-py2.6.egg (from configobj>=5.0.6->mycli==1.8.1)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /usr/lib/python2.6/site-packages/wcwidth-0.1.7-py2.6.egg (from prompt-toolkit<1.1.0,>=1.0.0->mycli==1.8.1)
Installing collected packages: sqlparse, mycli
  Found existing installation: sqlparse 0.2.3
    Uninstalling sqlparse-0.2.3:
      Successfully uninstalled sqlparse-0.2.3
Successfully installed mycli-1.8.1 sqlparse-0.2.1

# mycli --help
Traceback (most recent call last):
  File "/usr/bin/mycli", line 7, in <module>
    from mycli.main import cli
  File "/usr/lib/python2.6/site-packages/mycli/main.py", line 17, in <module>
    import sqlparse
  File "/usr/lib/python2.6/site-packages/sqlparse/__init__.py", line 12, in <module>
    from sqlparse import cli
  File "/usr/lib/python2.6/site-packages/sqlparse/cli.py", line 22, in <module>
    import argparse
ImportError: No module named argparse

# rpm -qa|grep python-2.6
python-2.6.6-66.el6_8.x86_64

**Comment by tsroten** [comment]
@Travis-z Can you try `pip install argparse`, then run mycli again.

**Comment by tsroten** [comment]
I'm going to close this since we haven't heard from you in awhile. Feel free to open it back up if you'd like 😄

**Comment by brujackie-zhang** [comment]
Thank you very much!

**Comment by Travis-z** [comment]
Thanks guys, Now that I have learned python, this problem is solved
