### ISSUE TITLE
Delimiter does not work

### ISSUE THREAD

**Issue by wangxuesong29** [dbcli/mycli#426]
Hi guys, one more question.

When I use DELIMITER, I can change ; into whatever I want, like the picture 1.
![2017-05-03 09 39 26](https://cloud.githubusercontent.com/assets/14146871/25651628/736c1450-2fe4-11e7-9d9d-96144337b2ee.png)

But when I turn into mycli, I can not do the same thing. When I hit enter, it goes into another line. 
![2017-05-03 09 40 38](https://cloud.githubusercontent.com/assets/14146871/25651692/acdad8f2-2fe4-11e7-8c29-561237dda7e7.png)

zsh with macos sierra.

**Comment by tsroten** [comment]
Hi @wangxuesong29! We currently don't support the delimiter command.

I'm going to close this since it is a duplicate: https://github.com/dbcli/mycli/issues/383
