### ISSUE TITLE
How do I enable local data files?

### ISSUE THREAD

**Issue by dbolser-ebi** [dbcli/mycli#434]
LOAD DATA LOCAL INFILE in mycli gives me this error:

    Wed May 10 16:56:47 2017
    ensrw@mysql-eg-prod-1.ebi.ac.uk:4238/ sorghum_bicolor_core_36_89_20
    > LOAD DATA LOCAL INFILE 
    ->  "/homes/dbolser/EG_Places/Data/Sorghum/Sbicolor_255_v2.1.locus_transcript_name_map_fix.txt"
    ->INTO TABLE
    ->  temp_stable_id_event
    ->;
    (1148, 'The used command is not allowed with this MySQL version')

**Comment by dbolser-ebi** [comment]
I should mention that this same SQL works fine in the standard client.

**Comment by tsroten** [comment]
Hello @dbolser-ebi! Can you make sure that local infile is turned on in mycli?

## Option 1

Add `local-infile=True` to the `[client]` section of your `.my.cnf`.

## Option 2

Start mycli with the local infile option: `mycli --local-infile=1`

**Comment by dbolser-ebi** [comment]
I'm sure that's it, thanks @tsroten ... Yup, works :-D

**Comment by dbolser-ebi** [comment]
Can I add this in my.cli configuration? I don't want mysqldump and friends getting confused by options they don't understand.

**Comment by tsroten** [comment]
@dbolser-ebi Not at this time. I'd try `alias mycli='mycli --local-infile=1'` in your shell config files.

I'm revamping some of the ways we read config options (#281). I'll add a note there that you requested it.

**Comment by dbolser-ebi** [comment]
Thanks again @tsroten.

**Comment by tsroten** [comment]
@dbolser-ebi I forgot to mention the `loose-` prefix for the config option. This is designed to prevent it from breaking other mysql applications. From the [MySQL documentation](https://dev.mysql.com/doc/refman/5.5/en/load-data-local.html):

> If you use LOAD DATA LOCAL in Perl scripts or other programs that read the [client] group from option files, you can add an local-infile option setting to that group. To prevent problems for programs that do not understand this option, specify it using the loose- prefix:
> ```
> [client]
> loose-local-infile=0
> ```
> or:
> ```
> [client]
> loose-local-infile=1
> ```

Mycli supports `loose-local-infile`.

**Comment by dbolser-ebi** [comment]
Wow, MySQL admit that their [client] setting is unfit for purpose... Why
don't they just recommend that you put it in [mysql]? Why don't they just
warn about options the given client doesn't understand? So ... do they
expect every client to be able to ignore every option from every other
client by just prefixing loose? This is crazy!​ (Nothing todo with mycli,
but I guess you've inherited a broken system).
