### ISSUE TITLE
Disable "You are now connected to database" notice after selected database

### ISSUE THREAD

**Issue by keevitaja** [dbcli/mycli#439]
Hello!

Is it possible to disable "You are now connected to database" notice when database has been selected?

Or at least do not require user hit `q`

![screenshot_2017-05-16_09-55-30](https://cloud.githubusercontent.com/assets/158787/26093273/db561c76-3a1d-11e7-81aa-039b1c5cbd6e.png)

**Comment by meeuw** [comment]
Hi, I think your pager `less` isn't playing nice, this is not how it should work.
Please have a look at https://github.com/dbcli/mycli/issues/376, you should set `export LESS=-RXF`.

**Comment by keevitaja** [comment]
Thanx. All good!
