### ISSUE TITLE
prompt not effective and how can let query result show directly on the prompt

### ISSUE THREAD

**Issue by ArduousBonze** [dbcli/mycli#442]
hi,

I have 2 questions:

1. why the prompt not effective since already configed on the ~/.myclirc: 
```
prompt = '\t \u@\h:\d> '
prompt_continuation = '-> '
```
2. how can let query result show directly on the prompt window? Now every time when I run a query, the result show in another cmd(editor) window, I have to press `q` to get back to the mycli prompt window. 

thanks

**Comment by amjith** [comment]
@ArduousBonze 

1. The prompt will be automatically shortened if it was longer than 45 characters. This is to avoid really long host names (like AWS hostnames) from dominating the prompt with useless information. So if your prompt was really long then it will be shortened to just the name of the database. 

2. The result is automatically piped into a pager we try to use the `less` pager to show the results. But if you want you can disable that by setting an environment variable in your shell such as: 

```
export EDITOR=cat
```

This will force mycli to use `cat` as it's pager which will do as you expect.

**Comment by tsroten** [comment]
@ArduousBonze The prompt is only shortened if you are using the default prompt. If you change your prompt to something like `prompt = '\u@\h:\d> '` then it will not shorten.

**Comment by tsroten** [comment]
@amjith Good response :) I think you might mean to set the pager instead of the editor.

In `~/.my.cnf`:
```
[client]
pager = cat
```

**Comment by ArduousBonze** [comment]
Thanks a lot. @amjith  and @tsroten . All my issues are fixed!

```sql
dtboost_test_01@xxxx.mysql.rds.aliyuncs.com:dtboost_test_schema> select account_id from account limit 10;
+--------------+
|   account_id |
|--------------|
|         1000 |
|         2000 |
|         5000 |
|         3100 |
|         3200 |
|         4100 |
|         4200 |
|         4300 |
|         4400 |
|         3000 |
+--------------+
10 rows in set
Time: 0.020s
dtboost_test_01@xxxx.mysql.rds.aliyuncs.com:dtboost_test_schema>
```

**Comment by amjith** [comment]
@tsroten Didn't we decide that we were going to get rid of the support for pager in ~/.my.cnf and add that option to myclirc file?

**Comment by tsroten** [comment]
@amjith Yeah, I'm working on refactoring all the config code.

**Comment by amjith** [comment]
@ArduousBonze We're thinking about making some changes to the way the pager is handled in mycli. Would you mind helping us by answering a couple of questions? 

Can you tell us what version of mycli you're using? You can find out the version by:

```
mycli -v
```

Can you also tell us the output of the following commands in your shell (not inside mycli)

```
echo $PAGER
echo $LESS
```

**Comment by ArduousBonze** [comment]
Sure.

```shell
➜  ~ mycli -v
Version: 1.10.0
➜  ~
➜  ~ echo $PAGER
less
➜  ~ echo $LESS
-R
```
