### ISSUE TITLE
how to clear the blank lines at the bottom  ?

### ISSUE THREAD

**Issue by charliehjkl** [dbcli/mycli#447]
as title

**Comment by amjith** [comment]
Can you elaborate a little? Maybe a screenshot will help.

**Comment by 962464** [comment]
https://github.com/dbcli/mycli/issues/288#issuecomment-279590700

**Comment by tsroten** [comment]
@962464 Hello! If I'm interpreting your link and title correctly, you're wondering how to get rid of the blank lines below the mycli prompt. Those lines are needed for auto-completions to work, which is an essential feature in mycli. We can't get rid of them and still have a working auto-completion menu.

If you're having trouble using mycli in a small window, our next release has a fix for that -- the number of reserved lines will vary based on the size of your terminal window/pane: https://github.com/dbcli/mycli/pull/421

I hope that helps!

**Comment by amjith** [comment]
I'm guessing this is related to the pager stuff. 

Try setting an environment variable called `PAGER` and set its value to `cat`. 

eg: 

```
export PAGER=cat
```

See if that helps.

**Comment by 962464** [comment]
@amjith it doesnot work . thx
@tsroten hope for the next version . thx

**Comment by tsroten** [comment]
@charliehjkl The newest version of mycli is out! If you installed via `pip`, you can upgrade by running `pip install --upgrade mycli`.

There should be less blank lines in small terminal windows. If you're still having trouble, please upload a screenshot so we can see what your problem is. Thanks!!
