### ISSUE TITLE
Have to press q after do some search.

### ISSUE THREAD

**Issue by wuhuanyu** [dbcli/mycli#449]
Newbie to mycli,and it works very well.But whenever I do some operation, I have to bother to press q to quit. Screenshort:
![selection_015](https://cloud.githubusercontent.com/assets/16066355/26752570/9320fa4a-4885-11e7-890f-bc8c100fed5c.png)
After I quit, no result shows in the original terminal:
![selection_016](https://cloud.githubusercontent.com/assets/16066355/26752601/32ab2b76-4886-11e7-8c50-6e16c2993408.png)

Is there something I could change in configuration to avoid such boresome thing?

**Comment by tsroten** [comment]
Hi! That is the pager program, which is enabled by default.

You can disable it by adding this to your `~/.my.cnf` file:

```
[client]
skip-pager=on
```

**Comment by tsroten** [comment]
Hi! That is the pager program, which is enabled by default.

You can disable it by adding this to your `~/.my.cnf` file:

    [client]
    skip-pager=on

**Comment by amjith** [comment]
@wuhuanyu  Can you tell us what version of mycli you're using? You can find out the version by:

```
mycli -v
```
Can you also tell us the output of the following commands in your shell (not inside mycli)

```
echo $PAGER
echo $LESS
```

**Comment by wuhuanyu** [comment]
@amjith 
![selection_017](https://cloud.githubusercontent.com/assets/16066355/26759070/34163baa-4925-11e7-9590-bff3394c9d5f.png)

**Comment by wuhuanyu** [comment]
@amjith @tsroten  I checked another closes issue and solved my problem! I changed the environment variable:
`export PAGER=cat` Thank you! And I think if cat should be default configuration for any new bie to mycli.
