### ISSUE TITLE
Why each time I execute sql, which require me press 'q' to exit the result screen

### ISSUE THREAD

**Issue by jiming** [dbcli/mycli#453]
Hi,

Thank you for this very cool tool, I really love it. I am using version 1.10

But each time I execute sql, it will have such a prompt and I then have to press 'q' to quit. I tried search google. But no solution. Could you please help me figure it out? Great thanks!
``` 
You are now connected to database "jiming" as user "jiming"
(END)
```

Jiming

**Comment by meeuw** [comment]
Hi @jiming, this is a known issue. I think the `LESS` environment variable is set without the `-F` flag, you should unset your `LESS` environment variable, add `-F` to your `LESS` environment variable or disable your pager.

**Comment by jiming** [comment]
Dear meeuw,

Thank you, add -F to LESS work! Have a nice day!

Jiming
