### ISSUE TITLE
How do I connect via a socket?

### ISSUE THREAD

**Issue by ShadowLL** [dbcli/mycli#456]
Mysql database can be connected by command mysql, but can not be connected by command mycli, it response the msessage as the title.

**Comment by meeuw** [comment]
Hmm I think `mysql` connects using a socket and `mycli` using a TCP/IP connection. Could you please connect using `mysql` and post the output from the `\s` command? Especially the `Connection` line.

**Comment by ShadowLL** [comment]
Using mysql:
```
root@kaili:~# mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 46
Server version: 10.1.23-MariaDB-8 Debian 9.0
Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MariaDB [(none)]>
```
Using mycli:
```
root@kali:~# mycli
(1698, u"Access denied for user 'root'@'localhost'")
```

**Comment by meeuw** [comment]
@ShadowLL could you please run the following command `\s` after: `MariaDB [(none)]>` ?

**Comment by ShadowLL** [comment]
@meeuw 
```
mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:          33
Current database:
Current user:           root@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         10.1.23-MariaDB-8 Debian 9.0
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8mb4
Conn.  characterset:    utf8mb4
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 53 sec
```

**Comment by tsroten** [comment]
@ShadowLL Hello! Like @meeuw mentioned, it looks like your `mysql` client is connecting via a UNIX socket, not over a TCP/IP connection. So, here's how you'll want to try to start mycli:

```bash
$ mycli -S /var/run/mysqld/mysqld.sock
```

-----
### Alternative Approach with Config File
You can also put this in a config file so you can start mycli normally:

In `~/.my.cnf`, add:
```
[client]
socket=/var/run/mysqld/mysqld.sock
```

Then, start mycli like this:
```bash
$ mycli
```

**Comment by ShadowLL** [comment]
@tsroten It worked when I tried the command `$ mycli -S /var/run/mysqld/mysqld.sock` as the user root. But it didn't work when I tried the same command as a normal user. Putting this in a config file is not OK either. Should I run the command as the root user?

**Comment by meeuw** [comment]
@ShadowLL please try the following command:
`mycli -S /var/run/mysqld/mysqld.sock -u root`

**Comment by tsroten** [comment]
@ShadowLL I'm interpreting your thumbs up to @meeuw's comment to mean that you got it working, so I'm closing this issue. Feel free to open it up if it didn't.

If the `-u root` part helped, you should be able to add this to `~/.my.cnf` so you don't have to type it in every time:
```
[client]
user=root
socket=/var/run/mysqld/mysqld.sock
```

**Comment by pawaanv** [comment]
below configuration worked for me on fedora 26 
[mysql]
user=root
password=ecipher
[client]
socket=/var/lib/mysql/mysql.sock
user=root
password=ecipher

**Comment by GEeKkk** [comment]
**System:**
`Ubuntu 18.04 bionic [Ubuntu on Windows 10]`

I try `mycli -S /var/run/mysqld/mysqld.sock -u root`, but it responsed the msessage: `(2003, "Can't connect to MySQL server on 'localhost' ([Errno 2] No such file or directory)")`. 

 This is the ouput from the \s command.

```
mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper
Connection id:          15
Current database:
Current user:           root@localhost
SSL:                    Not in use
Current pager:          less
Using outfile:          ''
Using delimiter:        ;
Server version:         5.7.23-0ubuntu0.18.04.1 (Ubuntu)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 23 min 59 sec

Threads: 1  Questions: 29  Slow queries: 0  Opens: 107  Flush tables: 1  Open tables: 26  Queries per second avg: 0.020
```

**Comment by msva** [comment]
It is strange issue:

I do have `socket=/path/to/socket` in `~/.my.cnf`, but `mycli` (1.27.0) anyway connects through tcp...

Is it any way to force it to connect through sockett even if tcp is available?
