### ISSUE TITLE
can mycli wrap very long text into multiple lines?

### ISSUE THREAD

**Issue by chrisyue** [dbcli/mycli#463]
when some fields of a row contain very long text, the result table is broke. so can I tune some setting to have a better presentation?
<img width="1436" alt="2017-06-14 10 12 53" src="https://user-images.githubusercontent.com/129517/27112559-7b150118-50ea-11e7-82d6-1c523ff46e20.png">

**Comment by tsroten** [comment]
Hello @chrisyue! Yes, you can definitely tweak this. mycli uses a pager application to display results (typically the program `less`).

You can tell `less` how to display the results by setting an environment variable:
```bash
$ export LESS="-XRFS"
```

A breakdown of the options:
- `-X` leaves file contents on the screen when less exits.
- `-F` makes `less` quit if the entire output can be displayed on one screen.
- `-R` displays ANSI color escape sequences in "raw" form.
- `-S` disables line wrapping. Side-scroll to see long lines.

If you want the change to be permanent, you'll want to set that environment variable in your `.bashrc` or `.zshrc`.

**Comment by meeuw** [comment]
you could also try the 'wide output', append `\G` to your query. For example:
```
select * from generator_16\G
***************************[ 1. row ]***************************
n | 0
***************************[ 2. row ]***************************
n | 1
***************************[ 3. row ]***************************
n | 2
***************************[ 4. row ]***************************
n | 3
***************************[ 5. row ]***************************
n | 4
etc
```

**Comment by chrisyue** [comment]
big thanks to @tsroten and @meeuw

**Comment by tsroten** [comment]
@chrisyue Have fun with mycli! Let us know if you need help with anything else 😄 .

**Comment by Hritik14** [comment]
@tsroten 
thanks for the solution! although, it fills up the terminal buffer very quickly after you press the right arrow and then `q` to close less. Afterwards, when you scroll up in the terminal, you see lots of empty space.
Here's what I mean: https://asciinema.org/a/7nvv8PFapkHUgoBj7GrChF8Re
