### ISSUE TITLE
completions in lowercase

### ISSUE THREAD

**Issue by Chinggis6** [dbcli/mycli#473]
Is it posible to reconfigure `mycli` somehow (I think somewhere within the `.py` files inside `site-packages/mycli`) to suggest autocompletions in lowercase than in all uppercase?

I only type in lowercase and am very used to it as ALL UPPERCASE LETTERS HURT MY EYES :-)

Thanks for the attention.

**Comment by tsroten** [comment]
@Chinggis6 Thanks for mentioning this! We're definitely open to this, but I don't think we've made any progress on this, yet. We welcome new contributors to give it a shot :smile:.

We've had this request before, so I'm going to close this since it's a duplicate. Here is the [original issue](https://github.com/dbcli/mycli/issues/128).

**Comment by tsroten** [comment]
@Chinggis6 Good news, this is going to be in the next release of mycli 😄 .

**Comment by Chinggis6** [comment]
This is really good news to hear today. I admire your responsiveness. Thanks for caring about the users.

**Comment by tsroten** [comment]
@Chinggis6 This is included as of version 1.11.0. If you installed via `pip`, you can upgrade by running `pip install --upgrade mycli`.

To use this, just add this to your `~/.myclirc`:
```conf
keyword_casing = lower
```

We also support `auto` which will suggest upper or lower case based on how you type.

Thanks for the idea!

**Comment by Chinggis6** [comment]
Just to note, completion after typing `show` is displayed all uppercase even when `keyword_casing=lower` :(

**Comment by j-bennet** [comment]
I'll reopen so we can look into it.

**Comment by tsroten** [comment]
@Chinggis6 Thanks again for reporting the issue with the `show` completions. This is fixed as of version 1.13.1, which is in pip.

You can upgrade with:
```
pip install -U mycli
```
