### ISSUE TITLE
How do I disable the pager?

### ISSUE THREAD

**Issue by zer09** [dbcli/mycli#477]
why when executing the ```show``` command, the output is on the vi? it doesn't directly print on the terminal. when you quit the vi you will lose the output.

Any suggestion how to fix this? please.

Thanks

**Comment by tsroten** [comment]
@zer09 Hello! It's probably a pager program like `less`.

If you want to disable it altogether, even if the output is really long, you can add this to your `~/.my.cnf` file:
```conf
[client]
skip-pager = on
```

-----
If you'd rather use the pager, but make the output stay on the screen after quitting, you can try this:
```sh
$ export LESS="-XRF"
```
If you like this second change, you can make it permanent by adding that command to your `.bashrc` or `.zshrc`.

**Comment by tsroten** [comment]
There is now a page in the documentation about configuring the pager: http://mycli.net/pager

Feel free to let us know if you need help with anything.

**Comment by zer09** [comment]
ohh thank you so much.
