### ISSUE TITLE
Unable to display rows with newlines on Python 2

### ISSUE THREAD

**Issue by KyoChou** [dbcli/mycli#479]
When I exec "show create table...",  it got error "unicode argument expected, got 'str'"
![mysqltmp](https://user-images.githubusercontent.com/1185621/28302922-dce4e244-6bc2-11e7-8497-0c184ad8bb68.png)

and my system is
Darwin kyo-mbp15.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Comment by KyoChou** [comment]
and my system is 
Darwin kyo-mbp15.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Comment by tsroten** [comment]
@KyoChou Thanks for reporting this! I'm sorry for the error. This appears to be an issue only on Python 2.

**Comment by tsroten** [comment]
It appears that Pygments attempts to [write a newline (bytes, not unicode)](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/formatters/terminal256.py?at=default&fileviewer=file-view-default#terminal256.py-250) to the output. Our output buffer that we use for styled output expects unicode because we ran into encoding problems when we used bytes.

**Comment by tsroten** [comment]
@KyoChou This is now fixed! Thanks for reporting this. If you installed via `pip` you can upgrade by doing:
`pip install --upgrade cli_helpers`

**Comment by gmagno** [comment]
I'm also hitting this issue. I'm using python 3.9.0.

![image](https://user-images.githubusercontent.com/46817915/102486882-a0e06d00-4061-11eb-9036-0d32cf54d314.png)

**Comment by pasenor** [comment]
@gmagno it is probably an issue in the underlying library [cli_helpers](https://github.com/dbcli/cli_helpers), I'll look into it. Some formats are unaffected, for example you can switch to `psql`:
```
mysql root@localhost:employees> \T psql
Changed table format to psql
Time: 0.000s
mysql root@localhost:employees> show create table departments;
+-------------+----------------------------------------+
| Table       | Create Table                           |
|-------------+----------------------------------------|
| departments | CREATE TABLE `departments` (           |
|             |   `dept_no` char(4) NOT NULL,          |
|             |   `dept_name` varchar(40) NOT NULL,    |
|             |   PRIMARY KEY (`dept_no`),             |
|             |   UNIQUE KEY `dept_name` (`dept_name`) |
|             | ) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------------+----------------------------------------+
```
To set it permanently change the `table_format` value in  `~/.myclirc`

**Comment by gmagno** [comment]
Fantastic. Changing the table format did the trick.
Thank you for the quick reply, wish you an awesome week.
