### ISSUE TITLE
unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by FengLi666** [dbcli/mycli#493]
Version: 1.11.0
when query a utf-8 encoding table
~~~
unicode argument expected, got 'str'
~~~
this occurs in mycli , but have not happen in mysql terminal

**Comment by tsroten** [comment]
@FengLi666 The upcoming release of mycli fixes this.

If you installed mycli via `pip`, you can fix this now by doing this:
```bash
$ pip install -U cli_helpers
```

**Comment by FengLi666** [comment]
Thank you very much @tsroten .
