### ISSUE TITLE
Feature request: source command filename completion

### ISSUE THREAD

**Issue by chrisamow** [dbcli/mycli#500]
Allowing completion on the source command would really add to the integrated feeling of mycli as a development tool.  It would allow very low friction execution of convenient batches of sql functionality like snippets or environmental database setup. This a followup to a comment left in #108

**Comment by tsroten** [comment]
@chrisamow Thanks for the suggestion! It's a great idea 👍 !

Not sure when we can get to this, but anyone is welcome to give it a shot.

**Comment by tsroten** [comment]
@chrisamow Good news! This was just released in version 1.13.0. If you installed via pip you can upgrade by running `pip install -U mycli`

It's also in Homebrew as well: `brew update && brew upgrade mycli`.

**Comment by chrisamow** [comment]
You guys are awesome!!  Thanks! I use mycli a lot, especially when I want to copy/show the results.
