### ISSUE TITLE
mycli remote connect fail  ，system is macOS，local is OK

### ISSUE THREAD

**Issue by q2qiang** [dbcli/mycli#502]
log：
![image](https://user-images.githubusercontent.com/20965435/29564992-b68680ce-8776-11e7-9e92-a8baa74c4ce4.png)

![image](https://user-images.githubusercontent.com/20965435/29565039-df6c9f96-8776-11e7-8db2-f55cfdb045ab.png)

remote mysql version：

![image](https://user-images.githubusercontent.com/20965435/29565089-1792b63a-8777-11e7-88ce-b451460bc040.png)

can  you help me？

**Comment by fpietka** [comment]
We are looking into it.
In the meantime would it be possible for you to paste the test rather than screenshot? It would be easier for us to copy/paste, and also would be referenced in search for people with the same issue as yours.

To copy output of the error, you can try the following:
```
mycli -u root -h your_host 2>&1 pbcopy
```

Thanks.
