### ISSUE TITLE
mycli fails to connect to ProxySQL

### ISSUE THREAD

**Issue by LiraNuna** [dbcli/mycli#504]
For some reason, mycli is having issues connecting to ProxySQL:

```
$ mycli -u admin -padmin -h 127.0.0.1 -P 6032
(1045, u'no such function: connection_id')
$ mycli -u admin -padmin -h localhost -P 6032
(1045, u'no such function: connection_id')
```

While mysql cli connects to it just fine:

```
$ mysql -u admin -padmin -h 127.0.0.1 -P6032
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql> 
```

**Comment by meeuw** [comment]
Hi @LiraNuna I don't think someone tried to use mycli with proxysql yet; I'm not sure if we can support it.

Could you please add the relevant errors from `~/.mycli.log`? I'll see if I can reproduce this error using the docker image from `perconalab/proxysql`.

**Comment by LiraNuna** [comment]
Sadly this is all that the log provides:

```
2017-08-24 11:46:08,194 (12200/MainThread) mycli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/mycli/main.py", line 400, in connect\n    raise e\nOperationalError: (1045, u\'no such function: connection_id\')\n'
```

**Comment by meeuw** [comment]
I've found out I need to configure etcd for the docker image (which I haven't done yet).

**Comment by meeuw** [comment]
Ok, I did the following (server-mysql is my mysql docker container, which has ip address 172.17.0.2):
- `docker run --link server-mysql -p 6033 --rm -ti centos bash -i`
- `yum install -y https://github.com/sysown/proxysql/releases/download/v1.2.1/proxysql-1.2.1-1-centos7.x86_64.rpm`
- `yum install /usr/bin/mysql`
- `mysql -u admin -padmin -h 127.0.0.1 -P6032`
- `INSERT INTO mysql_servers(hostgroup_id,hostname,port) VALUES (1,'172.17.0.2', 3306);`
- `LOAD MYSQL SERVERS TO RUNTIME;`
- `INSERT INTO mysql_users(username,password,default_hostgroup) VALUES ('root','',1);`
- `LOAD MYSQL USERS TO RUNTIME;`
- `SAVE MYSQL USERS TO DISK;`
- `mycli -h 172.17.0.3 -u root -P6033`

And everything seems to work:
```
mysql root@172.17.0.3:(none)> status
--------------
mycli 1.10.0, running on CPython 3.6.2

+----------------------+-------------------------------------+
| Connection id:       | 20                                  |
| Current database:    | information_schema                  |
| Current user:        | root@172.17.0.3                     |
| Current pager:       | System default                      |
| Server version:      | 5.6.36 MySQL Community Server (GPL) |
| Protocol version:    | 10                                  |
| Connection:          | 172.17.0.3 via TCP/IP               |
| Server characterset: | latin1                              |
| Db characterset:     | utf8                                |
| Client characterset: | utf8                                |
| Conn. characterset:  | utf8                                |
| TCP port:            | 6033                                |
| Uptime:              | 1 hour 35 min 47 sec                |
+----------------------+-------------------------------------+

Connections: 1  Queries: 53  Slow queries: 0  Opens: 70  Flush tables: 1  Open tables: 63  Queries per second avg: 0.009
--------------
Time: 0.019s
```

So the good news is; mycli seems to support proxysql and the bad news is, I cannot reproduce your error. Have you tried using the latest version of mycli?

**Comment by LiraNuna** [comment]
> Have you tried using the latest version of mycli?

I'm using the version in `pip`: 
```
$ mycli --version
Version: 1.12.1
```

**Comment by LiraNuna** [comment]
I found the difference in our usage: I was using `mycli` to connect to the default admin user, which operates on different port:

```
$ mycli -u admin -padmin -h 127.0.0.1 -P6032
(1045, u'no such function: connection_id')
```

**Comment by meeuw** [comment]
ah, yes I'm sorry I didn't notice you're connecting to port 6032.
This is a mysql server "simulation" for configuring proxysql. I will test this later.

**Comment by fpietka** [comment]
@meeuw FYI: https://github.com/sysown/proxysql/issues/1134
It seems Proxysql doesn't support `connection_id()` yet.

Since it is used solely to kill the connection on keyboard interrupt, I can't say if it is safe to bypass for now.

**Comment by meeuw** [comment]
Hmm, yes, and even then; kill isn't implemented in the proxysql admin interface. We'll have to check if the introspection for mycli auto suggestion even works. There is no `information_schema.columns` table for this in the proxysql admin interface 😞. I think the proxysql admin interface is a no-go for mycli (it wouldn't be possible to suppport all of our nice features like completion)

**Comment by santec** [comment]
Sure, features would be disabled. But the alternative is using a different client only for ProxySQL's admin port, which is a bit uncomfortable :( . I hope you will reconsider this.

**Comment by amjith** [comment]
There is already an issue filed against ProxySQL to support connection_id() which is needed for mycli to work with it. 

Changing mycli to accommodate for missing fields or failing queries is unwanted extra code to maintain. Our target is MySQL and any variants that support the MySQL protocol. It looks like ProxySQL aims to be fully compliant, we'll let them reach that maturity and mycli will start with it automatically.
