### ISSUE TITLE
How to make use of ~/.mylogin.cnf in mycli?

### ISSUE THREAD

**Issue by thanatos** [dbcli/mycli#505]
#94 seems to indicate that support for `~/.mylogin.cnf` was implemented. However, I cannot for the life of me figure out what `mycli`'s equivalent of

```
$ mysql --login-path=myserver mydatabase
```

is.

This is made more frustrating by the fact that http://mycli.net/ is down (and thus, the docs are hard to get to, but AFAICT, there are no relevant docs.)

**Comment by j-bennet** [comment]
This was answered in https://github.com/dbcli/mycli/issues/491. Looks like http://www.mycli.net/ is up right now. The docs are here:

http://www.mycli.net/docs

But you're right, we don't seem to have an entry on that. I'll make sure we add one.

**Comment by tsroten** [comment]
The section in the docs about it simply says:

> MySQL recommends that users store their passwords in an encrypted login path file. Mycli will read this file. For more information about how to store your authentication credentials in this file, see the [MySQL Configuration Utility documentation](https://dev.mysql.com/doc/refman/5.7/en/mysql-config-editor.html).

**Comment by thanatos** [comment]
> This was answered in #491.

@j-bennet You're right. I'm not sure now how I missed the `--login-path` flag. Thank you.

> Looks like http://www.mycli.net/ is up right now.

It's still unreachable from here: I can't successfully resolve your DNS name, `mycli.net`; our OPs team suspects — and I concur with them — that it is because [your DNS host, DreamHost, appears to be under a DDoS attack](https://arstechnica.com/tech-policy/2017/08/dreamhost-takes-a-beating-after-hosting-racist-daily-stormer/); I can resolve your DNS name from *some* places though (e.g., at home is okay, my office is nope, inside AWS is nope) so it appears to be dependent on where/how you resolve it. (I don't really see much that can be done here, other than hope that the people executing the DDoS give up or grow up, or DreamHost finds a way to counter it…)

**Comment by j-bennet** [comment]
Oh goodness, I didn't realize there's a problem with `mycli.net` host, because I still can access without any problems, but I guess it's not the same from everywhere. I hope they resolve it soon. There's now an entry about `--login-path` on [the docs page](http://www.mycli.net/docs) also.
