### ISSUE TITLE
mycli to support   pager？

### ISSUE THREAD

**Issue by csyuancode** [dbcli/mycli#506]
For the results
![image](https://user-images.githubusercontent.com/22109773/29696697-28480bda-897d-11e7-86c8-1d9c6e62ca37.png)
![image](https://user-images.githubusercontent.com/22109773/29696762-8ad69816-897d-11e7-8d57-31670cfa32bc.png)

mysql
![image](https://user-images.githubusercontent.com/22109773/29696772-9c6c8130-897d-11e7-9c2f-a9f10fe9e205.png)

wo more like mycli .  Can I configure it?   Thanks mycli team

**Comment by meeuw** [comment]
I don't understand your question. This is the repository for mycli not mgcli and your screenshots look like the official mysql client (which isn't supported by us).

The pager in mycli can be configured using the `pager` command or in `~/.my.cnf` by settings `pager='vim -'` for example. See http://www.mycli.net/config
