### ISSUE TITLE
Does not work on Debian jessie with Python 2.7

### ISSUE THREAD

**Issue by lunemec** [dbcli/mycli#510]
```
Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 7, in <module>
    from mycli.main import cli
  File "/usr/local/lib/python2.7/dist-packages/mycli/main.py", line 15, in <module>
    from cli_helpers.tabular_output import TabularOutputFormatter
  File "/usr/local/lib/python2.7/dist-packages/cli_helpers/tabular_output/__init__.py", line 11, in <module>
    from .output_formatter import format_output, TabularOutputFormatter
  File "/usr/local/lib/python2.7/dist-packages/cli_helpers/tabular_output/output_formatter.py", line 7, in <module>
    from cli_helpers.compat import (text_type, binary_type, int_types, float_types,
  File "/usr/local/lib/python2.7/dist-packages/cli_helpers/compat.py", line 16, in <module>
    from backports import csv
ImportError: No module named backport
```

There is not much I can add other than this. It is clean install.
Also pip install throws errors upon trying to compile dependencies, and it required me to install these packages (which are not mentioned anywhere, so trial and error):
`apt-get install build-essential python-dev libssl-dev libffi-dev`

When removing all python2 sh*t from the system and installing everything with python3, it works.

**Comment by tsroten** [comment]
@lunemec We should definitely add the apt-get requirements to our documentation.

Can you try installing the missing dependency manually?
```bash
$ pip install backports.csv
```

**Comment by lunemec** [comment]
Ok, I don't understand this, I created new debian jessie image, installed the deps:
```
apt-get install python python-pip python-dev build-essential libssl-dev libffi-dev
```
then I did:
```
pip install mycli
```

and it worked. The only difference I did before was: `pip install --upgrade pip`, so that may have been the problem, but I can't reproduce it. I weep for python and its dependency management, it is worse every year...
