### ISSUE TITLE
mycli on Python 2.7 not running due to missing csv dependency

### ISSUE THREAD

**Issue by bzd111** [dbcli/mycli#511]
machine:  CentOS Linux release 7.3.1611 (Core)
mycli version: mycli-1.12.1

**Comment by bzd111** [comment]
root@zidy ~ >> mycli
Traceback (most recent call last):
  File "/usr/bin/mycli", line 7, in <module>
    from mycli.main import cli
  File "/usr/lib/python2.7/site-packages/mycli/main.py", line 15, in <module>
    from cli_helpers.tabular_output import TabularOutputFormatter
  File "/usr/lib/python2.7/site-packages/cli_helpers/tabular_output/__init__.py", line 11, in <module>
    from .output_formatter import format_output, TabularOutputFormatter
  File "/usr/lib/python2.7/site-packages/cli_helpers/tabular_output/output_formatter.py", line 7, in <module>
    from cli_helpers.compat import (text_type, binary_type, int_types, float_types,
  File "/usr/lib/python2.7/site-packages/cli_helpers/compat.py", line 16, in <module>
    from backports import csv
ImportError: cannot import name csv

**Comment by bzd111** [comment]
I change from backports import csv to import csv 
It works!

# from backports import csv                                                 
import csv

**Comment by tsroten** [comment]
@bzd111 It looks like you're missing one of the dependencies. Can you do `pip install backports.csv` and see if that fixes it?

Your change will work for now, but has the following side effects:
1. Anytime you update, you will have to make the change again.
2. You will not be able to save non-ASCII output in CSV files.

**Comment by tsroten** [comment]
@bzd111 I hope you were able to get mycli running. I'm going to close this issue for now since adding the dependency should make it work. If it's still a problem, feel free to open this back up.
