### ISSUE TITLE
Feature request: aliases with parameters

### ISSUE THREAD

**Issue by Terseus** [dbcli/mycli#518]
It would be cool if the aliases (aka. favorite queries) have support for having arguments, so you can execute them with different arguments every time.

As an example, consider the following query:
```
SELECT * FROM table WHERE foreign_key IN (SELECT id FROM other_table WHERE some_value = $1);
```

Then, you could execute it like:

```
mysql user@host:db> \f example 10
```

This would execute the previous query replacing `$1` with the value `10`.

**Comment by tsroten** [comment]
@Terseus This is a great idea. Thanks for filing the issue.

I've also thought about it prompting the user to fill in arguments that aren't provided. E.g.
```
mysql user@host:db> \f example
some_value? 10
```

**Comment by tsroten** [comment]
@Terseus This feature is in the latest release of myci. Thanks again for the idea!
