### ISSUE TITLE
Prompt user for password when -p, --pass, or --password have no arg

### ISSUE THREAD

**Issue by dougthor42** [dbcli/mycli#530]
The standard MySQL cli interface, `mysql`, allow the user to indicate that a password is required without entering it.

I think that `mycli` should support this as well. It
1. is much more secure than entering the password in plaintext on the command line and
2. would make the transition from `mysql` to `mycli` easier.

#### How the standard MySQL cli works:
```bash
$ mysql -u root -p
Enter password:
```

Docs: 
```
-p, --password[=name]
                      Password to use when connecting to server. If password is
                      not given it's asked from the tty.
```

**Comment by tsroten** [comment]
@dougthor42 Thanks for reporting this! I'm marking it as a duplicate and linking to #341

**Comment by dougthor42** [comment]
Ah, I didn't this issue hidden inside that when when I scanned for dupes. I found it now though. thanks!
