### ISSUE TITLE
tee command is broken in Python 2.7: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by Terseus** [dbcli/mycli#532]
The `tee` command is broken in the current version.
A minimal example:
```
Version: 1.13.1
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - Chris Anderton
mariadb root@localhost:(none)> select 123456
+--------+
| 123456 |
+--------+
| 123456 |
+--------+
1 row in set
Time: 0.020s
mariadb root@localhost:(none)> tee tee_file_test.sql
Time: 0.001s
mariadb root@localhost:(none)> select 123456
write() argument 1 must be unicode, not str
mariadb root@localhost:(none)>
```

The traceback from the log:
```
Traceback (most recent call last):
  File "/home/terseus/programacion/python/mycli/mycli/main.py", line 550, in one_iteration
    self.output(formatted, status)
  File "/home/terseus/programacion/python/mycli/mycli/main.py", line 719, in output
    special.write_tee(line)
  File "/home/terseus/programacion/python/mycli/mycli/packages/special/iocommands.py", line 295, in write_tee
    click.echo(output, file=tee_file, nl=False)
  File "/home/terseus/virtualenvs/mycli-py2/lib/python2.7/site-packages/click/utils.py", line 259, in echo
    file.write(message)
TypeError: write() argument 1 must be unicode, not str
```

The problem comes from the update of the library [cli_helpers](https://github.com/dbcli/cli_helpers) from 0.2.3 to 1.0.0 but I opened the issue here because I'm not sure if the bug is in mycli or in the library.

Probably @tsroten and/or @meeuw can find the best solution ^_^

**Edit**: For reference, I left here these build links:
* Working build: https://travis-ci.org/dbcli/mycli/jobs/286481539
* Failed build: https://travis-ci.org/dbcli/mycli/jobs/287905558

**Comment by j-bennet** [comment]
This was fixed in https://github.com/dbcli/cli_helpers/pull/32 but not yet released.

**Comment by meeuw** [comment]
:flushed: totally missed this issue, thanks @j-bennet

**Comment by tsroten** [comment]
@Terseus Thanks for pointing this out. This was fixed in a CLI Helpers release earlier today (version 1.0.1). You should be able to upgrade cli_helpers to fix this: `pip install -U cli_helpers`.
