### ISSUE TITLE
it always start from second line, and only highlight with white and black.

### ISSUE THREAD

**Issue by chester7cheng** [dbcli/mycli#535]
![image](https://user-images.githubusercontent.com/20255240/32133616-0cb4525c-bc0e-11e7-9a4a-34e9a3951dd6.png)

hello，
it always start from second line, and only highlight with white and black.
do you have any idea?
i have tried everything.
thank you!

**Comment by meeuw** [comment]
Hi @chestercheng which terminal emulator application are you using and of which operating system?

**Comment by chestercheng** [comment]
hi @meeuw 

Vagrant 2.0.0 + VirtualBox 5.1.30
CentOS Linux release 7.4.1708 (Core)
Zsh Shell
and  i use Git Bash (in git version 2.14.3.windows) remote login.

actually when i login using the terminal in VirtualBox, it work perfectly.
and in all  of other environment, it  work perfectly.

thank you!

**Comment by j-bennet** [comment]
@jonathanslenders, do you think you could advise on this?

**Comment by jonathanslenders** [comment]
Hi @chester7cheng,

From within git-bash, do you have any idea which Python interpreter is used? Is it the one from the Windows installation? What is the output of ``which mycli``? 
If it is the Windows Python installation, you need to use winpty to start it from git-bash.
From the screenshot though, I'm not sure what happens.

**Comment by chester7cheng** [comment]
Hi @jonathanslenders @j-bennet @meeuw 

I use git-bash just as a SSH client.(to remote login linux)
Python interpreter version: 2.7.

I did nothing change to anything, but when i check again, mycli work with the beautiful syntax highlight now.
It really only has white&black syntax highlight until yestoday. 

Thanks all of you!

This screenshot is detail of my environment:
![image](https://user-images.githubusercontent.com/20255240/32228946-9af1b932-be8a-11e7-8b7c-0fcc5a025d92.png)
