### ISSUE TITLE
queries history/favorites query

### ISSUE THREAD

**Issue by mysz** [dbcli/mycli#54]
In Sequel Pro, which I mentioned some time ago, is very nice feature: easily accesible history of queries, and favorites queries. I know that i have some kind of history using arrow up/down *when prompt is empty*, but this is very low usable - i can't search through it in any way (or in any way i know currently :) ).

Maybe some kind of "queries repositories" - where i can in simple way add query i sent, add some name to it etc, and some way to search through it (fuzzy :) ).

It also can be extended with idea from #22 - i mean: favorites for all connections or only for one selected connection etc :)

**Comment by amjith** [comment]
Closing this issue since favorites and history search works as expected.

run and exit will be addressed at a later time if there is enough demand.
