### ISSUE TITLE
USE without ;

### ISSUE THREAD

**Issue by santec** [dbcli/mycli#556]
Mainstream mysql cli doesn't require ; or \G after the command USE <dbname>. It would be nice to have the same in mycli (if nothing else, because habits are hard to change).

**Comment by amjith** [comment]
We don't require a ; or \G for any of the commands not just USE. 

The ; is only needed if you are in the multi-line mode. You can toggle multi-line mode using the F3 key or by setting `multi_line = True` in you config file (~/.myclirc).

**Comment by santec** [comment]
Thanks for clarification
