### ISSUE TITLE
Toolbar display problem with Tango in Terminal on Linux Mint 13.

### ISSUE THREAD

**Issue by j-bennet** [dbcli/mycli#56]
With Multiline ON:

![mycli-toolbar-ok](https://cloud.githubusercontent.com/assets/637013/8241976/2b8d83c4-15c1-11e5-9ccc-026fd8315b25.png)

With Multiline OFF:

![mycli-toolbar-not-ok](https://cloud.githubusercontent.com/assets/637013/8241982/35795868-15c1-11e5-8320-e67cd125a9a9.png)

Here is my terminal setup:

![gnome-term](https://cloud.githubusercontent.com/assets/637013/8242060/d4a27bf4-15c1-11e5-9077-d4b4dd99f467.png)

![gnome-term-color](https://cloud.githubusercontent.com/assets/637013/8242061/d4a28ec8-15c1-11e5-9a38-2eb673702bbb.png)

**Comment by tsroten** [comment]
Hi @j-bennet! Is this still a problem?

**Comment by j-bennet** [comment]
Good question. I don't work in Mint anymore. :) I'll close this.
