### ISSUE TITLE
Alias DSN connection doesn't work

### ISSUE THREAD

**Issue by cvetan** [dbcli/mycli#563]
I've configured alias_dsn in .myclirc. 

But when i try to connect: i get error: 
`Error: no such option: -d`

Docs clearly says -d is the option. What it the problem? This is pretty handy option for me,because i have several db servers i connect to all the time.

**Comment by tsroten** [comment]
Hi @cvetan! It seems like maybe you're not on the latest release (1.16.0). If you installed through homebrew, we're about to upgrade the version on there.

You can check your version by running `mycli -v`.

**Comment by cvetan** [comment]
Yeah. 1.13.1 :(

I didn't install via homebrew, i am on Manjaro Linux.

**Comment by tsroten** [comment]
@cvetan Great! This makes me think it would be useful to put an “added in version X” note on features in the documentation.
