### ISSUE TITLE
Autocompletion fails for more than one join

### ISSUE THREAD

**Issue by SunflowerFuchs** [dbcli/mycli#567]
If i have a query with more than one join, autocompletion won't show the name/alias of the second joined table, nor its columns.

Example:
```SQL
SELECT * FROM users u
INNER JOIN user_tags ut ON ut.`USER_ID` = u.`USER_ID`
INNER JOIN tags t ON ut.`TAG_ID` = t.`TAG_ID`;
```
In this example, it'd show the names, aliases, and columns of the tables "user_tags" and "users", but not of the table "tags", nor any of the tables that might follow.

`mycli 1.16.0, running on CPython 2.7.12`

**Comment by meeuw** [comment]
For mycli 1.15.0 I've made some changes to add joins to the completions but it isn't perfect.

Does it work when you use the alias for tags (`t.`) ?

**Comment by egoisticalgoat** [comment]
I've just installed it at home so i can try it out with a fresh database for testing, getting the same results.
After the join keyword, it suggests me all tables, like it's expected. But after the on keyword, it only suggests the first two table names or, if given, their alias. The third table doesn't even get suggested. Doesn't make a difference if i do all aliases, mixed aliases/table names, or all table names.

**Comment by NeverI** [comment]
I have the same issue with version 1.20.1 :(
