### ISSUE TITLE
Twine update?

### ISSUE THREAD

**Issue by brainwane** [dbcli/mycli#587]
Hi! I'm one of the maintainers of [Twine](https://pypi.org/project/twine/). We've just released 1.11.0 and I notice that you [use an old version](https://github.com/dbcli/mycli/blob/88858208b46b6bd5b925287ae544d6cde4cc02e5/requirements-dev.txt#L5) -- please let me know if you've experienced any barriers to upgrading. Thanks!

**Comment by brainwane** [comment]
Thanks! Would you consider using [1.11.0](https://pypi.org/project/twine/1.11.0/), which is a little more recent? If you had any trouble with it, we would like to know. :)

**Comment by tsroten** [comment]
We're now using 1.12.1 - closing this issue for now.
