### ISSUE TITLE
Please add instructions for Cygwin

### ISSUE THREAD

**Issue by simolev** [dbcli/mycli#590]
It would be useful to know beforehand the steps needed to install [mycli ](https://www.mycli.net) on [cygwin](https://cygwin.org).  
Please add them to [README.md](https://github.com/dbcli/mycli/blob/master/README.md).

1. Install cygwin packages: `python3`, `gcc-g++`, `python3-devel`, `libffi-devel`, `openssl-devel`.
2. Download and run get-pip.py (as explained [here](https://pip.pypa.io/en/latest/installing/)): 
    `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
    `python3 get-pip.py`

3. And, finally, install mycli:
`    pip install -U mycli`

**Comment by tsroten** [comment]
@simolev Good idea! We'll get it added to the README and [docs](http://mycli.net/install).

**Comment by meeuw** [comment]
hmm, I wonder, isn't pip available by default in cygwin? If it isn't, wouldn't it be better to install pip using easy_install? Or maybe install mycli using easy_install?

**Comment by meeuw** [comment]
I've just installed cygwin and found python3-pip available as a package!

**Comment by simolev** [comment]
@meeuw, @tsroten Thanks!
