### ISSUE TITLE
Questions about MySQL 8.0

### ISSUE THREAD

**Issue by always0108** [dbcli/mycli#598]
When I update MySQL from 5.7 to 8.0, this tool can't affect. I want to ask whether it support MySQL 8.0.

**Comment by friek** [comment]
I've just ran into this problem with mycli 1.8.1. It was giving my a 'Bad handshake' error on connecting, so I thought I'd upgrade to the latest version (1.17.0) with pip.
That version was still giving me a 'Bad handhake', so I upgraded PyMySQL to version 0.8.1 and the problem went away.
mycli appears to depend on PyMySQL >= 0.6.7:
https://github.com/dbcli/mycli/blob/master/setup.py#L19

**Comment by always0108** [comment]
Thanks a lot !

**Comment by always0108** [comment]
The problem has went away .
