### ISSUE TITLE
Error when open local database (2003, "Can't connect to MySQL server on u'localhost' ([Errno 61] Connection refused)")

### ISSUE THREAD

**Issue by whbalzac** [dbcli/mycli#615]
First install by
$ pip install -U mycli

and I run the following line to open local database.
mycli confuse.db

Error:
(2003, "Can't connect to MySQL server on 'localhost' ([Errno 2] No such file or directory)")
Failed to connect by socket, retrying over TCP/IP
(2003, "Can't connect to MySQL server on u'localhost' ([Errno 61] Connection refused)")

**Comment by meeuw** [comment]
Hi @whbalzac! MySQL is a client/server database and you seem to open a filename called `confuse.db`.
You'll need to connect using a `hostname` or a `socket` to connect to your server.
