### ISSUE TITLE
Error reading config file with semi-colon

### ISSUE THREAD

**Issue by rjosodtssp** [dbcli/mycli#616]
![default](https://user-images.githubusercontent.com/11205685/42070592-b35f9f90-7b89-11e8-993e-9d344ac254c2.png)

I changed the option `smart_completion` into `false`, then I restart mycli and the aboving errors happened. Even if I changed it into `true`, mycli still doesn't work. But MySQL is fine.

**Comment by tsroten** [comment]
@rjosodtssp It looks like you might have a semi-colon in at the end of the line in your config file. It would be nice to have a better error message here (without a stack trace).

Can you try removing the semi-colon and see how it works?

**Comment by rjosodtssp** [comment]
Thanks, I didn't notice the semi-colon
