### ISSUE TITLE
Found a problem, delimiter doesn't work

### ISSUE THREAD

**Issue by rjosodtssp** [dbcli/mycli#618]
delimiter works fine in mysql command line
![default](https://user-images.githubusercontent.com/11205685/42495264-2ee4761c-8455-11e8-925f-b77509189d22.png)

same code doesn't work in mycli
![default](https://user-images.githubusercontent.com/11205685/42495268-312dd850-8455-11e8-9b1d-69c2d99360bd.png)

**Comment by tsroten** [comment]
Hi @rjosodtssp! Unfortunately, the custom delimiter is not currently supported. We have an issue that is tracking this: https://github.com/dbcli/mycli/issues/383
