### ISSUE TITLE
Execute initial command without exiting (like mysql's --init-command)

### ISSUE THREAD

**Issue by AndyFWealthfront** [dbcli/mycli#622]
mycli supports -e/--execute to execute a SQL command, and then it exits. I'm looking for a way to execute an initial command but then keep the session open. My use case is wanting to set session variables on every startup such as "set sql_select_limit=1000, sql_max_join_size=1000000".

Would this be worth a separate command-line switch, like --init-command?

This would work as a more general solution to https://github.com/dbcli/mycli/issues/512.

**Comment by AndyFWealthfront** [comment]
I would also be happy with any reasonable workaround. I've been trying Expect (https://core.tcl.tk/expect), but I haven't been able to get it to interact well with mycli's autocomplete popups. I end up with extra control characters printing in the middle of my output sometimes.

**Comment by tsroten** [comment]
@AndyFWealthfront I think this is a neat idea.

As far as Expect goes, we actually use [Pexpect](https://pexpect.readthedocs.io/en/stable/) for our automated test suite, however I'm not sure if it would work any better in a process that you're trying to interact with as well.
