### ISSUE TITLE
Favorite Queries cannot be executed with positional parameters

### ISSUE THREAD

**Issue by VSversus** [dbcli/mycli#626]
Ubuntu 18.04
Mycli 1.8.1

It is not possible to execute favorite query with parameter.

mysql aws@18.184.19.34:(none)> \fs test SELECT '$1'
Saved.
Time: 0.000s
mysql aws@18.184.19.34:(none)> \f test 1
No favorite query: test 1
Time: 0.001s
mysql aws@18.184.19.34:(none)> \f test foo
No favorite query: test foo
Time: 0.000s
mysql aws@18.184.19.34:(none)> \f test 'foo'
No favorite query: test 'foo'

**Comment by mrfrostikcz** [comment]
@VSversus Positional parameters added in v1.14.0. 🙂
