### ISSUE TITLE
drop user - doesn't tab complete the username

### ISSUE THREAD

**Issue by grooverdan** [dbcli/mycli#64]
<pre>
mariadb root@127.0.0.1:mysql> drop USER ACCESS
                                         ACCESS             
                                         ADD                
                                         ALL                
                                         ALTER TABLE        
                                         AND                
                                         ANY                
</pre>

**Comment by martianzhang** [comment]
If a user, which not super a user or not have `mysql` database select privilege, should not run following query. 
`SELECT CONCAT("'", user, "'@'",host,"'") FROM mysql.user`
`SELECT name from mysql.help_topic WHERE name like "SHOW %"`

Some SQL firewall will give an alarm when use mycli tool and take mycli as a dangerous attack.

**Comment by grooverdan** [comment]
@martianzhang , without SUPER is there any command completion that would work anyway?

If the SQL firewall alarms is that a problem for the firewall, mycli, or the incident response team that considers it dangerous without validating its cause?
