### ISSUE TITLE
It can't connect and show me the "2003 error";

### ISSUE THREAD

**Issue by matianhe** [dbcli/mycli#641]
(2003, "Can't connect to MySQL server on 'localhost' ([Errno 2] No such file or directory)")
Failed to connect by socket, retrying over TCP/IP
Password:
(1045, u"Access denied for user 'matianhe'@'localhost' (using password: NO)")

I already set password. It can login when I use mysql command.

**Comment by KeatingSmith** [comment]
maybe you can use the command:

```shell
mycli -u username -h localhost
```

**Comment by eirnym** [comment]
I had this issue when I installed mariadb using `MacPorts`. 

If you want to have a socket connection, You can specfiy socket to connect manually using `~/.my.cnf` file in client section. 
The same file could be used if you want to select preferred protocol if system my.cnf wasn't found for some reason
