### ISSUE TITLE
local-infile does not work 

### ISSUE THREAD

**Issue by laoshaw** [dbcli/mycli#642]
on ubuntu 18.04 with mysql8, I can use 'mysql -u root -p --local-infile=1' as expected, but with 'mycli -u root -p --local-infile=1' it will show "(1148, 'The used command is not allowed with this MySQL version')" when I load local files.

Related problem with the option itslef: 'mycli --help' will show the option as:

--local-infile BOOLEAN        Enable/disable LOAD DATA LOCAL INFILE.

I think it should be

--local-infile=BOOLEAN   (0 or 1)

as otherwise it think '1' is a database name.

**Comment by meeuw** [comment]
Hmm, that's strange, I've just tested this and it works for me. Are you running mycli on the same host as the mysql client?

**Comment by laoshaw** [comment]
yes it works for me this morning, mycli -u root --local-infile=1 -p mydb, not sure what happened.
Thanks for checking.
