### ISSUE TITLE
`use` command should not open a new connection

### ISSUE THREAD

**Issue by laoshaw** [dbcli/mycli#644]
mycli will fail to import mysql's own sample database : https://dev.mysql.com/doc/sakila/en/sakila-installation.html . You can download the schema sql at: https://dev.mysql.com/doc/index-other.html

in the sakila-schema.sql, the first three lines are:
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

looks like mycli somehow is not following them? mysql's native client has no problems though.

"mycli closes the connection and opens a new one after it does the USE sakila; line. So the session variables like FOREIGN_KEY_CHECKS are reset to the defaults for a new connection.

it's actually the USE sakila; line that causes the reconnect, rather than the CREATE SCHEMA. In                 main.py, you can see that register_special_commands() causes a "use" command to call change_db(), which just makes a new connection with sqlexecute.connect()"  - found out by @snoyes on #mysql irc

**Comment by laoshaw** [comment]
"To fix it, I imagine they would break the part of sqlexecute.connect() that fetches information about a connection off into a separate method, and then register "use" to a function that calls                pymysql.select_db() and then the function that gets the connection information, rather than making a new connection."  -- from @snoyes

**Comment by snoyes** [comment]
In main.py, register_special_commands() causes both 'USE' and 'connect' commands to call change_db(), which just calls sqlexecute.connect(), which opens a new connection using pymsql.connect(). In the case of 'USE', it should instead call pymsql.select_db().

**Comment by tsroten** [comment]
Another issue related to the `use` command is the delay when using the new SSH tunnel feature.
It potentially takes a second or two to select a different default database. Ultimately, the `use` command needs to:
1.  Set the sqlexecute.dbname instance variable
2. Trigger the completions thread to run

**Comment by amjith** [comment]
This is now available in v1.19.0. Please upgrade and give it a shot. 

```
pip install -U mycli
```
