### ISSUE TITLE
Search .myclirc in same and directories above

### ISSUE THREAD

**Issue by eirnym** [dbcli/mycli#648]
I request an ability from `mycli` tool  to search it's `.myclirc` file in local directory, directory above till `${HOME}` or `/`. 

Current alternative solutions have their downsides. For example, This behaviour can be achieved by manual specifying rc file with constant remembering to open `mycli` in a specific directory it's located.  Which is quite impractical if project path is long enough. 

Alternatively automatic behavior can be achieved by hooking `cd` which impacts shell performance as `mycli` command is on the bottom of my run list

Reasoning: For some projects I have their own myclirc and want to keep some settings per project. like history file location, DSNs and so on.

**Comment by amjith** [comment]
This feature request reminds me of a vim feature where you can specify where to search for the `tags` file. 

```
set tags=tags;/
```

https://stackoverflow.com/questions/5017500/vim-difficulty-setting-up-ctags-source-in-subdirectories-dont-see-tags-file-i/5019111#5019111

I'd be wary of changing the default behavior to always search from the local folder, but I wonder if we can use a command line option to do this. 

@tsroten @meeuw Thoughts?

**Comment by eirnym** [comment]
I agree to have a command line option or (better) ~/.myclirc option for it.

**Comment by tsroten** [comment]
@eirnym This is now live in version 1.18.0! You can get the newest version via `pip` or [check out the release](https://pypi.org/project/mycli/#files).

**Comment by eirnym** [comment]
Thank you for the release!
