### ISSUE TITLE
insufficient completions for SHOW

### ISSUE THREAD

**Issue by grooverdan** [dbcli/mycli#65]
<pre>
mariadb root@127.0.0.1:mysql> SHOW 
                                    COLUMNS      
                                    DATABASES    
                                    PROCESSLIST  
                                    TABLES       
</pre>

more complete list: https://mariadb.com/kb/en/mariadb/show/

apart from AUTHORS, deprecated innodb status and plugin specific options I use all of these quite regularly.

**Comment by derobert** [comment]
@amjith @grooverdan Another option instead of strace is, if you're using a TCP connection, turn off SSL/TLS and use Wireshark. Very easy to read all the queries then.

**Comment by amjith** [comment]
SHOW command now has appropriate completions.
