### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'value'

### ISSUE THREAD

**Issue by quoidautre** [dbcli/mycli#656]
Hi,
When I launch Mycli, I've this error (python version : 3.5.2) : 

I'm on vagrant : 
```
$ uname -a
Linux vm 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ mycli
Version: 1.5.2
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - Norbert Spichtig
mysql root@localhost:(none)> use Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 673, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/share/mycli/mycli/sqlcompleter.py", line 256, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/share/mycli/mycli/packages/completion_engine.py", line 85, in suggest_type
    full_text, identifier)
  File "/usr/share/mycli/mycli/packages/completion_engine.py", line 134, in suggest_based_on_last_token
    token_v = token.value.lower()
AttributeError: 'tuple' object has no attribute 'value'
```
But, I can use mycli, and, apparently, it's work "fine" :).

Thanks,
F.

**Comment by tsroten** [comment]
@quoidautre Hello!! Thanks for using mycli!

It looks like the version of mycli you're using is very old. Here are a couple of ways you can get a newer version:

1. Use `pip`: `pip install mycli` (might require `sudo`)
2. Use [Linuxbrew](http://linuxbrew.sh/) and run `brew install mycli`

I hope that helps!

**Comment by quoidautre** [comment]
Hi,
Thanks a lot, it's working :)

I've installed mycli using apt-get, and not with pip.

But, why the version aren't the same ?

F.

**Comment by tsroten** [comment]
@quoidautre I don't think we have anyone actively keeping the Ubuntu package up-to-date (see #551 and #308). It looks like the Ubuntu 18.10 mycli version is newer though: https://packages.ubuntu.com/source/cosmic/misc/mycli

**Comment by quoidautre** [comment]
Hi,
Ok.

So, thanks to "pip" :)

F.
