### ISSUE TITLE
Upgrade to Prompt Toolkit 2

### ISSUE THREAD

**Issue by mattLLVW** [dbcli/mycli#660]
It seems that there's a dependency conflict between mycli and IPython.

mycli require 'prompt_toolkit>=1.0.10,<1.1.0' whereas IPython require 'prompt_toolkit>=2.0.0,<2.1.0' .

I'm using both and in a project so for now i need to freeze IPython to an older version.

Would you accept a PR updating this requirement?

**Comment by tsroten** [comment]
Hello @mattLLVW! Thanks for filing this issue. We actually have [a pull request](https://github.com/dbcli/mycli/pull/633) open now that upgrades the prompt toolkit version that mycli uses. It's currently undergoing some testing, but will be merged and released soon.

**Comment by eirnym** [comment]
@tsroten this PR has been merged 5 days ago, when we should expect the release?

**Comment by tsroten** [comment]
@eirnym Very soon! I'm double-checking a few things for the release now. Thanks!

**Comment by tsroten** [comment]
Hello @eirnym and @mattLLVW! This is now released in version 1.18.1. You can update via pip: `pip install -U mycli`.

**Comment by eirnym** [comment]
Thank you @tsroten
