### ISSUE TITLE
Changes theme in .mycli

### ISSUE THREAD

**Issue by kaluosi** [dbcli/mycli#661]
I can't find any place in .myclirc to apply a different theme. 
How can I change the syntax colors in mycli??. Darkblue on black is not very useful.

**Comment by tsroten** [comment]
Hello @kaluosi! That doesn't sound easy to read!

You can change it with the `syntax_style` setting in the `[main]` section of the config file. Here are two links that might help:
1. https://www.mycli.net/config
2. https://www.mycli.net/syntax

**Comment by amjith** [comment]
Re-open the issue if you are still having difficulty.

**Comment by indeedwatson** [comment]
I just want to point out that you could save some users like me a few minutes by rephrasing:

> These themes can be modified via the config file (~/.myclirc).

into:

> These themes can be modified via the config file (~/.myclirc) via the `style` option.

Or something like that, I know it's explained in the whole config doc page but if you're just looking to change the colors, those 3 lines could save someone like me a little bit of time.

**Comment by tom-on-the-internet** [comment]
Agree with this.
