### ISSUE TITLE
Favorite queries not loaded from or saved to config file

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/mycli#669]
When using a non-default config file (`--myclirc`) favorite queries are neither loaded from nor saved to the config files. Instead they are loaded from and saved to the default config file.

The same issue exists in pgcli and mssql-cli.

**Comment by amjith** [comment]
We just got a PR for pgcli to address this exact bug. 

https://github.com/dbcli/pgcli/pull/962

@mdsrosa Do you want to use that as a reference, since it looks like you've got the dibs on this issue?

**Comment by mdsrosa** [comment]
Sorry @amjith - just seeing this now. I'll check out the PR. Thanks!

**Comment by tsroten** [comment]
@thorstenkampe Thanks for reporting this -- it should be fixed as of yesterday's release, version 1.20.0. You can upgrade if you installed via pip:
`pip install -U mycli`

**Comment by thorstenkampe** [comment]
@tsroten confirmed
