### ISSUE TITLE
SIGTSTP trapped?

### ISSUE THREAD

**Issue by yjfguhd** [dbcli/mycli#688]
In 1.18.2, `^Z` does not suspend the process. This used to happen on at least version 1.16.0. Instead, "^Z" is printed:

```
prompt> ^Z
prompt>
```

**Comment by amjith** [comment]
@jonathanslenders I'm guessing this is an artifact of the new prompt-toolkit version. 
Do you know if there is a way to fix this?

**Comment by amjith** [comment]
This is now available in v1.19.0. Please upgrade and give it a shot. 

```
pip install -U mycli
```

**Comment by yjfguhd** [comment]
Confirmed, thanks.
