### ISSUE TITLE
feature request: repeat command on interval

### ISSUE THREAD

**Issue by grooverdan** [dbcli/mycli#69]
While monitoring a server sometime you do commands like show slave status\G or show processlist, or show global status like ... ; where you want it repeated every few seconds or so.

is a syntax like \w{atch} [interval default 5s] :  {SQL}

possible?

**Comment by scottchiefbaker** [comment]
I agree this would be a great feature. A simple `while()` loop with a `sleep()` inside would be sufficient.

**Comment by amjith** [comment]
This feature is now available in master. You can install directly from master as follows: 

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

This will be available in the next release.

**Comment by grooverdan** [comment]
Thankyou!

**Comment by ShawnCorrigan** [comment]
I know this is late, but is there documentation for this? I can't seem to find any (although I could be blind)
