### ISSUE TITLE
I can't use alias_dsn to connect.

### ISSUE THREAD

**Issue by vastpeng** [dbcli/mycli#698]
![image](https://user-images.githubusercontent.com/15377472/49911927-3836e680-fec3-11e8-89d1-9a0b49206d41.png)

what's the matter? I am sure I set dsn in `.myclirc`.

**Comment by vastpeng** [comment]
I have solved it（use options `-d`）, but I think it can be found by default.

New feature?

**Comment by tsroten** [comment]
Thanks for reporting this -- it should be fixed as of yesterday's release, version 1.20.0. You can upgrade if you installed via pip:
`pip install -U mycli`
