### ISSUE TITLE
Calling shell command throws decoding error

### ISSUE THREAD

**Issue by smoothjump** [dbcli/mycli#700]
#### OS
MacOS Mojave
#### Version
1.16.0
#### How to reproduce
Using mysql system keyword to call shell command(e.g. ls) will trigger decode error as below
![image](https://user-images.githubusercontent.com/7953949/49925791-e1e29b80-fef4-11e8-9d88-c9491f1c23e5.png)

I wonder if this is a duplicate problem, if it is, pls let me know. Thx

**Comment by amjith** [comment]
What version of python are you using? 

I'm not able to reproduce it on Python 2.7 or Python 3.6.

BTW, I'm trying this on mycli version 1.19.0, can you try upgrading mycli? 

You can run `pip install -U mycli` to upgrade mycli.

**Comment by smoothjump** [comment]
Mycli was installed via homebrew, I've tried to upgrade it to 1.19 and problem solved now. Thx.
