### ISSUE TITLE
How can I export data in csv?

### ISSUE THREAD

**Issue by vastpeng** [dbcli/mycli#702]
## Example

execute SQL:

```sql
SELECT * FROM t_table LIMIT 3;
```

It will show:

|id|name|
|:---:|:---:|
|1|a|
|2|b|
|3|c|

Now, I want to export these columns into `~/Downloads/export.csv`.

## How can I do it?

`INTO OUTFILE` is not working, because it just work in mysql-server.

**Comment by meeuw** [comment]
Try this:
`\T csv ; \o ~/Downloads/export.csv ; SELECT * FROM t_table LIMIT 3`

**Comment by vastpeng** [comment]
Thanks, it helps me a lot.

**Comment by necesitod** [comment]
just great
