### ISSUE TITLE
Execute query every X intervals

### ISSUE THREAD

**Issue by clijunky** [dbcli/mycli#710]
I routinely use "watch" to execute a given query every X intervals in order to watch something in near realtime.  For example to watch an order as it proceeds through various steps in a log table.

It would be helpful to have this integrated into mycli, so as to avoid the connect/disconnect + figuring out how to escape the command for watch.

One idea of how to implement in the terminal, would be to have a toggle like Vi/Emac keys, that would toggle the repeated execution of the query, the timing of which could be set in the configs.  Sub second interval allowance would be very helpful in watching show processlist.

**Comment by j-bennet** [comment]
What version of mycli are you using? This is already in mycli:

```
| watch       | watch [seconds] [-c] query | Executes the query every [seconds] seconds (by default 5). |
```
example:
```
mysql root@127.0.0.1:test> watch 5 select * from abc
> select * from abc
+-----------------+
| a               |
+-----------------+
| {"name": "tom"} |
+-----------------+
Time: 0.026s
```

**Comment by clijunky** [comment]
I thought I had read the docs thoroughly enough.  

Thank you, it's a wonderful feature.

**Comment by j-bennet** [comment]
I usually run `\?` to list available commands whenever I update the CLI. You never know when something else shows up you may find useful. :)
