### ISSUE TITLE
Logfile config does not work

### ISSUE THREAD

**Issue by rixx** [dbcli/mycli#713]
I'm trying to make mycli run without creating a ``~/.mycli.log``.

``mycli --logfile=~/.cache/mycli.log`` complained that this file or directory did not exist, despite its existance. No ~ expansion?

``mycli --logfile=/home/rixx/.cache/mycli.log`` again creates ``~/.mycli.log``.

**Comment by tsroten** [comment]
@rixx Hello! Thanks for reporting this. So, this appears to be an odd behavior related to how the library we use to parse the command-line arguments works. I think this is definitely worth fixing. For now, here is a workaround.

You can edit your mycli config file (defaults to `~/.myclirc`) and set the `audit_log` config option to `~/.cache/mycli.log`. I actually do something similar with [my mycli config](https://github.com/tsroten/dotfiles/blob/master/.config/mycli/config).

As for fixing this going forward, it looks like we need to change this from a `click.File` to `click.Path`. Marking as a bug 😄

**Comment by Hanaasagi** [comment]
@tsroten. When run

```
mycli mysql://root@10.6.112.32:3306 --logfile=~/mycli.log
```

will get 

```
Error: Invalid value for "-l" / "--logfile": Could not open file: ~/mycli.log: No such file or directory
```

But run 

```
mycli mysql://root@10.6.112.32:3306 --logfile ~/mycli.log
```

It will be ok.

`~` is normally expanded by the shell. If use `--logfile=~/mycli.log`, it will not trigger. I find that someone wants to using `os.path.expanduser` to solve this problem in `Click`, but the pull request was rejected. Please see https://github.com/pallets/click/pull/229.

And `click.Path` will not work too.
