### ISSUE TITLE
mycli doesn't show SELECT `table.columns`  autocomplete

### ISSUE THREAD

**Issue by slarsar** [dbcli/mycli#734]
**mycli cannot auto-complete `table.columns` after [SELECT] ...**

![Screenshot_2019-04-25_18-05-30](https://user-images.githubusercontent.com/46400566/56728305-127cf080-6785-11e9-8051-0d3ab8265500.png)

**Comment by slarsar** [comment]
itemss is a table under database: BUE_SELL.
table itemss describe is these:
![Screenshot_2019-04-30_13-36-09](https://user-images.githubusercontent.com/46400566/56942401-20e45700-6b4d-11e9-9c25-328e3367e236.png)
hope mycli can auto complete table.items like jetbrans database :
![Screenshot_2019-04-30_13-38-56](https://user-images.githubusercontent.com/46400566/56942480-92240a00-6b4d-11e9-80d4-26c4a087346a.jpg)

**Comment by tsroten** [comment]
This is a great idea! We currently only complete columns when the table is specified via a `from` or `join` clause. But, this should definitely be doable.

**Comment by slarsar** [comment]
> This is a great idea! We currently only complete columns when the table is specified via a `from` or `join` clause. But, this should definitely be doable.

I have  forked mycli. Then I will try to   finish this these days.

**Comment by slarsar** [comment]
> This is a great idea! We currently only complete columns when the table is specified via a `from` or `join` clause. But, this should definitely be doable.


inspired by your mycli project ,  I want to regenrtate mycli for Golang version. I'd be very appreated if  you are interested in mycli-go.

I plan to regenerate
