### ISSUE TITLE
[WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by NDelt** [dbcli/mycli#736]
I've installed MariaDB 10.3 on Windows 10, port 3307.
But mycli doesn't work.

>`mysql -u root -p`
-> works well

>`mycli -u root`
-> (2003, "Can't connect to MySQL server on 'localhost'
([WinError 10061] No connection could be made because the target machine actively
 refused it)")

**Comment by j-bennet** [comment]
@NDelt was your problem solved?

**Comment by NDelt** [comment]
@j-bennet it has solved just after re-installing.
