### ISSUE TITLE
Feature request: multi-line with Shift+Enter

### ISSUE THREAD

**Issue by pabloab** [dbcli/mycli#738]
Usually I like and prefer the default _monoline_ mycli approach. But sometimes, when the line became too long I would like to go multiline. Yes we can change [that with <kbd>F3</kbd>](https://www.mycli.net/multi-line) but for example for [byobu](http://www.byobu.org/) users that imply to first disable keybindings. Would be more easy and intuitive to just <kbd>Shift+Enter</kbd> for just that particular newline, the same way we are already familiar while using other apps like WhatsApp web.

**Comment by amjith** [comment]
@jonathanslenders Is this possible to do using prompt-toolkit? 

When I tried to create a keybinding with `s-enter` I got an error message which leads me to believe that this key combination is not supported by prompt-toolkit. Is that true?

**Comment by jonathanslenders** [comment]
No, unfortunately, most terminals don't support shift-enter.

There are maybe a few that allow you to configure what data is sent into stdin if this key combination is pressed, but there is no standard.

**Comment by pabloab** [comment]
Tested with `showkey -a`: Sad but true (mentioned [here](https://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter) and [here](https://unix.stackexchange.com/a/128403/209677)). Same with Ctrl and Super keys.

Could be <kbd>Alt+Enter</kbd> instead?

BTW this enhancement also apply to `pgcli`, should I file a bug there also or this one is enough?

**Comment by amjith** [comment]
@pabloab I have created PR #748 for this. The change is very small. Feel free to port the feature to pgcli and send us a PR. :stuck_out_tongue_winking_eye:

**Comment by pabloab** [comment]
@amjith Thank you so much! I created [PR 1065 on pgcli](https://github.com/dbcli/pgcli/pull/1065). 😀

I hope it comes soon to Debian and Ubuntu repos!

**Comment by tsroten** [comment]
@pabloab Thanks for reporting this -- it should be fixed as of yesterday's release, version 1.20.0. You can upgrade if you installed via pip:
`pip install -U mycli`
