### ISSUE TITLE
Mycli is very slow when import database from local .sql file using 'source' command.

### ISSUE THREAD

**Issue by slarsar** [dbcli/mycli#750]

**Comment by tsroten** [comment]
Hello @slarsar! Thanks for using mycli!

So, we typically [recommend](https://github.com/dbcli/mycli/issues/663#issuecomment-427574674) using the official mysql client for importing large SQL files as it's definitely going to be faster. Mycli really tries to excel at interactive usage.

Is that an option for you here?

**Comment by slarsar** [comment]
> Hello @slarsar! Thanks for using mycli!
> 
> So, we typically [recommend](https://github.com/dbcli/mycli/issues/663#issuecomment-427574674) using the official mysql client for importing large SQL files as it's definitely going to be faster. Mycli really tries to excel at interactive usage.
> 
> Is that an option for you here?

thank you.
