### ISSUE TITLE
bash: syntax error near unexpected token `B128' when use special code

### ISSUE THREAD

**Issue by mnloveyx** [dbcli/mycli#752]
![image](https://user-images.githubusercontent.com/20296448/59602945-a4c4c380-913a-11e9-829a-4edc49b5df62.png)

**Comment by tsroten** [comment]
Hi @mnloveyx! I think that you might need to put quotes around your password. For example:

```
mycli -p "pass)(*word"
```

Another option is to remove the password and `-p` flag. Mycli will automatically prompt you for the password.

I hope that helps!

**Comment by tsroten** [comment]
@mnloveyx I hope that advice helped! I'm going to close this issue for now. If you continue to have problems with this, just let us know, thanks!
