### ISSUE TITLE
Piping in the REPL

### ISSUE THREAD

**Issue by Aerex** [dbcli/mycli#753]
I would like to preface this issue by saying this is an amazing tool. It is far better than the mysql cli. 

In regards to this ticket, this is not a bug but I couldn't find an area where I can ask questions. I would like to pipe the out to csv then run a command to convert this csv to json using this npm cli module [csvtojson](https://www.npmjs.com/package/csvtojson#command-line-usage). Aftewards I would pipe the response to `jq`

Here is an example. 
```
mycli > \o file
mycli > select * from tb1 where id = xxx
mycli > system csvtojson file | jq '.'

[
{"id":"1","status":"on","type":"normal"}
]
```

I expected the json response to be prettified like so 
```
[
  {
    "id": "1",
    "status": "on",
    "type": "normal"
  }
]
```

Is the behaviour from mycli expected or is there something I am missing here.

**Comment by tsroten** [comment]
Hello @Aerex! That's a neat idea! Unfortunately, mycli does not currently support the use of pipes in the `system` command.

However, my recommendation is to use the "pager" for this. It eliminates the need to save the file into a file. First, explicitly enable the pager (by making sure the following is in your MySQL configuration file, `~/.my.cnf`):
```
[client]
pager=on
```

Then, you can use the pager command to extend mycli quite a bit. For example, using the `csvjson` utility from [csvkit](https://csvkit.readthedocs.io/en/latest/):
```
localhost:test_db> \T csv
Changed table format to csv
Time: 0.000s
localhost:test_db> pager csvjson | jq '.'
PAGER set to csvjson | jq '.'.
Time: 0.000s
localhost:test_db> select * from foo
[
  {
    "id": 1,
    "bar": "吃饭"
  },
  {
    "id": 2,
    "bar": "data"
  },
  {
    "id": 3,
    "bar": "hello world"
  },
  {
    "id": 4,
    "bar": "foo"
  }
]
```

Additional common pagers that I use are:
- `vim -`, opens the query output immediately in a Vim buffer for editing or further processing
- `slackcat -c CHANNEL`, sends the query output to the desired Slack channel as an attachment using [slackcat](https://github.com/bcicen/slackcat) (you might need to add the argument `--filetype=text`)

Once in mycli, you can toggle the pager on/off like this:
- `nopager`, pager is disabled, output is simply printed to the screen
- `pager COMMAND`, specify a command to use as the pager
- `pager`, the previously-used pager is turned back on (previously-used in the same session)

I hope that helps!

Additionally, you can use `tee` to save the output to a file *and* send it to an arbitrary command at the same time, which becomes pretty powerful.

**Comment by Aerex** [comment]
That is great. Thanks for the tip!
