### ISSUE TITLE
ImportError: cannot import name DynamicCompleter

### ISSUE THREAD

**Issue by quoidautre** [dbcli/mycli#755]
Hi,
I've a new error when I try to use myscli
I'm on a Debian, "jessie".
```
$ mycli
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/mycli", line 6, in <module>
    from mycli.main import cli
  File "/home/vagrant/.local/lib/python2.7/site-packages/mycli/main.py", line 18, in <module>
    from prompt_toolkit.completion import DynamicCompleter
ImportError: cannot import name DynamicCompleter
```
I try ton install "prompt_toolkit" with pip, but same error :( 
```
$ pip install prompt_toolkit
Requirement already satisfied: prompt_toolkit in ./.local/lib/python2.7/site-packages (1.0.15)
Requirement already satisfied: wcwidth in ./.local/lib/python2.7/site-packages (from prompt_toolkit) (0.1.7)
Requirement already satisfied: six>=1.9.0 in ./.local/lib/python2.7/site-packages (from prompt_toolkit) (1.12.0)
```

Have you an idea please ?

Thanks :
F.

**Comment by tsroten** [comment]
Hello @quoidautre! It looks like the version of prompt toolkit that you have installed is pretty old. Can you post your mycli version so we know which version of prompt toolkit is compatible with it?

You can likely see the version number via: `cat /home/vagrant/.local/lib/python2.7/site-packages/mycli/__init__.py`

**Comment by quoidautre** [comment]
Hi, 
Thanks and sorry for my late response :(
```
mycli==1.19.0
```

**Comment by tsroten** [comment]
@quoidautre No problem!

It looks like you have two prompt_toolkits installed, one in `.local/lib/python2.7/site-packages`, e.g. from this output:
```
$ pip install prompt_toolkit
Requirement already satisfied: prompt_toolkit in ./.local/lib/python2.7/site-packages (1.0.15)
```

And one in `/usr/local/lib/python2.7/dist-packages`, e.g. from this output:
```
$ sudo pip install mycli -U
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: mycli in /usr/local/lib/python2.7/dist-packages (1.19.0)
Requirement already satisfied, skipping upgrade: PyMySQL>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from mycli) (0.9.3)
Requirement already satisfied, skipping upgrade: prompt-toolkit>=2.0.6 in /usr/local/lib/python2.7/dist-packages (from mycli) (2.0.9)
```

I assume it's because one is with `sudo` and one is without `sudo`. I would uninstall from both and do a clean install of mycli using just one of them.

**Comment by quoidautre** [comment]
Hi,
I uninstall Mycli, and it's ok now :)
I've the same issue with PgCli. Do the same "trick", and it's good :)

Thanks.
F.
