### ISSUE TITLE
USE does not change db if used after DELETE and CREATE in single line

### ISSUE THREAD

**Issue by danadam** [dbcli/mycli#756]
I use this sequence quite a lot:

    DROP DATABASE foobar; CREATE DATABASE foobar; USE foobar;

It works in `mysql` client, i.e., I end up with `foobar` database selected. In `mycli` it says that it connects to it but in the end the database is not selected and I have to execute `USE` again on its own:

    mariadb root@localhost:foobar> DROP DATABASE foobar; CREATE DATABASE foobar; USE foobar;
    You're about to run a destructive command.
    Do you want to proceed? (y/n): y
    Your call!
    Query OK, 0 rows affected
    Time: 0.001s

    Query OK, 1 row affected
    Time: 0.000s

    You are now connected to database "foobar" as user "root"
    Time: 0.000s
    mariadb root@localhost:(none)>
    mariadb root@localhost:(none)> USE foobar
    You are now connected to database "foobar" as user "root"
    Time: 0.000s
    mariadb root@localhost:foobar>

**Comment by tsroten** [comment]
@danadam Thanks for using mycli! And, thanks for finding this bug.

My hunch is this is a bug introduced by #490.

**Comment by SukiCZ** [comment]
Hi @tsroten :tada: 
I love using `mycli` and this seems like a good way to say thanks :two_hearts: 
You can find PR fixing this issue #796 :computer: 

Let me know what you think :thinking: 

Thanks! :beers:
