### ISSUE TITLE
Access denied for user

### ISSUE THREAD

**Issue by josephhyatt** [dbcli/mycli#759]
Hi, I am trying to login to mycli using the terminal in ubuntu 18.04.

When I type `mycli` I get an opportunity to put in my password, so I put in my password and get `(1045, "Access denied for user 'jh'@'localhost' (using password: YES)")`. When I try to enter `sudo mycli` and enter my root password I get an output `(1698, "Access denied for user 'root'@'localhost'")` even though I use the correct password for both occurrences. Can use advise on where to go from here. Thank you.

**Comment by josephhyatt** [comment]
sorry, figured it out.

**Comment by josecalvillob** [comment]
> sorry, figured it out.

What did you do to fix the issue? I'm having the same issue myself and can't figure it out.

**Comment by Lemoners** [comment]
@josecalvillob 
You need to make sure your plugin for User 'root' is 'mysql_native_password' instead of 'auth_sock', which means that you can use mysql without sudo, and then things should work out.
