### ISSUE TITLE
"Invalid DSNs found in the config file." error when using login-path option with DB name

### ISSUE THREAD

**Issue by joestepp** [dbcli/mycli#768]
The follow command worked in mycli 1.19.0:

`mycli --login-path=<db_alias> --auto-vertical-output <db_name>`

It no longer works in 1.20.0, with the following error:

`Invalid DSNs found in the config file. Please check the "[alias_dsn]" section in myclirc.`.

The example in the documentation (https://www.mycli.net/loginpath) also no longer works, raising the same error as above:

`mycli --login-path my_server_alias my_database_name`.

These commands work:

`mycli --login-path=<db_alias>`
`mycli --login-path=<db_alias> --auto-vertical-output`

but tacking on the database name at the end raises the error.

System info:

macOS 10.14.6
zsh 5.7.1
MariaDB 10.2.21-MariaDB-log

**Comment by tsroten** [comment]
Hi @joestepp -- sorry for this bug, we'll get this fixed shortly (as in later today).

I appreciate you reporting this 👍

**Comment by tsroten** [comment]
@joestepp This should be fixed in [version 1.20.1](https://pypi.org/project/mycli/1.20.1/). Thanks again!

**Comment by joestepp** [comment]
@tsroten Thanks for quickly fixing this.
