### ISSUE TITLE
Mycli installed through AUR won't run

### ISSUE THREAD

**Issue by notaduck** [dbcli/mycli#770]
I just installed `mycli` on a brand new system but I keep getting this exception:

```
[~] mycli -h 127.0.0.2 -u root
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (sqlparse 0.3.0 (/usr/lib/python3.7/site-packages), Requirement.parse('sqlparse<0.3.0,>=0.2.2'), {'mycli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mycli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlparse<0.3.0,>=0.2.2' distribution was not found and is required by mycli

```

The current version of sqlparse is 0.3.0-1 however I've tried with 0.3.0 as well. The system it is installed on is Manjaro if that helps.

**Comment by notaduck** [comment]
So, I downgraded the package to version 0.2.2 however that doesn't fix the issue that installing mycli through AUR automaticly pulls the latest pytnol-sqlparse package which is 3.0.0-1

**Comment by tsroten** [comment]
Hello @notaduck! I'm sorry you had a difficult time installing mycli. So, the mycli team doesn't maintain the mycli packages on various Linux distributions. You'll want to let the package maintainer know about this. I'm guessing it might be this package? https://aur.archlinux.org/packages/mycli/

I'll leave this open so other people can track the issue 👍

**Comment by meeuw** [comment]
For the archlinux maintainer: I've backported the sqlparse (0.2.2) changes for Fedora in this branch https://github.com/dbcli/mycli/tree/backports/sqlparse-0.2.2

**Comment by nicolaiskogheim** [comment]
I have installed `mycli` through AUR, and it works as it should from what I can gather. I installed it three days ago. I'm on Antergos (what's left of Antergos anyway), which is also based on Arch linux like Manjaro.

```
$ mycli --version
Version: 1.20.1
```

**Comment by loonies** [comment]
Hi,

The maintainer of the AUR mycli package here.

The current version of mycli on Arch works without issues:

```
$ mycli --version
Version: 1.20.1

$ pacman -Q mycli 
mycli 1.20.1-1

$ pacman -Q $(expac -Q '%D' mycli)
python 3.8.0-1
python-click 7.0-3
python-configobj 5.0.6-6
python-cryptography 2.8-1
python-prompt_toolkit 3.0.2-1
python-pygments 2.5.2-1
python-pymysql 0.9.3-1
python-sqlparse 0.3.0-3
python-cli_helpers 1.2.0-1
```

Most of the time rebuild of mycli and maybe some dependencies solves the problem after system upgrade. Therefore, make sure your system, mycli dependencies, and mycli itself are up-to-date / rebuilt.

As far as I'm concerned this issue can be closed. Also, please report or forward all the build issues to the [mycli AUR](https://aur.archlinux.org/packages/mycli/) page, I'm not monitoring this bug tracker.
