### ISSUE TITLE
History search not working

### ISSUE THREAD

**Issue by mattlaw** [dbcli/mycli#772]
Attempting to search through history using `<C-r>` as described in https://www.mycli.net/history does nothing at all. The same keys work as expected in bash in the same terminal.

This is happening in version 1.5.2 on MacOS.

I've also attempted to achieve the same end by switching to Vi-mode and doing `<esc>?...` to no avail, not sure if that's supposed to work.

**Comment by mattlaw** [comment]
Upgrading fixed my problem, thanks. It was harder to do than I had hoped, as I needed ssh support, so I'm going to scribble down the steps I needed to take in the hope that it'll help others in the same situation:

Get `paramiko` installed in a place that `mycli` can see it:
```
/usr/local/Cellar/mycli/1.20.1_1/libexec/bin/pip install paramiko
```

MacOS will generate OPENSSH format private keys by default, paramiko apparently needs a PEM format; resetting the password can reformat a key in place:

```
$ cp -v ~/.ssh/id_rsa{,.pem}
$ ssh-keygen -p -m PEM -f ~/.ssh/id_rsa.pem
$ file ~/.ssh/id_rsa{,.pem}
~/.ssh/id_rsa:     OpenSSH private key
~/.ssh/id_rsa.pem: PEM RSA private key
```

**Comment by meeuw** [comment]
Thanks for your confirmation that @tsroten suggestion fixed your problem! You are right that paramiko doesn't support the OpenSSH private key format and the error message is awful `q must be exactly 160, 224, or 256 bits long`. I'll create a new issue for this.

**Comment by mattlaw** [comment]
`pip` is not part of the `mycil` homebrew installation at version 1.27.0. This worked for me at this version to enable ssh:

```
/opt/homebrew/Cellar/mycli/1.27.0/libexec/bin/python /opt/homebrew/lib/python3.12/site-packages/pip install paramiko
```
