### ISSUE TITLE
<C-x><C-e> in emacs mode ignores EDITOR

### ISSUE THREAD

**Issue by mattlaw** [dbcli/mycli#773]
Using `\e` to invoke an editor works as advertised, but the `C-xC-e` sequence does invoke an editor but it appears to always be `nano`.

**Comment by tsroten** [comment]
Hello @mattlaw! Would you mind running the following command from inside of mycli and seeing what the output is?

`system printenv EDITOR`

For example:
```
mycli> system printenv EDITOR
nvim
```

Thanks!

**Comment by mattlaw** [comment]
This is on Version 1.5.2 (latest on Ubuntu Xenial).

```
> system printenv EDITOR

Time: 0.012s
```
So it appears that it's not present in the environment at all. I'd been running mycli directly over ssh using `ssh -qt myvm bash -lc mycli`, but that `-l` wasn't enough to get bash to fully start up. Running with `EDITOR` _actually_ in the environment worked as expected; so PEBKAC, apologies.

However, under those conditions:

```
> system printenv EDITOR
Traceback (most recent call last):
  File "/usr/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.5.2', 'console_scripts', 'console')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/mycli/mycli/main.py", line 649, in cli
    mycli.run_cli()
  File "/usr/share/mycli/mycli/main.py", line 510, in run_cli
    self.output_via_pager('\n'.join(output))
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by tsroten** [comment]
@mattlaw I'm glad it's working for you now!

That particular error should be fixed in newer versions of mycli. We don't have any regular contributors managing OS-specific releases at this point in time. So, you might consider using [`pip` to install mycli](https://www.mycli.net/install) so you can get the newest version.
