### ISSUE TITLE
Issue with favorite queries that has positional parameters

### ISSUE THREAD

**Issue by OlegApanovich** [dbcli/mycli#788]
Such feature complete do not work for me. Even when I try to add new favorite query just like in documentation.
![Screenshot from 2019-10-14 13-08-49](https://user-images.githubusercontent.com/25242713/66744208-85d60400-ee84-11e9-8138-5a092ea77aff.png)
There always eror that query with do not exist 
![Screenshot from 2019-10-14 13-13-54](https://user-images.githubusercontent.com/25242713/66744303-c766af00-ee84-11e9-92ff-31ef20b2e860.png)
If I try do new favorite queries without positional parameters, than all work great.

**Comment by pasenor** [comment]
Your version of mycli is very out-of-date. This feature was added in version 1.14.0, you'll have to upgrade mycli if you want to use it. Please consult the [installation instructions](https://www.mycli.net/install) (and note that later versions only work with python 2.7+).

**Comment by OlegApanovich** [comment]
Thank you, it was version problem.
I install mycli on ubuntu 18.04 through standard 'apt-get install mycli' command. Now I uninstall it and install through 'pip install cli' command and it worked great.
