### ISSUE TITLE
changing output file prevents output

### ISSUE THREAD

**Issue by peterdutton** [dbcli/mycli#798]
Hi,

Firstly, thanks for a fantastic piece of software.

My issue is that if I direct output to a file, e.g:

`\o ~/output/file1.sql`

Then run a query (which outputs as normal), if I then direct to a different file using the same `\o` option, there is no output to that file, although there is no error in mycli itself. The only way to get the output working again is to `exit` and relaunch mycli.

Thanks for any advice you might have.

**Comment by pasenor** [comment]
Thanks for pointing it out, there is indeed a bug
