### ISSUE TITLE
Automatic reconnect to database

### ISSUE THREAD

**Issue by johshoff** [dbcli/mycli#8]
This is more "wish list" than "critical".

One of my favorite things with the default mysql CLI is that it'll reconnect if it can't connect to the database.

Currently, in mycli it just times out and never reconnects:

```
mysql> select * from foo
(2013, 'Lost connection to MySQL server during query ([Errno 60] Operation timed out)')
mysql> select * from foo
(2006, "MySQL server has gone away (error(32, 'Broken pipe'))")
```

Also, it's probably worth considering setting a lower connection timeout if this feature is implemented. It's quite high at the moment.

**Comment by diversario** [comment]
So, just to check – this is in master but not enabled?..

**Comment by amjith** [comment]
@diversario This was released a long time ago. Are you not seeing the reconnect prompt?

**Comment by diversario** [comment]
The prompt? Yes, I see it. I'm saying I'd like that to happen automatically, because right now if I issue a command and switch to a diff pane – often I come back to a reconnect prompt. It should be automatic, IMO, like in the `mysql` client.
