### ISSUE TITLE
How to make mycli use pspg as its pager

### ISSUE THREAD

**Issue by scottchiefbaker** [dbcli/mycli#803]
I just came across the `pspg` pager for Postgres/MySQL

https://github.com/okbob/pspg

It works well with the standard `mysql` cli tool, and I feel like it would be a great feature add if `mycli` supported it as well. 

I believe it should be pretty simple to add support for `pspg`. MyCLI would just have to output consistent tabular formatting and (optionally) send that output to `pspg`.

**Comment by markbrody** [comment]
I coincidentally came across this looking for a way to set pspg as the default pager and have just gotten it working.  You can explicitly set the pager in your current session with the `pager` or `\P` command, i.e.

```
> pager pspg;
```

Or by default, it appears that mycli uses the system environment variable `PAGER` if a value is not set.  Adding the following to your `.bashrc` or similar profile should do the trick.

```
export PAGER=pspg
```

**Comment by tsroten** [comment]
Wow, that's a really neat pager! In addition to the options that @markbrody mentioned, you can also set the pager permanently for mycli via your `~/.my.cnf` file:

```
[client]
pager=pspg
```

The advantage with that over `export PAGER=pspg` is that it won't affect other programs that use that environment variable.

**Comment by scottchiefbaker** [comment]
It just occurred to me why it wasn't working. I had the table format set incorrectly in my `.myclirc` 

Make sure you use:

    table_format = psql

In your `~/.myclirc`
