### ISSUE TITLE
Error connecting to mysql .....How to solve

### ISSUE THREAD

**Issue by heguohui2018** [dbcli/mycli#811]
mycli -h localhost -P 3306 -u root -p Heguohui@123456

error message :
/usr/local/Cellar/mycli/1.20.1_2/libexec/lib/python3.8/site-packages/mycli/main.py:224: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if arg is '':

(2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")

my use macOS :
system ：Catalina 10.15.3
mysql :  8.0

**Comment by laixintao** [comment]
Hi @heguohui2018 

Did you mysql server listen port 3306? Maybe it only allows connecting via socket file. have you tried without `-P` ? 

Also try connect with mysql official client see if can connect, or just use `nc` to test the connection first.

It doesn't seem to be an mycli issue.

**Comment by heguohui2018** [comment]
Can now be used normally，Is due to access restrictions,

Thank you

**Comment by laixintao** [comment]
@heguohui2018  Good to know, please kindly close this issue :)

**Comment by josecalvillob** [comment]
@heguohui2018 How did you fix the access restriction? I'm getting access denied as well

**Comment by josecalvillob** [comment]
@heguohui2018 Nevermind. I ran what you had

> mycli -h localhost -P 3306 -u root -p Heguohui@123456

but with my own credentials and changed my user from localhost to root and I logged right in 😀

**Comment by heguohui2018** [comment]
## Login mysql
## Refresh permissions，
mysql> flush privileges; 

 ## Add access permissions to resolve client failure to connect to the database
mysql>grant all privileges on *.* to 'root'@'localhost' with grant option;

## Restart mysql，Reconnect
