### ISSUE TITLE
Website uses not provided font

### ISSUE THREAD

**Issue by Hunman** [dbcli/mycli#815]
Couldn't find a public github project for the https://www.mycli.net/ page, so I'm making an issue here

In the page's CSS, the `Monaco` space is used in certain rules as a monospace font
This font however is not served, so the table on the https://www.mycli.net/commands page has fallen apart
![image](https://user-images.githubusercontent.com/7405480/75158575-b3766800-5716-11ea-822d-097f31a61504.png)
![image](https://user-images.githubusercontent.com/7405480/75158483-81650600-5716-11ea-9472-09fa360d6de8.png)

Either the `Monaco` font should be served as well, or a generic `monospace` font being used as a fallback one
```css
pre {
    font-family: Monaco, monospace; // Like this
}

**Comment by Hunman** [comment]
Oh, same thing also happening on the https://www.pgcli.com/ pages

**Comment by amjith** [comment]
That's awful. I'll see if I can fix that. :disappointed:

**Comment by amjith** [comment]
Can you check again? I believe I have fixed it.
