### ISSUE TITLE
Custom pager setting

### ISSUE THREAD

**Issue by seschwar** [dbcli/mycli#82]
In my `~/.my.cnf` I have the following, which only pages the output if it doesn't fit on the screen:

    [client]
    pager = less -FSX

It would be nice if mycli respected this setting or allows setting a pager of its own.

**Comment by amjith** [comment]
Reading the pager from my.cnf would be a nice addition. I'll add that in. But in the meantime I have two solutions for you. 

1. I've updated the default pager option used by mycli to '-FSXR' in the master branch. You can directly install from master to get the benefit right away. You can install from git as follows:

    pip install -U -e git+https://github.com/dbcli/mycli.git#egg=mycli

2. You can set the pager at the run time as follows:

    pager less -FSXR 

That will set the pager for the current session.

I'll work on parsing the pager from my.cnf in the meantime. Thank you!

**Comment by amjith** [comment]
This is now available in the latest version of mycli 1.1.1. Thanks to the PR from @j-bennet.

Please upgrade:

    pip install -U mycli

**Comment by seschwar** [comment]
Nice! Thanks, @amjith and @j-bennet.
