### ISSUE TITLE
`FORMAT` comes out with the wrong answer

### ISSUE THREAD

**Issue by Jamesking56** [dbcli/mycli#820]
Consider this query:

`SELECT FORMAT(100/100, 2);`

Official `mysql` client comes out with the correct answer of `1.00`

However, `mycli` comes out with `1`.

`FORMAT(<value>, 2)` enforces 2 decimal places to be displayed. For some reason, `mycli` ignores this.

**Comment by pasenor** [comment]
Hi, it is something that is not controlled by mycli itself: the underlying library pymysql returns a string that is already formatted, so this should just work, here is my output.
```(none) > select format(100/100, 3);                                                                                                                                                                                                                             
+--------------------+
| format(100/100, 3) |
+--------------------+
| 1.000              |
+--------------------+
1 row in set
```

Let's try to reproduce your issue: what is your OS, database version and `pip freeze` output? (in particular, the pymysql version)

**Comment by Jamesking56** [comment]
`mycli` version: 1.8.1
OS: Ubuntu 18.04.4 LTS
Database version: `10.0.38-MariaDB-1~xenial` (Docker) and I've also tested on `10.4.12-MariaDB-1:10.4.12+maria~bionic` (Docker)
`pip freeze` output: `command pip not found`

**Comment by pasenor** [comment]
You are running a very old version of mycli (unfortunately, it is not often updated in the ubuntu repositories). The easiest way to upgrade is through pip
```
sudo apt-get remove mycli
sudo apt-get install python-pip
sudo pip install --upgrade mycli
```

**Comment by Jamesking56** [comment]
@pasenor This fixed the issue :+1: thanks for your help
