### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by flamendless** [dbcli/mycli#834]
Hi, I cant connect using `mycli`.

I can easily connect with my previous setup with `/opt/lampp/bin/mysql -u root -p` (password is empty)

but with `mycli -u root -h localhost` I get
```
(2003, "Can't connect to MySQL server on 'localhost' ([Errno 2] No such file or directory)")
Failed to connect by socket, retrying over TCP/IP
(2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

```

**Comment by pasenor** [comment]
Hi, it seems mycli has trouble finding the socket file. It's something that will be improved in the next version, but for now you have to specify it explicitly with the argument  `--socket=/path/to/socket` if it is located anywhere other than `/var/run/mysqld/mysqld.sock`

**Comment by flamendless** [comment]
alright thanks, that works. My `mysql.socket` location is in `/opt/lampp/var/mysql/mysql.socket`
