### ISSUE TITLE
alias_dsn with ssl options

### ISSUE THREAD

**Issue by nbari** [dbcli/mycli#835]
How could I create/define an `alias_dsn`to use `--ssl-ca /path/to/crt`?

I have tried without sucess:

```
[alias_dsn]
test = mysql://root:secret@host/db --ssl-ca /path/to/crt
```

It is possible?

**Comment by pasenor** [comment]
Unfortunately, no. At the moment only hostname, port, username, password, and database name are extracted from the URI, for more than that you'd have to save mycli invocation with command line arguments in a script.
