### ISSUE TITLE
mycli doesn't work normally in my environment

### ISSUE THREAD

**Issue by tangerrine-tj** [dbcli/mycli#836]
My OS release is ubuntu 18.04, python version is 2.7.17. Mysql server-end is running in docker, and the version is 8.0. I pulled the official image from docker hub and the docker version is 19.03.8. 
Mycli could connect to mysql in docker, and run normally in single line mode. But when I input "delimiter $$", it shows (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'delimiter $$' at line 1"). And when I create cursor or procedure, it shows something like that.

**Comment by pasenor** [comment]
Hi, `DELIMITER` is not part of the SQL specification, it's a special command of  the standard `mysql` shell. It has been recently implemented in mycli, but not yet released. You may try to install from the github master branch: 
```
pip install git+https://github.com/dbcli/mycli.git
```
Also, I don't think there is an "official" mycli docker image, official packages are available on pypi. The way to dockerize them is to run `pip install --upgrade mycli` (or the above command) in a docker image that contains python.

**Comment by tangerrine-tj** [comment]
Thanks for reply, i mean official mysql docker image, not mycli docker image. Thank you very much, I'm gonna try the latest release.
