### ISSUE TITLE
new line (Alt+Enter) is not the start of the line.

### ISSUE THREAD

**Issue by yahwang** [dbcli/mycli#839]
OS: Ubuntu 18.04
Python: 3.7.5
mycli : 1.20.1 pgcli: 2.2.0

I want to use multi-line with mycli like pgcli does. My situation is like below image.

mycli (left) vs pgcli (right)

![2020-03-19-22:26](https://user-images.githubusercontent.com/12381530/77072636-5f1e8980-6a31-11ea-9d8f-d7a9c54d5e3c.png)

**Comment by amjith** [comment]
I've got a PR that'll let you do this once it is merged.
