### ISSUE TITLE
auto-completion of favorite names not working any more?

### ISSUE THREAD

**Issue by SamCritch** [dbcli/mycli#845]
Hi, mycli favorites are extremely useful, especially when you include variables. I have quite a lot of favorites reducing complex queries to a short statement. 

I'm fairly sure auto-completion used to work for favorite names. For example I could type `\f get_` and mycli would autocomplete with a list like:

`get_customers`
`get_transactions`
`get_logins`
[...]

This has stopped working fairly recently. Is it a config option?

**Comment by amjith** [comment]
Confirmed it is broken. :disappointed: 

I'll look into it. Thanks for reporting.

**Comment by amjith** [comment]
Hi. This is now fixed in master. You can install directly from master using 

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

The change should go out in the next version which will be released in about a week or so.

**Comment by amjith** [comment]
Newest version 1.21.1 released with the fix. 

Please upgrade: `pip install -U mycli`

**Comment by SamCritch** [comment]
Thanks amjith
