### ISSUE TITLE
Syntax error when running mycli with vcli

### ISSUE THREAD

**Issue by troyvit** [dbcli/mycli#851]
Hi,

I installed mycli on kde-neon (Ubuntu 18.04) a few days ago via pip and it worked great. However something about my install broke my version of vcli. I reinstalled vcli (also via pip) and now when I try to start mycli I receive this error:

```
$ mycli
Traceback (most recent call last):
  File "/home/vit/.local/bin/mycli", line 7, in <module>
    from mycli.main import cli
  File "/home/vit/.local/lib/python2.7/site-packages/mycli/main.py", line 44, in <module>
    from .config import (write_default_config, get_mylogin_cnf_path,
  File "/home/vit/.local/lib/python2.7/site-packages/mycli/config.py", line 28
    print(message, file=sys.stderr)
                       ^
SyntaxError: invalid syntax
```
Do you know what I need to do to get mycli back up and running and (maybe?) getting it to coexist peacefully with vcli?

Thanks in advance

**Comment by amjith** [comment]
Hi, 

vcli hasn't been updated in ages but mycli has released multiple new versions and their dependencies have diverged a lot.

To have them coexist, I'd recommend using [pipx](https://pipxproject.github.io/pipx/) to install them, which creates separate virtualenvs for each program. 

Eg: 

```
pip install --user pipx

pipx install vcli 

pipx install mycli
```

**Comment by Rozkipz** [comment]
Try installing v1.20.1 - The latest version doesn't seem to work with Python2

`
pip uninstall mycli
pip install -U mycli==v1.20.1
`

**Comment by troyvit** [comment]
Thanks both of you! As a workaround I've installed 1.20.1. When I have more time I'll a) figure out why I'm not using python 3 and b) try the virtual env.
