### ISSUE TITLE
when the line is too long, contents cannot be seen totally

### ISSUE THREAD

**Issue by makiThinks** [dbcli/mycli#859]
![image](https://user-images.githubusercontent.com/51020538/81171356-d357c100-8fce-11ea-82ff-df618a0811d7.png)

**Comment by pasenor** [comment]
Long strings may be truncated depending on the formatter used: a terminal table with overly long columns would be unusable (it seems your output is already messed up). 

Try switching to the vertical format
```
\T vertical
```
(or append `\G` at the end of your query)

**Comment by makiThinks** [comment]
it works! thanks!

**Comment by makiThinks** [comment]
> Long strings may be truncated depending on the formatter used: a terminal table with overly long columns would be unusable (it seems your output is already messed up).
> 
> Try switching to the vertical format
> 
> ```
> \T vertical
> ```
> 
> (or append `\G` at the end of your query)

it works! thanks!
