### ISSUE TITLE
NULL presentation is inconsistent

### ISSUE THREAD

**Issue by morgo** [dbcli/mycli#86]
In horizontal output it shows up as `<null>`, in vertical it is `none`.

It might make sense to use the word `NULL` in italics?

**Comment by amjith** [comment]
You are correct, I missed that part. I'll fix the vertical output. 

I'm not sure how to do italics in the console. So that might not happen.

Thank you for the report.

**Comment by morgo** [comment]
If not italics, maybe change the color?  It's not important as long as it is consistent.

**Comment by amjith** [comment]
I've fixed the inconsistency in master. You can install directly from master using pip: 

```
pip install https://github.com/dbcli/mycli/archive/master.zip
```

I'll publish a new version to brew this weekend.
