### ISSUE TITLE
Error on Linux (Ubuntu 18.04) version 1.21.x

### ISSUE THREAD

**Issue by cvetan** [dbcli/mycli#861]
I've installed mycli through pip.

When I try to run it, I get the following error:

```
Traceback (most recent call last):
  File "/home/cvetan/.local/bin/mycli", line 7, in <module>
    from mycli.main import cli
  File "/home/cvetan/.local/lib/python2.7/site-packages/mycli/main.py", line 44, in <module>
    from .config import (write_default_config, get_mylogin_cnf_path,
  File "/home/cvetan/.local/lib/python2.7/site-packages/mycli/config.py", line 28
    print(message, file=sys.stderr)
                       ^
SyntaxError: invalid syntax
```
I've tried installing version **1.21.0** also doesn't work. 

Version **1.20.1** works. 

So the issue is in the **1.21.x** versions.

**Comment by pasenor** [comment]
Version 1.21 dropped python2 support. Ubuntu 18.04 comes with python 3.6, you need to use it to install mycli:
```
apt-get intall python3 python3-pip
pip uninstall mycli
pip3 install mycli
```

**Comment by cvetan** [comment]
Don't know. But this what you suggested works. So not sure if this issue should be closed or not. :)

**Comment by hegyre** [comment]
Hellom

Having same issue on CentOS 7.8 with mycli 1.22.2
Only Python 2.7 was installed.

It may be a good idea to update the website ([Install tab](https://www.mycli.net/install)):
```
Install
Compatibility:
Mycli is tested on macOS and Linux. It runs on Python 2.7 and 3.4+.

Works well with unicode input/output.

NOTE: Python 2.6 support was dropped in mycli 1.9.0. If you're running Python 2.6, you'll want to install mycli 1.8.1.
```
Could be good to also write that version 1.21 dropped Python 2.7.

**Comment by pasenor** [comment]
> Could be good to also write that version 1.21 dropped Python 2.7.

Added that info to the website, thanks for pointing out.
