### ISSUE TITLE
mycli is very slow compared to regular mysql cli

### ISSUE THREAD

**Issue by guest73** [dbcli/mycli#873]
I tried a query on both CLIs but mycli is MUCH slower. What could be the reason for this and how to make it a bit faster.
The table has 100 records and I make a LIMITATION: select * FROM product limit 40;

![Screenshot at 2020-05-31 20-47-28](https://user-images.githubusercontent.com/4907799/83359010-0ac44e00-a380-11ea-8273-b92a26b051cf.png)

On a bigger dataset it's even worth.

Also why is my mariadb is identified as mysql on a promt with \t option?

**Comment by guest73** [comment]
My mycli.rc
[myclirc.txt](https://github.com/dbcli/mycli/files/4708110/myclirc.txt)

**Comment by pasenor** [comment]
The slow part is styling output with colors etc (although 4 seconds seems a little extreme for 40 rows). Actually, I have just tried to speed things up there. If you've installed mycli with pip, can you try to install `cli_helpers` from branch with the following command to see what it changes for you?
```pip uninstall cli_helpers && pip install git+https://github.com/dbcli/cli_helpers.git@cache-formatter#egg=cli_helpers```

**Comment by pasenor** [comment]
Another option is to use csv output (it's much faster) and a special pager like [pspg](https://github.com/okbob/pspg) or [visidata](https://www.visidata.org/). Here is a discussion about how to do it with pspg: https://github.com/dbcli/mycli/issues/803

**Comment by guest73** [comment]
Thanks for a quick response.
I'll try your suggestions.

**Comment by guest73** [comment]
Here is my new results
![Screenshot at 2020-06-01 10-40-36](https://user-images.githubusercontent.com/4907799/83387836-15b9c580-a3f6-11ea-965f-4a05fb123fa1.png)
I must say the improvement is amazing. Thank you very much!
