### ISSUE TITLE
Text clipped from output of show create table <Table>

### ISSUE THREAD

**Issue by wolterhv** [dbcli/mycli#875]
I have a table called **Table** with 12 columns and 2 constraints, and when I run the command 

    show create table Table;

The output doesn't show the complete description of the table creation.

The expected behaviour would be that the complete description of the table creation be shown.

Is there maybe a hard-coded limit on the amount of text that can be printed as output to this command (and possibly others as well) ?

**Comment by pasenor** [comment]
Special commands like `show create table` are treated like normal queries, so yes, table rendering imposes a limit. You can switch to vertical format
`\T vertical`
then the text will be displayed in full

**Comment by amjith** [comment]
@wolterhv There was an issue with the old version of `cli_helpers` which is a dependency of mycli that truncated output that was longer than 1000 chars. 

We have since fixed that issue. Can you try upgrading cli_helpers? 

```pip install -U cli_helpers```

**Comment by wolterhv** [comment]
@amjith Updating `cli_helpers` seems to have fixed it. Thanks!
@pasenor Thanks for the good tip, will definitely come in handy.
