### ISSUE TITLE
Add $XDG_CONFIG_HOME/mycli/.myclirc to sourcing configs

### ISSUE THREAD

**Issue by MYDavoodeh** [dbcli/mycli#879]
It seems that there is no config placeholder for myclirc under $XDG_CONFIG_HOME.

I'd like to suggest to add one proper address like
$XDG_CONFIG_HOME/mycli/.mysqlrc
or
$XDG_CONFIG_HOME/myclirc

**Comment by pasenor** [comment]
#808 added $XDG_CONFIG_HOME/mycli/myclirc
Does it work for you?

**Comment by MYDavoodeh** [comment]
Oh, I see that it is a merged request already.
No, it doesn't work for me but it is certainly a local problem now that I should find and debug rather than a missing feature.
In case I found a real bug I will make another issue for that.
Thanks for letting me know about that.

I am closing this issue since it is found obsolete.
