### ISSUE TITLE
PIP install results in error. 

### ISSUE THREAD

**Issue by autotune** [dbcli/mycli#88]
This is on CentOS 6.5:

[root@chef-solo logs]# cat /etc/redhat-release
CentOS release 6.5 (Final)

[foo@chef-solo ~]$ sudo pip uninstall mycli

[foo@chef-solo ~]$ mycli 

Traceback (most recent call last): File "/usr/bin/mycli", line 5, in <module> from pkg_resources import load_entry_point File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module> working_set.require(__requires__) File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require needed = self.resolve(parse_requirements(requirements)) File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve raise DistributionNotFound(req) pkg_resources.DistributionNotFound: six>=1.8

Running the package install directly does the trick though.

**Comment by amjith** [comment]
Sorry about the difficulty in getting started. 

Your command says `sudo pip uninstall mycli` did you really uninstall it or was that a typo? 

Also can you elaborate what you mean by 

> Running the package install directly does the trick though.

My suggestions are:

     pip install --upgrade --force-reinstall mycli 

or

    easy_install --upgrade mycli

If neither of those work then install directly from the git repo. 

    pip uninstall mycli && pip install https://github.com/dbcli/mycli/archive/master.zip

If you're still having trouble, please feel free to reopen the issue.

**Comment by autotune** [comment]
Hey,

That was a typo, consider it fixed. Running "sudo pip install mycli" is where the resulting error occur. Downloading directly and then running sudo python setup.py works. While this method does work, it really should work by downloading through "sudo pip install mycli."

**Comment by qw3rtman** [comment]
Was having the same issue on CentOS 6.5 (Final). Eventually solved it by executing `pip uninstall mycli && pip install https://github.com/dbcli/mycli/archive/master.zip` and then `easy_install --upgrade mycli`.

**Comment by amjith** [comment]
I've removed Six from being an explicit dependency for mycli. I hope that solves the issue in the future. I'll release a new version soon.
