### ISSUE TITLE
Can't connect, socket option seems ignored

### ISSUE THREAD

**Issue by xeron** [dbcli/mycli#887]
mycli 1.22.1
macOS 10.15.6
python 3.8.5

```
$ cat ~/.my.cnf
[client]
port    = 3306
socket  = /opt/local/var/run/mysql8/mysqld.sock
$ mycli -uroot --socket=/opt/local/var/run/mysql8/mysqld.sock
(2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
$ mysql -uroot
…
mysql>
```

According to `tcpdump` it still tries TCP connection to `3306`.

1.20.1 works just fine even without `--socket`:
```
$ mycli -uroot
mysql 8.0.21
mycli 1.20.1
```

**Comment by terjeros** [comment]
Reason seems to be that ssh_port has default value of 22 and this condition is always true:

```
if port or host or ssh_host or ssh_port:
        socket = ''
else:
```

https://github.com/dbcli/mycli/blob/master/mycli/main.py#L387

**Comment by xeron** [comment]
Anyone? This makes `mycli` completely unusable for me.

**Comment by Findus23** [comment]
@xeron In the meantime you can edit the `mycli/main.py` and remove the `or ssh_port` and it should work fine.

**Comment by xeron** [comment]
My patch to workaround this issue:

https://github.com/macports/macports-ports/pull/8671/files#diff-96b354fe038f157a65bbfa783516eb5d

**Comment by afreakk** [comment]
im still having this issue:
```
❯ mycli --version
Version: 1.24.1
```

works with regular `mysql` but not with `mycli`
```
❯ mycli -S .mysql/mysql.sock
(1698, "Access denied for user 'afreak'@'localhost'")

❯ mysql --socket=.mysql/mysql.sock                                                                                                                                                  nix-shell
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 215
Server version: 10.5.8-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

**Comment by weirdan** [comment]
@afreakk try adding `-P <some integer>` parameter. See #1001 for details
