### ISSUE TITLE
need about 2~3 mins to see the query result 

### ISSUE THREAD

**Issue by Leon-Huang** [dbcli/mycli#891]
![image](https://user-images.githubusercontent.com/16815164/89262027-9ea4e580-d661-11ea-894a-2cff8490faef.png)

Hi, in MySQL  server (windows), there's a sample database named `world` and several tables in it
using the command `SELECT * FROM city` command, the result will displayed after about 2~3 mins......
however MySQL workbench will show the query result immediately

**Comment by Leon-Huang** [comment]
![image](https://user-images.githubusercontent.com/16815164/89269519-8d150b00-d66c-11ea-853c-7276ebde05a4.png)

**Comment by pasenor** [comment]
Looks like a problem that was addressed in `cli_helpers==2.1.0`. If your version is lower, an upgrade may help.

**Comment by Leon-Huang** [comment]
> Looks like a problem that was addressed in `cli_helpers==2.1.0`. If your version is lower, an upgrade may help.

yes, my `cli_helpers` is 2.0.1, after upgrade to 2.1.0, it's perfect.
