### ISSUE TITLE
I can not use backquote in mycli when i use 'use' to change database, but it works in mysql.exe or mysqlsh.exe

### ISSUE THREAD

**Issue by Double-Wen** [dbcli/mycli#901]
in mycli:

![image](https://user-images.githubusercontent.com/44485638/95535418-fde4f480-0a1a-11eb-9615-54ca288cfc9d.png)

in normal mysql shell:

![image](https://user-images.githubusercontent.com/44485638/95535505-3389dd80-0a1b-11eb-9a42-a657260b9bb3.png)

**Comment by rolandwalker** [comment]
Hi!  Good point.
