### ISSUE TITLE
undefined function `_parsed_is_open_quote` in file `packages/parseutils.py`

### ISSUE THREAD

**Issue by shispt** [dbcli/mycli#907]
Here is the link: https://github.com/dbcli/mycli/blob/master/mycli/packages/parseutils.py#L234

**Comment by pasenor** [comment]
That's true, thanks for pointing out. But that function doesn't seem to be called, did you get this exception at runtime?

**Comment by shispt** [comment]
Mine runs fine, it's just my IDE prompts the warning.
