### ISSUE TITLE
'utf-8' codec can't decode bytes in position 2010-2011: invalid continuation byte

### ISSUE THREAD

**Issue by shanezhiu** [dbcli/mycli#908]
## mycli
Version: 1.22.2

## locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
## os
Linux version 5.9.0-1-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.0-15) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35.1) #1 SMP Debian 5.9.1-1 (2020-10-17)

## reproduce 

When I executed `show engine innodb status\G`, I got a message` 'utf-8' codec can't decode bytes in position 2010-2011: invalid continuation byte`.

**Comment by tinyRatP** [comment]
## Locale 

```diff
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
-  LC_ALL=
+ LC_ALL=en_US.UTF-8
```

## OS

Linux tenda 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux

I can't reproduce the problem. Maybe you should modify the `LC_ALL`.

**Comment by shanezhiu** [comment]
Yeah, it's works for me. Thank you very much.
