### ISSUE TITLE
Feature request: allow a pass a file instead of a password

### ISSUE THREAD

**Issue by jeromegit** [dbcli/mycli#910]
After reading https://www.netmeister.org/blog/passing-passwords.html I thought it would be a great idea to allow mycli to allow to pass a file using -p /file/path in lieu of a plain-text password.
This would make  mycli more secure

**Comment by Stuwang** [comment]
you can edit config file: ~/.myclirc, and the last line give a example for alias for database,

```
# Use the -d option to reference a DSN.
[alias_dsn]
# example_dsn = mysql://[user[:password]@][host][:port][/dbname]
```
see this https://www.mycli.net/config for detail

**Comment by jeromegit** [comment]
Thanks, @Stuwang , but the article above (https://www.netmeister.org/blog/passing-passwords.html) calls for a file that would be a short-lived FIFO file or STDIN with the typical "-p -" convention.

**Comment by claudiofreitas** [comment]
It is also possible to run `mysql_config_editor` to save an obfuscated file and pass the login_path when doing login.

References:
- https://www.mycli.net/loginpath
- https://dev.mysql.com/doc/refman/5.7/en/mysql-config-editor.html

**Comment by pasenor** [comment]
Option `--login-path` was added by @jeromegit in version 1.24.1
To recap, the password can now be specified in a number of ways:

- in ~/.my.cnf ([client] section)
- in ~/.mylogin.cnf through mysql_config_editor
- in a text file with --password-file
- in the --password argument
- interactively on the commad line.

**Comment by jeromegit** [comment]
Thanks for all your help, @pasenor !
