### ISSUE TITLE
New release compatible with sqlparse 0.4

### ISSUE THREAD

**Issue by frenzymadness** [dbcli/mycli#911]
Hello.
I see that the master here is compatible with sqlparse 0.4 (https://github.com/dbcli/mycli/commit/17f093d7b70ab2d9f3c6eababa041bf76f029aac) but the latest release is not and have requirement on sqlparse < 0.4. Would It be possible to release a new version of mycli?
Have a nice day.

**Comment by jfly** [comment]
It looks like this was taken care of in https://github.com/dbcli/mycli/commit/96e6c951f221d10be27d95fc5fbcdc8ce3710a7b. I think this issue can be closed.

**Comment by frenzymadness** [comment]
Thank you!
