### ISSUE TITLE
mycli startup error

### ISSUE THREAD

**Issue by achuanya** [dbcli/mycli#912]
## my information:
Operating system: Linux achuanPC 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux
MySQL: 8.0

```bash
Software library: archlinuxcn
Name: mycli
Version: 1.22.2-3
Figure: A Terminal Client for MySQL with AutoCompletion and Syntax Highlighting
Architecture: any
URL: https://github.com/dbcli/mycli
Software License: BSD
Group: None
Provide: None
Depends on: python python-click python-configobj python-cryptography python-prompt_toolkit
                  python-pygments python-pymysql python-sqlparse python-cli_helpers
Optional dependency: python-paramiko: SSH support
Conflict with it: none
Replace: None
Download size: 160.27 KiB
Installed size: 763.54 KiB
Packager: lilac (on behalf of Sasasu) <su@sasasu.me>
Compile Date: Wed 02 Dec 2020 07:35:41 PM CST
Verifier: MD5 check value SHA-256 check value digital signature
```

## error
```bash
Traceback (most recent call last):
  File "/usr/bin/mycli", line 33, in <module>
    sys.exit(load_entry_point('mycli==1.22.2', 'console_scripts', 'mycli')())
  File "/usr/bin/mycli", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: mycli
```

**Comment by pasenor** [comment]
Hi! How did you install mycli? It seems like you are trying to run it with a different python interpreter than the one used for installation

**Comment by achuanya** [comment]
an use it normally after downgrading.

> Hi! How did you install mycli? It seems like it is trying to run with a different python interpreter than the one used for installation

I installed it through sudo pacman -S mycli. The 1.22.2-3 version seems to be unavailable. I can use it normally after downgrading.

**Comment by sudaraka** [comment]
> I upgraded and installed it through sudo pacman -Syyu, version 1.22.2-3 seems to be unavailable, but it can be used normally after I downgrade

I had the same issue, my problem was an old version of sqlparser from AUR was left in the system and latest update to mycli is picking it up. Got it fixed by removing **python-sqlparse-cli_helpers** and re-installing mycli.
