### ISSUE TITLE
Copying results to clipboard

### ISSUE THREAD

**Issue by Wryte** [dbcli/mycli#939]
Hey all,

I've got a feature request that I could try help build if needed. (not a python dev 😬 ). I think it would be useful to be able to copy the results of a query directly into your clipboard. I often find myself using `tee` to write the output to a file just so I can copy it out of there and into slack or somewhere else. While this works I usually have to clean up the output of `tee` a bit since it includes everything like the prompt or me switching the output format with `\T`.

Not sure the best UX to achieve this but here are some suggestions:

- adding a `\cp` to the end of a query (eg. `SELECT 1 \cp`)
- starting and stopping using the clipboard with a command like `tee` (eg. `pbcopy` and `nopbcopy`)

Any thoughts?

PS. Thanks for this tool! It's a lot of fun to use.

**Comment by rolandwalker** [comment]
Hi!

In #916 we added a new special command `\|` that could help.

You mention `pbcopy` so perhaps you are on a Mac?  In that case the command would  look like
```
\| pbcopy; SELECT 1;
```

But to try this out, you'd have to be running the `master` branch; it isn't released yet.

**Comment by pasenor** [comment]
Another option is to delegate copying (and dealing with results in general) to the pager application. A good one is [visidata](https://github.com/saulpw/visidata), you can install it with `pip install visidata`, then set mycli output format to csv (`\T csv` on mycli prompt) and pager to vd (`\P vd -f csv`). Then you get a rich set of commands to operate on the result set: https://jsvine.github.io/visidata-cheat-sheet/en/

We should probably add it to the documentation.
