### ISSUE TITLE
Feature request : Read the ~/.mylogin.cnf file at startup

### ISSUE THREAD

**Issue by rapha8l** [dbcli/mycli#94]
Hi, 
Would it be possible that mycli takes ~/.my.cnf ?
Thanks

**Comment by mesirendon** [comment]
+1

**Comment by amjith** [comment]
It already does. It reads in username, password, host, database, socket, port attributes from my.cnf. If you have other attributes that you'd like to be honored, can you please list them?

**Comment by seagoj** [comment]
So is this documented somewhere? `mycli [servername]` doesn't seem to do it.

**Comment by amjith** [comment]
@seagoj I didn't know about the mylogin.cnf file. I might be able to add that in.

Too many ways to specify options, it's hard to keep up.

**Comment by tanji** [comment]
.mylogin.cnf is a windows thing. On Linux, the file used is ~/.my.cnf, as the OP said. It is conventional to use that file for user logins, so if you could add it to the list of parsed files that could be nice.

**Comment by seagoj** [comment]
@tanji [.mylogin.cnf](http://dev.mysql.com/doc/refman/5.6/en/mysql-config-editor.html) is not a "Windows thing". It allows you to store connection information in an encrypted file using mysql_config_editor.

**Comment by tanji** [comment]
@seagoj OK, it is MySQL 5.6 specific. If it's encrypted, how do you expect mycli to read it?

**Comment by seagoj** [comment]
@tanji 
> pass in the --login-path to the mysql call that should do it.

**Comment by seagoj** [comment]
Looks like pymysql doesn't support it, yet, so no such luck until they do.

**Comment by mesirendon** [comment]
I have a configuration that allows me to use a specific server and DB when requiered... so my `.my.cnf` file looks like this:

```
[clientServerName]
user=root
password=MySuperSecurePassword
host=remote.server.com
database=example
[clientAnotherServer]
...
```

Now... I have a function in my `.zshrc` file that allows me to connect to any DB
```
mycnc() {
        mysql --defaults-group-suffix=$1
}
```
So... if I need to connect to `ServerName` I just type `mycnc ServerName` and that's all.

Hope this conf helps you to add an option to use the tool reading right away the .my.cnf file

P.S. Great tool. Keep it growing ;)

**Comment by amjith** [comment]
@seagoj Thank you for filing the issue. 

@mesirendon There is a pending issue for supporting the `--default-group-suffix` option in mycli. Ref: #95

**Comment by tsroten** [comment]
I would also love to see `~/.mylogin.cnf` support so passwords aren't stored in plaintext. @jedy [provided the Python code to decrypt `~/.mylogin.cnf`](https://github.com/dbcli/mycli/issues/17#issuecomment-104175743).

**Comment by amjith** [comment]
@tsroten I'd be willing help shepherd a PR from you or anyone else. :)

**Comment by tsroten** [comment]
Okay, sure. I'll submit one.

- Thomas

**Comment by mdsrosa** [comment]
@tsroten Nicely done!
Well, If has already been merged. I think we can close this issue, correct? :)

**Comment by j-bennet** [comment]
Correct!

**Comment by amjith** [comment]
Yes this feature is complete. But there is one tiny issue. This PR brings in a new dependency pycrypto. 

Pycrypto is not an easy package to install on Windows. I'd like to make pycrypto an optional dependency, since it is only used to parse mylogin.cnf which is not used by everyone. 

But to answer the question of closing this issue. Yes. I'll close this issue and create a new one to make pycrypto optional.

**Comment by vr001** [comment]
@amjith @seagoj 
I don't see in the document anything mentioned about login path. 
https://pymysql.readthedocs.io/en/latest/modules/connections.html
Am I checking in the wrong place? Will appreciate if any one can post an example of how you are using currently. 
Also, sorry for bringing this discussion here.

**Comment by j-bennet** [comment]
@vr001 We have a documentation page about that here: http://www.mycli.net/loginpath.

**Comment by vr001** [comment]
@j-bennet Thanks. 

1) How to overwrite the host info on the login path using mycli?
2) I tried to connect using mycli using login path, but still i have been prompted to enter password.

**Comment by tsroten** [comment]
@vr001 You can specify a host that overrides what's in the login path like this:
```
mycli --host=localhost --login-path=qa
```

If you're prompted for your password it means that mycli was not able to connect using the username/password/host/port in the login path. Try to double-check that you set it correctly:
https://dev.mysql.com/doc/refman/5.7/en/mysql-config-editor.html

**Comment by vr001** [comment]
Thanks @tsroten . Answered my previous questions !!
