### ISSUE TITLE
auto completion for script.sql files 

### ISSUE THREAD

**Issue by JoffreyVerkade** [dbcli/mycli#955]
For example, I open mycli on a shell and the cwd is /home/user/sql_script.

It would be nice to have auto completion on the script files in the pwd.

prompt> source "hit tab" and the a list of available scripts in the cwd is popping up a bit like the keywords for SQL.

You'd only harvest the *.sql files on runtime for that folder. 

I hope I made sense :)

**Comment by pasenor** [comment]
It should already work with the special command `source`
![image](https://user-images.githubusercontent.com/11982173/107650637-c23f8d00-6c8f-11eb-9389-58b279e1bfde.png)

**Comment by JoffreyVerkade** [comment]
ah! you are right, I was using it without the ./ , thanks for clarifying that one.
