### ISSUE TITLE
Exception 1193, "Unknown system variable 'VERSION_COMMENT'"

### ISSUE THREAD

**Issue by jeffreytse** [dbcli/mycli#957]
When the MySQL server version is older than `5.0.22`, we will catch the error as below:

![image](https://user-images.githubusercontent.com/9413601/108316452-e4895b80-71f7-11eb-84b7-832b22e6ddc5.png)

MySQL server information:
![image](https://user-images.githubusercontent.com/9413601/108316956-9032ab80-71f8-11eb-9859-bf6fa2f93055.png)

**Comment by pasenor** [comment]
Fixed in #940. Please verify that the current master branch fixes the bug.

**Comment by pasenor** [comment]
released in version 1.24.1
