### ISSUE TITLE
Update prompt_toolkit for auto-completion on Windows 7 x64

### ISSUE THREAD

**Issue by gstewart** [dbcli/mycli#98]
I installed on Windows 7 x64 with:
```shell
pip install mycli
```
I am using `pip 7.1.0` and `python 3.4.3`.

I was getting no auto-completion, and also no completion when using `<TAB>` or `<C-Space>`.

I set `log_level = DEBUG` in `.myclirc` and I saw this in the logs

```log
2015-07-31 14:13:55,846 (9224/MainThread) mycli.key_bindings DEBUG - Detected <Tab> key.
2015-07-31 14:13:57,391 (9224/MainThread) mycli.key_bindings DEBUG - Detected <C-Space> key.
```
I tried it in the standard cmd.exe console and in the ConEmu console (which prompt_toolkit recommends for windows).

-----

I noticed some recent updates to https://github.com/jonathanslenders/python-prompt-toolkit for windows console. I updated the prompt_toolkit dependency in mycli's setup.py to `prompt_toolkit==0.45` from `0.42` and also had to update the six dependency to `six >= 1.9`.

I installed again with these versions and the auto-completion is working great! It now works for me in both the standard cmd.exe console and the ConEmu console.

I'm not sure how this would affect other system though, and if there was a specific reason it was using the older version of prompt_toolkit.

Let me know if you need any more information.

**Comment by amjith** [comment]
I'm surprised you weren't getting popups in Windows. 

I was able to get it on Window with Python 2.7. I didn't test it on Python 3. 

But I'm glad you tried it with a newer version of prompt_toolkit. I plan on upgrading soon. Hopefully this weekend I'll upgrade and test the changes and make a new release. 

Thank you for the report.

**Comment by illagrenan** [comment]
Auto-completing in ConEmu is also working for me after upgrade:

```
pip install prompt-toolkit six --upgrade
```

**Python `2.7.10`, Windows `8.1@x64`.**

**Comment by amjith** [comment]
New version (1.2.0) is released to pypi. 

You can upgrade using `pip install -U mycli`. 

New version has prompt_toolkit 0.45 as its dependency.
