### ISSUE TITLE
How to insall offline?

### ISSUE THREAD

**Issue by dujbo** [dbcli/mycli#987]
Thanks.

**Comment by j-bennet** [comment]
Mycli is a Python package. Pip has tools for downloading and installing those offline. Steps:

1. `mkdir /tmp/mycli_offline`
2. `cd /tmp/mycli_offline`
3. `pip download mycli` (this will download package and dependencies into current directory)
4. `pip install --no-index --find-links . mycli` (this will install mycli from current directory into current python interpreter).
