### ISSUE TITLE
No auto-completion for quotes,brackets,etc

### ISSUE THREAD

**Issue by shubham-cpp** [dbcli/mycli#994]
I dont know if this feature exists or not and its not mentioned in the docs as well but how can I get mycli to auto-complete **'**,**(**,etc.

Eg:
```sql
insert into students(roll_no,fname,lname) values (1001,'
```
Now this should automatically enter
```sql
insert into students(roll_no,fname,lname) values (1001,'')
```

**Comment by j-bennet** [comment]
Correct, we don't have this feature.

**Comment by shubham-cpp** [comment]
No issue, I could just edit the query with editor using `\e` as mention [here](https://www.mycli.net/editor)
